
package com.searshc.hs.som.thm.domain.sywr;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.7-b01-
 * Generated source version: 2.1
 * 
 */
@WebService(name = "ProfileSoap", targetNamespace = "http://www.epsilon.com/webservices/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ProfileSoap {


    /**
     * 
     * @param associateId
     * @param storeNumber
     * @param terminal
     * @param affinities
     * @param memberNumber
     * @param messageVersion
     * @param user
     * @param requestorID
     * @return
     *     returns com.searshc.hs.som.thm.domain.sywr.UpdateMemberAffinitySubscriptionsResponse.UpdateMemberAffinitySubscriptionsResult
     */
    @WebMethod(operationName = "UpdateMemberAffinitySubscriptions", action = "http://www.epsilon.com/webservices/UpdateMemberAffinitySubscriptions")
    @WebResult(name = "UpdateMemberAffinitySubscriptionsResult", targetNamespace = "http://www.epsilon.com/webservices/")
    @RequestWrapper(localName = "UpdateMemberAffinitySubscriptions", targetNamespace = "http://www.epsilon.com/webservices/", className = "com.searshc.hs.som.thm.domain.sywr.UpdateMemberAffinitySubscriptions")
    @ResponseWrapper(localName = "UpdateMemberAffinitySubscriptionsResponse", targetNamespace = "http://www.epsilon.com/webservices/", className = "com.searshc.hs.som.thm.domain.sywr.UpdateMemberAffinitySubscriptionsResponse")
    public com.searshc.hs.som.thm.domain.sywr.UpdateMemberAffinitySubscriptionsResponse.UpdateMemberAffinitySubscriptionsResult updateMemberAffinitySubscriptions(
        @WebParam(name = "MemberNumber", targetNamespace = "http://www.epsilon.com/webservices/")
        String memberNumber,
        @WebParam(name = "Affinities", targetNamespace = "http://www.epsilon.com/webservices/")
        ArrayOfAffinity affinities,
        @WebParam(name = "MessageVersion", targetNamespace = "http://www.epsilon.com/webservices/")
        String messageVersion,
        @WebParam(name = "RequestorID", targetNamespace = "http://www.epsilon.com/webservices/")
        String requestorID,
        @WebParam(name = "StoreNumber", targetNamespace = "http://www.epsilon.com/webservices/")
        String storeNumber,
        @WebParam(name = "Terminal", targetNamespace = "http://www.epsilon.com/webservices/")
        String terminal,
        @WebParam(name = "AssociateId", targetNamespace = "http://www.epsilon.com/webservices/")
        String associateId,
        @WebParam(name = "User", targetNamespace = "http://www.epsilon.com/webservices/")
        String user);

    /**
     * 
     * @param auditType
     * @param startDateTime
     * @param memberNumber
     * @param messageVersion
     * @param endDateTime
     * @param requestorID
     * @return
     *     returns com.searshc.hs.som.thm.domain.sywr.GetMemberAuditLookupResponse.GetMemberAuditResult
     */
    @WebMethod(operationName = "GetMemberAuditLookup", action = "http://www.epsilon.com/webservices/GetMemberAuditLookup")
    @WebResult(name = "GetMemberAuditResult", targetNamespace = "http://www.epsilon.com/webservices/")
    @RequestWrapper(localName = "GetMemberAuditLookup", targetNamespace = "http://www.epsilon.com/webservices/", className = "com.searshc.hs.som.thm.domain.sywr.GetMemberAuditLookup")
    @ResponseWrapper(localName = "GetMemberAuditLookupResponse", targetNamespace = "http://www.epsilon.com/webservices/", className = "com.searshc.hs.som.thm.domain.sywr.GetMemberAuditLookupResponse")
    public com.searshc.hs.som.thm.domain.sywr.GetMemberAuditLookupResponse.GetMemberAuditResult getMemberAuditLookup(
        @WebParam(name = "MemberNumber", targetNamespace = "http://www.epsilon.com/webservices/")
        String memberNumber,
        @WebParam(name = "MessageVersion", targetNamespace = "http://www.epsilon.com/webservices/")
        String messageVersion,
        @WebParam(name = "AuditType", targetNamespace = "http://www.epsilon.com/webservices/")
        String auditType,
        @WebParam(name = "RequestorID", targetNamespace = "http://www.epsilon.com/webservices/")
        String requestorID,
        @WebParam(name = "StartDateTime", targetNamespace = "http://www.epsilon.com/webservices/")
        String startDateTime,
        @WebParam(name = "EndDateTime", targetNamespace = "http://www.epsilon.com/webservices/")
        String endDateTime);

    /**
     * 
     * @param aliasName
     * @param time
     * @param storeNumber
     * @param source
     * @param memberNumber
     * @param messageVersion
     * @param associateID
     * @param transactionNumber
     * @param date
     * @param registerNumber
     * @param requestorID
     * @return
     *     returns com.searshc.hs.som.thm.domain.sywr.GetPartnerEnrollmentDetailsResponse.GetPartnerEnrollmentDetailsResult
     */
    @WebMethod(operationName = "GetPartnerEnrollmentDetails", action = "http://www.epsilon.com/webservices/GetPartnerEnrollmentDetails")
    @WebResult(name = "GetPartnerEnrollmentDetailsResult", targetNamespace = "http://www.epsilon.com/webservices/")
    @RequestWrapper(localName = "GetPartnerEnrollmentDetails", targetNamespace = "http://www.epsilon.com/webservices/", className = "com.searshc.hs.som.thm.domain.sywr.GetPartnerEnrollmentDetails")
    @ResponseWrapper(localName = "GetPartnerEnrollmentDetailsResponse", targetNamespace = "http://www.epsilon.com/webservices/", className = "com.searshc.hs.som.thm.domain.sywr.GetPartnerEnrollmentDetailsResponse")
    public com.searshc.hs.som.thm.domain.sywr.GetPartnerEnrollmentDetailsResponse.GetPartnerEnrollmentDetailsResult getPartnerEnrollmentDetails(
        @WebParam(name = "MemberNumber", targetNamespace = "http://www.epsilon.com/webservices/")
        String memberNumber,
        @WebParam(name = "Source", targetNamespace = "http://www.epsilon.com/webservices/")
        String source,
        @WebParam(name = "RequestorID", targetNamespace = "http://www.epsilon.com/webservices/")
        String requestorID,
        @WebParam(name = "StoreNumber", targetNamespace = "http://www.epsilon.com/webservices/")
        String storeNumber,
        @WebParam(name = "RegisterNumber", targetNamespace = "http://www.epsilon.com/webservices/")
        String registerNumber,
        @WebParam(name = "TransactionNumber", targetNamespace = "http://www.epsilon.com/webservices/")
        String transactionNumber,
        @WebParam(name = "AssociateID", targetNamespace = "http://www.epsilon.com/webservices/")
        String associateID,
        @WebParam(name = "Date", targetNamespace = "http://www.epsilon.com/webservices/")
        String date,
        @WebParam(name = "Time", targetNamespace = "http://www.epsilon.com/webservices/")
        String time,
        @WebParam(name = "AliasName", targetNamespace = "http://www.epsilon.com/webservices/")
        String aliasName,
        @WebParam(name = "MessageVersion", targetNamespace = "http://www.epsilon.com/webservices/")
        String messageVersion);

    /**
     * 
     * @param parameters
     * @return
     *     returns java.lang.Object
     */
    @WebMethod(operationName = "GetMemberTargetedOffers", action = "http://www.epsilon.com/webservices/GetMemberTargetedOffers")
    @WebResult(name = "GetMemberTargetedOffersResponse", targetNamespace = "http://www.epsilon.com/webservices/", partName = "parameters")
    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
    public Object getMemberTargetedOffers(
        @WebParam(name = "GetMemberTargetedOffers", targetNamespace = "http://www.epsilon.com/webservices/", partName = "parameters")
        GetMemberTargetedOffers parameters);

    /**
     * 
     * @param currentTime
     * @param memberNumber
     * @param messageVersion
     * @param currentDate
     * @param pinNumber
     * @param requestorID
     * @return
     *     returns com.searshc.hs.som.thm.domain.sywr.ValidatePinResponse.ValidatePinResult
     */
    @WebMethod(operationName = "ValidatePin", action = "http://www.epsilon.com/webservices/ValidatePin")
    @WebResult(name = "ValidatePinResult", targetNamespace = "http://www.epsilon.com/webservices/")
    @RequestWrapper(localName = "ValidatePin", targetNamespace = "http://www.epsilon.com/webservices/", className = "com.searshc.hs.som.thm.domain.sywr.ValidatePin")
    @ResponseWrapper(localName = "ValidatePinResponse", targetNamespace = "http://www.epsilon.com/webservices/", className = "com.searshc.hs.som.thm.domain.sywr.ValidatePinResponse")
    public com.searshc.hs.som.thm.domain.sywr.ValidatePinResponse.ValidatePinResult validatePin(
        @WebParam(name = "MemberNumber", targetNamespace = "http://www.epsilon.com/webservices/")
        String memberNumber,
        @WebParam(name = "RequestorID", targetNamespace = "http://www.epsilon.com/webservices/")
        String requestorID,
        @WebParam(name = "CurrentDate", targetNamespace = "http://www.epsilon.com/webservices/")
        String currentDate,
        @WebParam(name = "CurrentTime", targetNamespace = "http://www.epsilon.com/webservices/")
        String currentTime,
        @WebParam(name = "PinNumber", targetNamespace = "http://www.epsilon.com/webservices/")
        String pinNumber,
        @WebParam(name = "MessageVersion", targetNamespace = "http://www.epsilon.com/webservices/")
        String messageVersion);

    /**
     * 
     * @param memberNumber
     * @param messageVersion
     * @param requestorID
     * @return
     *     returns com.searshc.hs.som.thm.domain.sywr.GetMemberLevelResponse.GetMemberLevelResult
     */
    @WebMethod(operationName = "GetMemberLevel", action = "http://www.epsilon.com/webservices/GetMemberLevel")
    @WebResult(name = "GetMemberLevelResult", targetNamespace = "http://www.epsilon.com/webservices/")
    @RequestWrapper(localName = "GetMemberLevel", targetNamespace = "http://www.epsilon.com/webservices/", className = "com.searshc.hs.som.thm.domain.sywr.GetMemberLevel")
    @ResponseWrapper(localName = "GetMemberLevelResponse", targetNamespace = "http://www.epsilon.com/webservices/", className = "com.searshc.hs.som.thm.domain.sywr.GetMemberLevelResponse")
    public com.searshc.hs.som.thm.domain.sywr.GetMemberLevelResponse.GetMemberLevelResult getMemberLevel(
        @WebParam(name = "MemberNumber", targetNamespace = "http://www.epsilon.com/webservices/")
        String memberNumber,
        @WebParam(name = "MessageVersion", targetNamespace = "http://www.epsilon.com/webservices/")
        String messageVersion,
        @WebParam(name = "RequestorID", targetNamespace = "http://www.epsilon.com/webservices/")
        String requestorID);

    /**
     * 
     * @param currentTime
     * @param storeNumber
     * @param memberNumber
     * @param messageVersion
     * @param currentDate
     * @param associateID
     * @param requestorID
     * @return
     *     returns com.searshc.hs.som.thm.domain.sywr.GetRewardBalanceResponse.GetRewardBalanceResult
     */
    @WebMethod(operationName = "GetRewardBalance", action = "http://www.epsilon.com/webservices/GetRewardBalance")
    @WebResult(name = "GetRewardBalanceResult", targetNamespace = "http://www.epsilon.com/webservices/")
    @RequestWrapper(localName = "GetRewardBalance", targetNamespace = "http://www.epsilon.com/webservices/", className = "com.searshc.hs.som.thm.domain.sywr.GetRewardBalance")
    @ResponseWrapper(localName = "GetRewardBalanceResponse", targetNamespace = "http://www.epsilon.com/webservices/", className = "com.searshc.hs.som.thm.domain.sywr.GetRewardBalanceResponse")
    public com.searshc.hs.som.thm.domain.sywr.GetRewardBalanceResponse.GetRewardBalanceResult getRewardBalance(
        @WebParam(name = "RequestorID", targetNamespace = "http://www.epsilon.com/webservices/")
        String requestorID,
        @WebParam(name = "StoreNumber", targetNamespace = "http://www.epsilon.com/webservices/")
        String storeNumber,
        @WebParam(name = "CurrentDate", targetNamespace = "http://www.epsilon.com/webservices/")
        String currentDate,
        @WebParam(name = "CurrentTime", targetNamespace = "http://www.epsilon.com/webservices/")
        String currentTime,
        @WebParam(name = "AssociateID", targetNamespace = "http://www.epsilon.com/webservices/")
        String associateID,
        @WebParam(name = "MemberNumber", targetNamespace = "http://www.epsilon.com/webservices/")
        String memberNumber,
        @WebParam(name = "MessageVersion", targetNamespace = "http://www.epsilon.com/webservices/")
        String messageVersion);

    /**
     * 
     * @param extendedProfilePreferences
     * @param memberNumber
     * @return
     *     returns com.searshc.hs.som.thm.domain.sywr.UpdateMemberExtendedProfileResponse.UpdateMemberExtendedProfileResult
     */
    @WebMethod(operationName = "UpdateMemberExtendedProfile", action = "http://www.epsilon.com/webservices/UpdateMemberExtendedProfile")
    @WebResult(name = "UpdateMemberExtendedProfileResult", targetNamespace = "http://www.epsilon.com/webservices/")
    @RequestWrapper(localName = "UpdateMemberExtendedProfile", targetNamespace = "http://www.epsilon.com/webservices/", className = "com.searshc.hs.som.thm.domain.sywr.UpdateMemberExtendedProfile")
    @ResponseWrapper(localName = "UpdateMemberExtendedProfileResponse", targetNamespace = "http://www.epsilon.com/webservices/", className = "com.searshc.hs.som.thm.domain.sywr.UpdateMemberExtendedProfileResponse")
    public com.searshc.hs.som.thm.domain.sywr.UpdateMemberExtendedProfileResponse.UpdateMemberExtendedProfileResult updateMemberExtendedProfile(
        @WebParam(name = "MemberNumber", targetNamespace = "http://www.epsilon.com/webservices/")
        String memberNumber,
        @WebParam(name = "ExtendedProfilePreferences", targetNamespace = "http://www.epsilon.com/webservices/")
        ArrayOfExtendedProfilePreference extendedProfilePreferences);

    /**
     * 
     * @param parameters
     * @return
     *     returns java.lang.Object
     */
    @WebMethod(operationName = "DateTimeOnServer", action = "http://www.epsilon.com/webservices/DateTimeOnServer")
    @WebResult(name = "DateTimeOnServerResponse", targetNamespace = "http://www.epsilon.com/webservices/", partName = "parameters")
    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
    public Object dateTimeOnServer(
        @WebParam(name = "DateTimeOnServer", targetNamespace = "http://www.epsilon.com/webservices/", partName = "parameters")
        Object parameters);

    /**
     * 
     * @param currentTime
     * @param memberNumber
     * @param currentDate
     * @param messageVersion
     * @param emailAddress
     * @param emailConfirmed
     * @param requestorID
     * @return
     *     returns com.searshc.hs.som.thm.domain.sywr.UpdateEmailConfirmedResponse.UpdateEmailConfirmedResult
     */
    @WebMethod(operationName = "UpdateEmailConfirmed", action = "http://www.epsilon.com/webservices/UpdateEmailConfirmed")
    @WebResult(name = "UpdateEmailConfirmedResult", targetNamespace = "http://www.epsilon.com/webservices/")
    @RequestWrapper(localName = "UpdateEmailConfirmed", targetNamespace = "http://www.epsilon.com/webservices/", className = "com.searshc.hs.som.thm.domain.sywr.UpdateEmailConfirmed")
    @ResponseWrapper(localName = "UpdateEmailConfirmedResponse", targetNamespace = "http://www.epsilon.com/webservices/", className = "com.searshc.hs.som.thm.domain.sywr.UpdateEmailConfirmedResponse")
    public com.searshc.hs.som.thm.domain.sywr.UpdateEmailConfirmedResponse.UpdateEmailConfirmedResult updateEmailConfirmed(
        @WebParam(name = "MessageVersion", targetNamespace = "http://www.epsilon.com/webservices/")
        String messageVersion,
        @WebParam(name = "MemberNumber", targetNamespace = "http://www.epsilon.com/webservices/")
        String memberNumber,
        @WebParam(name = "RequestorID", targetNamespace = "http://www.epsilon.com/webservices/")
        String requestorID,
        @WebParam(name = "CurrentDate", targetNamespace = "http://www.epsilon.com/webservices/")
        String currentDate,
        @WebParam(name = "CurrentTime", targetNamespace = "http://www.epsilon.com/webservices/")
        String currentTime,
        @WebParam(name = "EmailAddress", targetNamespace = "http://www.epsilon.com/webservices/")
        String emailAddress,
        @WebParam(name = "EmailConfirmed", targetNamespace = "http://www.epsilon.com/webservices/")
        String emailConfirmed);

    /**
     * 
     * @param lastName
     * @param memberNumber
     * @param messageVersion
     * @param emailAddress
     * @param searchType
     * @param maxPOSPrompt
     * @param currentTime
     * @param storeNumber
     * @param maxRecords
     * @param phoneNumber
     * @param terminal
     * @param currentDate
     * @param zipCode
     * @param firstName
     * @param requestorID
     * @return
     *     returns com.searshc.hs.som.thm.domain.sywr.GetMemberLookupResponse.GetMemberLookupResult
     */
    @WebMethod(operationName = "GetMemberLookup", action = "http://www.epsilon.com/webservices/GetMemberLookup")
    @WebResult(name = "GetMemberLookupResult", targetNamespace = "http://www.epsilon.com/webservices/")
    @RequestWrapper(localName = "GetMemberLookup", targetNamespace = "http://www.epsilon.com/webservices/", className = "com.searshc.hs.som.thm.domain.sywr.GetMemberLookup")
    @ResponseWrapper(localName = "GetMemberLookupResponse", targetNamespace = "http://www.epsilon.com/webservices/", className = "com.searshc.hs.som.thm.domain.sywr.GetMemberLookupResponse")
    public com.searshc.hs.som.thm.domain.sywr.GetMemberLookupResponse.GetMemberLookupResult getMemberLookup(
        @WebParam(name = "MessageVersion", targetNamespace = "http://www.epsilon.com/webservices/")
        String messageVersion,
        @WebParam(name = "MemberNumber", targetNamespace = "http://www.epsilon.com/webservices/")
        String memberNumber,
        @WebParam(name = "EmailAddress", targetNamespace = "http://www.epsilon.com/webservices/")
        String emailAddress,
        @WebParam(name = "PhoneNumber", targetNamespace = "http://www.epsilon.com/webservices/")
        String phoneNumber,
        @WebParam(name = "StoreNumber", targetNamespace = "http://www.epsilon.com/webservices/")
        String storeNumber,
        @WebParam(name = "Terminal", targetNamespace = "http://www.epsilon.com/webservices/")
        String terminal,
        @WebParam(name = "RequestorID", targetNamespace = "http://www.epsilon.com/webservices/")
        String requestorID,
        @WebParam(name = "SearchType", targetNamespace = "http://www.epsilon.com/webservices/")
        String searchType,
        @WebParam(name = "CurrentDate", targetNamespace = "http://www.epsilon.com/webservices/")
        String currentDate,
        @WebParam(name = "CurrentTime", targetNamespace = "http://www.epsilon.com/webservices/")
        String currentTime,
        @WebParam(name = "MaxRecords", targetNamespace = "http://www.epsilon.com/webservices/")
        String maxRecords,
        @WebParam(name = "MaxPOSPrompt", targetNamespace = "http://www.epsilon.com/webservices/")
        String maxPOSPrompt,
        @WebParam(name = "FirstName", targetNamespace = "http://www.epsilon.com/webservices/")
        String firstName,
        @WebParam(name = "LastName", targetNamespace = "http://www.epsilon.com/webservices/")
        String lastName,
        @WebParam(name = "ZipCode", targetNamespace = "http://www.epsilon.com/webservices/")
        String zipCode);

    /**
     * 
     * @param currentTime
     * @param memberNumber
     * @param currentDate
     * @param messageVersion
     * @param pinNumber
     * @param requestorID
     * @return
     *     returns com.searshc.hs.som.thm.domain.sywr.UpdateMemberPinResponse.UpdateMemberPinResult
     */
    @WebMethod(operationName = "UpdateMemberPin", action = "http://www.epsilon.com/webservices/UpdateMemberPin")
    @WebResult(name = "UpdateMemberPinResult", targetNamespace = "http://www.epsilon.com/webservices/")
    @RequestWrapper(localName = "UpdateMemberPin", targetNamespace = "http://www.epsilon.com/webservices/", className = "com.searshc.hs.som.thm.domain.sywr.UpdateMemberPin")
    @ResponseWrapper(localName = "UpdateMemberPinResponse", targetNamespace = "http://www.epsilon.com/webservices/", className = "com.searshc.hs.som.thm.domain.sywr.UpdateMemberPinResponse")
    public com.searshc.hs.som.thm.domain.sywr.UpdateMemberPinResponse.UpdateMemberPinResult updateMemberPin(
        @WebParam(name = "MessageVersion", targetNamespace = "http://www.epsilon.com/webservices/")
        String messageVersion,
        @WebParam(name = "MemberNumber", targetNamespace = "http://www.epsilon.com/webservices/")
        String memberNumber,
        @WebParam(name = "RequestorID", targetNamespace = "http://www.epsilon.com/webservices/")
        String requestorID,
        @WebParam(name = "CurrentDate", targetNamespace = "http://www.epsilon.com/webservices/")
        String currentDate,
        @WebParam(name = "CurrentTime", targetNamespace = "http://www.epsilon.com/webservices/")
        String currentTime,
        @WebParam(name = "PinNumber", targetNamespace = "http://www.epsilon.com/webservices/")
        String pinNumber);

    /**
     * 
     * @param wirelessPermissionFlag
     * @param affinities
     * @param memberNumber
     * @param messageVersion
     * @param enrollmentOfferCode
     * @param state
     * @param address1
     * @param address2
     * @param tnCStatus
     * @param clubDNPStatus
     * @param preferredLanguage
     * @param city
     * @param zipCodeExtension
     * @param terminal
     * @param zipCode
     * @param firstName
     * @param cardDesignType
     * @param clubEmailOptStatus
     * @param lastName
     * @param countryCode
     * @param emailAddress
     * @param pinNumber
     * @param phoneNumbers
     * @param suffix
     * @param currentTime
     * @param storeNumber
     * @param shcAssociateInd
     * @param currentDate
     * @param prefix
     * @param dob
     * @param middleInitial
     * @param attributes
     * @param testAccount
     * @param clubMembershipCreatedBy
     * @param tnCVersion
     * @param requestorID
     * @return
     *     returns com.searshc.hs.som.thm.domain.sywr.CreateMemberResponse.CreateMemberResult
     */
    @WebMethod(operationName = "CreateMember", action = "http://www.epsilon.com/webservices/CreateMember")
    @WebResult(name = "CreateMemberResult", targetNamespace = "http://www.epsilon.com/webservices/")
    @RequestWrapper(localName = "CreateMember", targetNamespace = "http://www.epsilon.com/webservices/", className = "com.searshc.hs.som.thm.domain.sywr.CreateMember")
    @ResponseWrapper(localName = "CreateMemberResponse", targetNamespace = "http://www.epsilon.com/webservices/", className = "com.searshc.hs.som.thm.domain.sywr.CreateMemberResponse")
    public com.searshc.hs.som.thm.domain.sywr.CreateMemberResponse.CreateMemberResult createMember(
        @WebParam(name = "MemberNumber", targetNamespace = "http://www.epsilon.com/webservices/")
        String memberNumber,
        @WebParam(name = "EmailAddress", targetNamespace = "http://www.epsilon.com/webservices/")
        String emailAddress,
        @WebParam(name = "Prefix", targetNamespace = "http://www.epsilon.com/webservices/")
        String prefix,
        @WebParam(name = "Suffix", targetNamespace = "http://www.epsilon.com/webservices/")
        String suffix,
        @WebParam(name = "FirstName", targetNamespace = "http://www.epsilon.com/webservices/")
        String firstName,
        @WebParam(name = "MiddleInitial", targetNamespace = "http://www.epsilon.com/webservices/")
        String middleInitial,
        @WebParam(name = "TestAccount", targetNamespace = "http://www.epsilon.com/webservices/")
        String testAccount,
        @WebParam(name = "LastName", targetNamespace = "http://www.epsilon.com/webservices/")
        String lastName,
        @WebParam(name = "Address1", targetNamespace = "http://www.epsilon.com/webservices/")
        String address1,
        @WebParam(name = "Address2", targetNamespace = "http://www.epsilon.com/webservices/")
        String address2,
        @WebParam(name = "City", targetNamespace = "http://www.epsilon.com/webservices/")
        String city,
        @WebParam(name = "State", targetNamespace = "http://www.epsilon.com/webservices/")
        String state,
        @WebParam(name = "ZipCode", targetNamespace = "http://www.epsilon.com/webservices/")
        String zipCode,
        @WebParam(name = "ZipCodeExtension", targetNamespace = "http://www.epsilon.com/webservices/")
        String zipCodeExtension,
        @WebParam(name = "CountryCode", targetNamespace = "http://www.epsilon.com/webservices/")
        String countryCode,
        @WebParam(name = "DOB", targetNamespace = "http://www.epsilon.com/webservices/")
        String dob,
        @WebParam(name = "CurrentDate", targetNamespace = "http://www.epsilon.com/webservices/")
        String currentDate,
        @WebParam(name = "CurrentTime", targetNamespace = "http://www.epsilon.com/webservices/")
        String currentTime,
        @WebParam(name = "ClubMembershipCreatedBy", targetNamespace = "http://www.epsilon.com/webservices/")
        String clubMembershipCreatedBy,
        @WebParam(name = "ClubDNPStatus", targetNamespace = "http://www.epsilon.com/webservices/")
        String clubDNPStatus,
        @WebParam(name = "SHCAssociateInd", targetNamespace = "http://www.epsilon.com/webservices/")
        String shcAssociateInd,
        @WebParam(name = "CardDesignType", targetNamespace = "http://www.epsilon.com/webservices/")
        String cardDesignType,
        @WebParam(name = "WirelessPermissionFlag", targetNamespace = "http://www.epsilon.com/webservices/")
        String wirelessPermissionFlag,
        @WebParam(name = "ClubEmailOptStatus", targetNamespace = "http://www.epsilon.com/webservices/")
        String clubEmailOptStatus,
        @WebParam(name = "PreferredLanguage", targetNamespace = "http://www.epsilon.com/webservices/")
        String preferredLanguage,
        @WebParam(name = "StoreNumber", targetNamespace = "http://www.epsilon.com/webservices/")
        String storeNumber,
        @WebParam(name = "Terminal", targetNamespace = "http://www.epsilon.com/webservices/")
        String terminal,
        @WebParam(name = "RequestorID", targetNamespace = "http://www.epsilon.com/webservices/")
        String requestorID,
        @WebParam(name = "MessageVersion", targetNamespace = "http://www.epsilon.com/webservices/")
        String messageVersion,
        @WebParam(name = "EnrollmentOfferCode", targetNamespace = "http://www.epsilon.com/webservices/")
        String enrollmentOfferCode,
        @WebParam(name = "PinNumber", targetNamespace = "http://www.epsilon.com/webservices/")
        String pinNumber,
        @WebParam(name = "TnCStatus", targetNamespace = "http://www.epsilon.com/webservices/")
        String tnCStatus,
        @WebParam(name = "TnCVersion", targetNamespace = "http://www.epsilon.com/webservices/")
        String tnCVersion,
        @WebParam(name = "PhoneNumbers", targetNamespace = "http://www.epsilon.com/webservices/")
        ArrayOfPhone phoneNumbers,
        @WebParam(name = "Affinities", targetNamespace = "http://www.epsilon.com/webservices/")
        ArrayOfAffinity affinities,
        @WebParam(name = "Attributes", targetNamespace = "http://www.epsilon.com/webservices/")
        ArrayOfAttr attributes);

    /**
     * 
     * @param memberNumber
     * @param messageVersion
     * @param registrationUniqueId
     * @param serviceRegistrationNumber
     * @param date
     * @param serviceUnenrollmentDate
     * @param aliasName
     * @param time
     * @param storeNumber
     * @param source
     * @param associateID
     * @param registrationIndicator
     * @param transactionNumber
     * @param enrollmentIndicator
     * @param registerNumber
     * @param unenrollmentDate
     * @param mobileNumber
     * @param serviceEnrollmentDate
     * @param enrollmentDate
     * @param memberUniqueId
     * @param requestorID
     * @return
     *     returns com.searshc.hs.som.thm.domain.sywr.CreatePartnerEnrollmentDetailsResponse.CreatePartnerEnrollmentDetailsResult
     */
    @WebMethod(operationName = "CreatePartnerEnrollmentDetails", action = "http://www.epsilon.com/webservices/CreatePartnerEnrollmentDetails")
    @WebResult(name = "CreatePartnerEnrollmentDetailsResult", targetNamespace = "http://www.epsilon.com/webservices/")
    @RequestWrapper(localName = "CreatePartnerEnrollmentDetails", targetNamespace = "http://www.epsilon.com/webservices/", className = "com.searshc.hs.som.thm.domain.sywr.CreatePartnerEnrollmentDetails")
    @ResponseWrapper(localName = "CreatePartnerEnrollmentDetailsResponse", targetNamespace = "http://www.epsilon.com/webservices/", className = "com.searshc.hs.som.thm.domain.sywr.CreatePartnerEnrollmentDetailsResponse")
    public com.searshc.hs.som.thm.domain.sywr.CreatePartnerEnrollmentDetailsResponse.CreatePartnerEnrollmentDetailsResult createPartnerEnrollmentDetails(
        @WebParam(name = "MemberUniqueId", targetNamespace = "http://www.epsilon.com/webservices/")
        String memberUniqueId,
        @WebParam(name = "MemberNumber", targetNamespace = "http://www.epsilon.com/webservices/")
        String memberNumber,
        @WebParam(name = "RegistrationUniqueId", targetNamespace = "http://www.epsilon.com/webservices/")
        String registrationUniqueId,
        @WebParam(name = "ServiceRegistrationNumber", targetNamespace = "http://www.epsilon.com/webservices/")
        String serviceRegistrationNumber,
        @WebParam(name = "EnrollmentDate", targetNamespace = "http://www.epsilon.com/webservices/")
        String enrollmentDate,
        @WebParam(name = "UnenrollmentDate", targetNamespace = "http://www.epsilon.com/webservices/")
        String unenrollmentDate,
        @WebParam(name = "MobileNumber", targetNamespace = "http://www.epsilon.com/webservices/")
        String mobileNumber,
        @WebParam(name = "RegistrationIndicator", targetNamespace = "http://www.epsilon.com/webservices/")
        String registrationIndicator,
        @WebParam(name = "EnrollmentIndicator", targetNamespace = "http://www.epsilon.com/webservices/")
        String enrollmentIndicator,
        @WebParam(name = "Source", targetNamespace = "http://www.epsilon.com/webservices/")
        String source,
        @WebParam(name = "ServiceEnrollmentDate", targetNamespace = "http://www.epsilon.com/webservices/")
        String serviceEnrollmentDate,
        @WebParam(name = "ServiceUnenrollmentDate", targetNamespace = "http://www.epsilon.com/webservices/")
        String serviceUnenrollmentDate,
        @WebParam(name = "StoreNumber", targetNamespace = "http://www.epsilon.com/webservices/")
        String storeNumber,
        @WebParam(name = "RequestorID", targetNamespace = "http://www.epsilon.com/webservices/")
        String requestorID,
        @WebParam(name = "RegisterNumber", targetNamespace = "http://www.epsilon.com/webservices/")
        String registerNumber,
        @WebParam(name = "TransactionNumber", targetNamespace = "http://www.epsilon.com/webservices/")
        String transactionNumber,
        @WebParam(name = "AssociateID", targetNamespace = "http://www.epsilon.com/webservices/")
        String associateID,
        @WebParam(name = "Date", targetNamespace = "http://www.epsilon.com/webservices/")
        String date,
        @WebParam(name = "Time", targetNamespace = "http://www.epsilon.com/webservices/")
        String time,
        @WebParam(name = "AliasName", targetNamespace = "http://www.epsilon.com/webservices/")
        String aliasName,
        @WebParam(name = "MessageVersion", targetNamespace = "http://www.epsilon.com/webservices/")
        String messageVersion);

    /**
     * 
     * @param wirelessPermissionFlag
     * @param affinities
     * @param memberNumber
     * @param messageVersion
     * @param state
     * @param languagePreference
     * @param address1
     * @param address2
     * @param charity
     * @param tnCStatus
     * @param clubDNPStatus
     * @param zipCodeExtension
     * @param dateUpdated
     * @param city
     * @param terminal
     * @param accountStatus
     * @param zipCode
     * @param firstName
     * @param clubEmailOptStatus
     * @param lastName
     * @param clubMembershipUpdatedBy
     * @param profileUpdate
     * @param countryCode
     * @param emailAddress
     * @param posPrompt
     * @param phoneNumbers
     * @param suffix
     * @param currentTime
     * @param additionalAttributes
     * @param storeNumber
     * @param shcAssociateInd
     * @param currentDate
     * @param prefix
     * @param dob
     * @param middleInitial
     * @param attributes
     * @param testAccount
     * @param tnCVersion
     * @param requestorID
     * @return
     *     returns com.searshc.hs.som.thm.domain.sywr.UpdateMemberPrimaryProfileResponse.UpdateMemberPrimaryProfileResult
     */
    @WebMethod(operationName = "UpdateMemberPrimaryProfile", action = "http://www.epsilon.com/webservices/UpdateMemberPrimaryProfile")
    @WebResult(name = "UpdateMemberPrimaryProfileResult", targetNamespace = "http://www.epsilon.com/webservices/")
    @RequestWrapper(localName = "UpdateMemberPrimaryProfile", targetNamespace = "http://www.epsilon.com/webservices/", className = "com.searshc.hs.som.thm.domain.sywr.UpdateMemberPrimaryProfile")
    @ResponseWrapper(localName = "UpdateMemberPrimaryProfileResponse", targetNamespace = "http://www.epsilon.com/webservices/", className = "com.searshc.hs.som.thm.domain.sywr.UpdateMemberPrimaryProfileResponse")
    public com.searshc.hs.som.thm.domain.sywr.UpdateMemberPrimaryProfileResponse.UpdateMemberPrimaryProfileResult updateMemberPrimaryProfile(
        @WebParam(name = "MessageVersion", targetNamespace = "http://www.epsilon.com/webservices/")
        String messageVersion,
        @WebParam(name = "MemberNumber", targetNamespace = "http://www.epsilon.com/webservices/")
        String memberNumber,
        @WebParam(name = "RequestorID", targetNamespace = "http://www.epsilon.com/webservices/")
        String requestorID,
        @WebParam(name = "StoreNumber", targetNamespace = "http://www.epsilon.com/webservices/")
        String storeNumber,
        @WebParam(name = "Terminal", targetNamespace = "http://www.epsilon.com/webservices/")
        String terminal,
        @WebParam(name = "CurrentDate", targetNamespace = "http://www.epsilon.com/webservices/")
        String currentDate,
        @WebParam(name = "CurrentTime", targetNamespace = "http://www.epsilon.com/webservices/")
        String currentTime,
        @WebParam(name = "Prefix", targetNamespace = "http://www.epsilon.com/webservices/")
        String prefix,
        @WebParam(name = "FirstName", targetNamespace = "http://www.epsilon.com/webservices/")
        String firstName,
        @WebParam(name = "LastName", targetNamespace = "http://www.epsilon.com/webservices/")
        String lastName,
        @WebParam(name = "MiddleInitial", targetNamespace = "http://www.epsilon.com/webservices/")
        String middleInitial,
        @WebParam(name = "Suffix", targetNamespace = "http://www.epsilon.com/webservices/")
        String suffix,
        @WebParam(name = "ClubDNPStatus", targetNamespace = "http://www.epsilon.com/webservices/")
        String clubDNPStatus,
        @WebParam(name = "ClubMembershipUpdatedBy", targetNamespace = "http://www.epsilon.com/webservices/")
        String clubMembershipUpdatedBy,
        @WebParam(name = "DateUpdated", targetNamespace = "http://www.epsilon.com/webservices/")
        String dateUpdated,
        @WebParam(name = "DOB", targetNamespace = "http://www.epsilon.com/webservices/")
        String dob,
        @WebParam(name = "TestAccount", targetNamespace = "http://www.epsilon.com/webservices/")
        String testAccount,
        @WebParam(name = "AccountStatus", targetNamespace = "http://www.epsilon.com/webservices/")
        String accountStatus,
        @WebParam(name = "SHCAssociateInd", targetNamespace = "http://www.epsilon.com/webservices/")
        String shcAssociateInd,
        @WebParam(name = "WirelessPermissionFlag", targetNamespace = "http://www.epsilon.com/webservices/")
        String wirelessPermissionFlag,
        @WebParam(name = "LanguagePreference", targetNamespace = "http://www.epsilon.com/webservices/")
        String languagePreference,
        @WebParam(name = "Address1", targetNamespace = "http://www.epsilon.com/webservices/")
        String address1,
        @WebParam(name = "Address2", targetNamespace = "http://www.epsilon.com/webservices/")
        String address2,
        @WebParam(name = "City", targetNamespace = "http://www.epsilon.com/webservices/")
        String city,
        @WebParam(name = "State", targetNamespace = "http://www.epsilon.com/webservices/")
        String state,
        @WebParam(name = "ZipCode", targetNamespace = "http://www.epsilon.com/webservices/")
        String zipCode,
        @WebParam(name = "ZipCodeExtension", targetNamespace = "http://www.epsilon.com/webservices/")
        String zipCodeExtension,
        @WebParam(name = "CountryCode", targetNamespace = "http://www.epsilon.com/webservices/")
        String countryCode,
        @WebParam(name = "EmailAddress", targetNamespace = "http://www.epsilon.com/webservices/")
        String emailAddress,
        @WebParam(name = "ClubEmailOptStatus", targetNamespace = "http://www.epsilon.com/webservices/")
        String clubEmailOptStatus,
        @WebParam(name = "TnCStatus", targetNamespace = "http://www.epsilon.com/webservices/")
        String tnCStatus,
        @WebParam(name = "TnCVersion", targetNamespace = "http://www.epsilon.com/webservices/")
        String tnCVersion,
        @WebParam(name = "Charity", targetNamespace = "http://www.epsilon.com/webservices/")
        String charity,
        @WebParam(name = "ProfileUpdate", targetNamespace = "http://www.epsilon.com/webservices/")
        String profileUpdate,
        @WebParam(name = "POSPrompt", targetNamespace = "http://www.epsilon.com/webservices/")
        ArrayOfPOSPrompt posPrompt,
        @WebParam(name = "AdditionalAttributes", targetNamespace = "http://www.epsilon.com/webservices/")
        AdditionalAttributes additionalAttributes,
        @WebParam(name = "PhoneNumbers", targetNamespace = "http://www.epsilon.com/webservices/")
        ArrayOfPhone phoneNumbers,
        @WebParam(name = "Affinities", targetNamespace = "http://www.epsilon.com/webservices/")
        ArrayOfAffinity affinities,
        @WebParam(name = "Attributes", targetNamespace = "http://www.epsilon.com/webservices/")
        ArrayOfAttr attributes);

    /**
     * 
     * @param currentTime
     * @param associateId
     * @param storeNumber
     * @param terminal
     * @param memberNumber
     * @param currentDate
     * @param messageVersion
     * @param requestorID
     * @return
     *     returns com.searshc.hs.som.thm.domain.sywr.GetMemberAffinitySubscriptionsResponse.GetMemberAffinitySubscriptionsResult
     */
    @WebMethod(operationName = "GetMemberAffinitySubscriptions", action = "http://www.epsilon.com/webservices/GetMemberAffinitySubscriptions")
    @WebResult(name = "GetMemberAffinitySubscriptionsResult", targetNamespace = "http://www.epsilon.com/webservices/")
    @RequestWrapper(localName = "GetMemberAffinitySubscriptions", targetNamespace = "http://www.epsilon.com/webservices/", className = "com.searshc.hs.som.thm.domain.sywr.GetMemberAffinitySubscriptions")
    @ResponseWrapper(localName = "GetMemberAffinitySubscriptionsResponse", targetNamespace = "http://www.epsilon.com/webservices/", className = "com.searshc.hs.som.thm.domain.sywr.GetMemberAffinitySubscriptionsResponse")
    public com.searshc.hs.som.thm.domain.sywr.GetMemberAffinitySubscriptionsResponse.GetMemberAffinitySubscriptionsResult getMemberAffinitySubscriptions(
        @WebParam(name = "MemberNumber", targetNamespace = "http://www.epsilon.com/webservices/")
        String memberNumber,
        @WebParam(name = "MessageVersion", targetNamespace = "http://www.epsilon.com/webservices/")
        String messageVersion,
        @WebParam(name = "RequestorID", targetNamespace = "http://www.epsilon.com/webservices/")
        String requestorID,
        @WebParam(name = "StoreNumber", targetNamespace = "http://www.epsilon.com/webservices/")
        String storeNumber,
        @WebParam(name = "Terminal", targetNamespace = "http://www.epsilon.com/webservices/")
        String terminal,
        @WebParam(name = "AssociateId", targetNamespace = "http://www.epsilon.com/webservices/")
        String associateId,
        @WebParam(name = "CurrentDate", targetNamespace = "http://www.epsilon.com/webservices/")
        String currentDate,
        @WebParam(name = "CurrentTime", targetNamespace = "http://www.epsilon.com/webservices/")
        String currentTime);

    /**
     * 
     * @param newMemberNumber
     * @param messageVersion
     * @param originalMemberNumber
     * @return
     *     returns com.searshc.hs.som.thm.domain.sywr.MemberReplaceCardResponse.MemberReplaceCardResult
     */
    @WebMethod(operationName = "MemberReplaceCard", action = "http://www.epsilon.com/webservices/MemberReplaceCard")
    @WebResult(name = "MemberReplaceCardResult", targetNamespace = "http://www.epsilon.com/webservices/")
    @RequestWrapper(localName = "MemberReplaceCard", targetNamespace = "http://www.epsilon.com/webservices/", className = "com.searshc.hs.som.thm.domain.sywr.MemberReplaceCard")
    @ResponseWrapper(localName = "MemberReplaceCardResponse", targetNamespace = "http://www.epsilon.com/webservices/", className = "com.searshc.hs.som.thm.domain.sywr.MemberReplaceCardResponse")
    public com.searshc.hs.som.thm.domain.sywr.MemberReplaceCardResponse.MemberReplaceCardResult memberReplaceCard(
        @WebParam(name = "OriginalMemberNumber", targetNamespace = "http://www.epsilon.com/webservices/")
        String originalMemberNumber,
        @WebParam(name = "NewMemberNumber", targetNamespace = "http://www.epsilon.com/webservices/")
        String newMemberNumber,
        @WebParam(name = "MessageVersion", targetNamespace = "http://www.epsilon.com/webservices/")
        String messageVersion);

    /**
     * 
     * @param clubEmailOptStatus
     * @param currentTime
     * @param clubMembershipUpdatedBy
     * @param memberNumber
     * @param currentDate
     * @param messageVersion
     * @param emailAddress
     * @param requestorID
     * @return
     *     returns com.searshc.hs.som.thm.domain.sywr.UpdateMemberEmailResponse.UpdateMemberEmailResult
     */
    @WebMethod(operationName = "UpdateMemberEmail", action = "http://www.epsilon.com/webservices/UpdateMemberEmail")
    @WebResult(name = "UpdateMemberEmailResult", targetNamespace = "http://www.epsilon.com/webservices/")
    @RequestWrapper(localName = "UpdateMemberEmail", targetNamespace = "http://www.epsilon.com/webservices/", className = "com.searshc.hs.som.thm.domain.sywr.UpdateMemberEmail")
    @ResponseWrapper(localName = "UpdateMemberEmailResponse", targetNamespace = "http://www.epsilon.com/webservices/", className = "com.searshc.hs.som.thm.domain.sywr.UpdateMemberEmailResponse")
    public com.searshc.hs.som.thm.domain.sywr.UpdateMemberEmailResponse.UpdateMemberEmailResult updateMemberEmail(
        @WebParam(name = "MessageVersion", targetNamespace = "http://www.epsilon.com/webservices/")
        String messageVersion,
        @WebParam(name = "MemberNumber", targetNamespace = "http://www.epsilon.com/webservices/")
        String memberNumber,
        @WebParam(name = "RequestorID", targetNamespace = "http://www.epsilon.com/webservices/")
        String requestorID,
        @WebParam(name = "CurrentDate", targetNamespace = "http://www.epsilon.com/webservices/")
        String currentDate,
        @WebParam(name = "CurrentTime", targetNamespace = "http://www.epsilon.com/webservices/")
        String currentTime,
        @WebParam(name = "EmailAddress", targetNamespace = "http://www.epsilon.com/webservices/")
        String emailAddress,
        @WebParam(name = "ClubEmailOptStatus", targetNamespace = "http://www.epsilon.com/webservices/")
        String clubEmailOptStatus,
        @WebParam(name = "ClubMembershipUpdatedBy", targetNamespace = "http://www.epsilon.com/webservices/")
        String clubMembershipUpdatedBy);

    /**
     * 
     * @param lastName
     * @param memberNumber
     * @param messageVersion
     * @param firstName
     * @return
     *     returns com.searshc.hs.som.thm.domain.sywr.ValidateMemberResponse.ValidateMemberResult
     */
    @WebMethod(operationName = "ValidateMember", action = "http://www.epsilon.com/webservices/ValidateMember")
    @WebResult(name = "ValidateMemberResult", targetNamespace = "http://www.epsilon.com/webservices/")
    @RequestWrapper(localName = "ValidateMember", targetNamespace = "http://www.epsilon.com/webservices/", className = "com.searshc.hs.som.thm.domain.sywr.ValidateMember")
    @ResponseWrapper(localName = "ValidateMemberResponse", targetNamespace = "http://www.epsilon.com/webservices/", className = "com.searshc.hs.som.thm.domain.sywr.ValidateMemberResponse")
    public com.searshc.hs.som.thm.domain.sywr.ValidateMemberResponse.ValidateMemberResult validateMember(
        @WebParam(name = "MemberNumber", targetNamespace = "http://www.epsilon.com/webservices/")
        String memberNumber,
        @WebParam(name = "FirstName", targetNamespace = "http://www.epsilon.com/webservices/")
        String firstName,
        @WebParam(name = "LastName", targetNamespace = "http://www.epsilon.com/webservices/")
        String lastName,
        @WebParam(name = "MessageVersion", targetNamespace = "http://www.epsilon.com/webservices/")
        String messageVersion);

    /**
     * 
     * @param currentTime
     * @param shcAssociateInd
     * @param memberNumber
     * @param currentDate
     * @param messageVersion
     * @param zipCode
     * @param emailAddress
     * @param zipCodeExtension
     * @return
     *     returns com.searshc.hs.som.thm.domain.sywr.RegisterMemberResponse.RegisterMemberResult
     */
    @WebMethod(operationName = "RegisterMember", action = "http://www.epsilon.com/webservices/RegisterMember")
    @WebResult(name = "RegisterMemberResult", targetNamespace = "http://www.epsilon.com/webservices/")
    @RequestWrapper(localName = "RegisterMember", targetNamespace = "http://www.epsilon.com/webservices/", className = "com.searshc.hs.som.thm.domain.sywr.RegisterMember")
    @ResponseWrapper(localName = "RegisterMemberResponse", targetNamespace = "http://www.epsilon.com/webservices/", className = "com.searshc.hs.som.thm.domain.sywr.RegisterMemberResponse")
    public com.searshc.hs.som.thm.domain.sywr.RegisterMemberResponse.RegisterMemberResult registerMember(
        @WebParam(name = "MemberNumber", targetNamespace = "http://www.epsilon.com/webservices/")
        String memberNumber,
        @WebParam(name = "EmailAddress", targetNamespace = "http://www.epsilon.com/webservices/")
        String emailAddress,
        @WebParam(name = "ZipCode", targetNamespace = "http://www.epsilon.com/webservices/")
        String zipCode,
        @WebParam(name = "ZipCodeExtension", targetNamespace = "http://www.epsilon.com/webservices/")
        String zipCodeExtension,
        @WebParam(name = "SHCAssociateInd", targetNamespace = "http://www.epsilon.com/webservices/")
        String shcAssociateInd,
        @WebParam(name = "MessageVersion", targetNamespace = "http://www.epsilon.com/webservices/")
        String messageVersion,
        @WebParam(name = "CurrentDate", targetNamespace = "http://www.epsilon.com/webservices/")
        String currentDate,
        @WebParam(name = "CurrentTime", targetNamespace = "http://www.epsilon.com/webservices/")
        String currentTime);

    /**
     * 
     * @param memberNumber
     * @param messageVersion
     * @return
     *     returns com.searshc.hs.som.thm.domain.sywr.GetMemberExtendedProfileResponse.GetMemberExtendedProfileResult
     */
    @WebMethod(operationName = "GetMemberExtendedProfile", action = "http://www.epsilon.com/webservices/GetMemberExtendedProfile")
    @WebResult(name = "GetMemberExtendedProfileResult", targetNamespace = "http://www.epsilon.com/webservices/")
    @RequestWrapper(localName = "GetMemberExtendedProfile", targetNamespace = "http://www.epsilon.com/webservices/", className = "com.searshc.hs.som.thm.domain.sywr.GetMemberExtendedProfile")
    @ResponseWrapper(localName = "GetMemberExtendedProfileResponse", targetNamespace = "http://www.epsilon.com/webservices/", className = "com.searshc.hs.som.thm.domain.sywr.GetMemberExtendedProfileResponse")
    public com.searshc.hs.som.thm.domain.sywr.GetMemberExtendedProfileResponse.GetMemberExtendedProfileResult getMemberExtendedProfile(
        @WebParam(name = "MemberNumber", targetNamespace = "http://www.epsilon.com/webservices/")
        String memberNumber,
        @WebParam(name = "MessageVersion", targetNamespace = "http://www.epsilon.com/webservices/")
        String messageVersion);

    /**
     * 
     * @param memberNumber
     * @param messageVersion
     * @return
     *     returns com.searshc.hs.som.thm.domain.sywr.GetMemberPrimaryProfileResponse.GetMemberPrimaryProfileResult
     */
    @WebMethod(operationName = "GetMemberPrimaryProfile", action = "http://www.epsilon.com/webservices/GetMemberPrimaryProfile")
    @WebResult(name = "GetMemberPrimaryProfileResult", targetNamespace = "http://www.epsilon.com/webservices/")
    @RequestWrapper(localName = "GetMemberPrimaryProfile", targetNamespace = "http://www.epsilon.com/webservices/", className = "com.searshc.hs.som.thm.domain.sywr.GetMemberPrimaryProfile")
    @ResponseWrapper(localName = "GetMemberPrimaryProfileResponse", targetNamespace = "http://www.epsilon.com/webservices/", className = "com.searshc.hs.som.thm.domain.sywr.GetMemberPrimaryProfileResponse")
    public com.searshc.hs.som.thm.domain.sywr.GetMemberPrimaryProfileResponse.GetMemberPrimaryProfileResult getMemberPrimaryProfile(
        @WebParam(name = "MemberNumber", targetNamespace = "http://www.epsilon.com/webservices/")
        String memberNumber,
        @WebParam(name = "MessageVersion", targetNamespace = "http://www.epsilon.com/webservices/")
        String messageVersion);

}
