//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.05.20 at 11:01:46 AM CDT 
//


package com.searshc.hs.domi.service.merchandise.lookup.details.response;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;

import com.searshc.hs.base.ABase;


/**
 * <p>Java class for maintAgreement complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="maintAgreement">
 *   &lt;complexContent>
 *     &lt;extension base="{}aBase">
 *       &lt;sequence>
 *         &lt;element name="actualAmt" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="agreementSuffix" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="apEmployee" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="apPurchaseAmt" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="apTaxAmt" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="cancelDate" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="cancelRefundAmt" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="cancelTaxAmt" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="coverageMonth" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="currExpDate" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="currStartDate" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="deductibleAmt" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="payment" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="protectPlanName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="protectionPlan" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="purchaseAmt" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="purchaseDate" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="refundCoverageCredit" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="refundCoverageCreditTax" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="responseTime" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="saleUnit" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="serviceLoc" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="serviceProdNum" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="serviceProductType" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="taxAmt" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "maintAgreement", propOrder = {
    "actualAmt",
    "agreementSuffix",
    "apEmployee",
    "apPurchaseAmt",
    "apTaxAmt",
    "cancelDate",
    "cancelRefundAmt",
    "cancelTaxAmt",
    "coverageMonth",
    "currExpDate",
    "currStartDate",
    "deductibleAmt",
    "payment",
    "protectPlanName",
    "protectionPlan",
    "purchaseAmt",
    "purchaseDate",
    "refundCoverageCredit",
    "refundCoverageCreditTax",
    "responseTime",
    "saleUnit",
    "serviceLoc",
    "serviceProdNum",
    "serviceProductType",
    "taxAmt"
})
public class MaintAgreement
    extends ABase
{

    protected String actualAmt;
    protected String agreementSuffix;
    protected String apEmployee;
    protected String apPurchaseAmt;
    protected String apTaxAmt;
    protected String cancelDate;
    protected String cancelRefundAmt;
    protected String cancelTaxAmt;
    protected String coverageMonth;
    protected String currExpDate;
    protected String currStartDate;
    protected String deductibleAmt;
    protected String payment;
    protected String protectPlanName;
    protected String protectionPlan;
    protected String purchaseAmt;
    protected String purchaseDate;
    protected String refundCoverageCredit;
    protected String refundCoverageCreditTax;
    protected String responseTime;
    protected String saleUnit;
    protected String serviceLoc;
    protected String serviceProdNum;
    protected String serviceProductType;
    protected String taxAmt;

    /**
     * Gets the value of the actualAmt property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getActualAmt() {
        return actualAmt;
    }

    /**
     * Sets the value of the actualAmt property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setActualAmt(String value) {
        this.actualAmt = value;
    }

    /**
     * Gets the value of the agreementSuffix property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAgreementSuffix() {
        return agreementSuffix;
    }

    /**
     * Sets the value of the agreementSuffix property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAgreementSuffix(String value) {
        this.agreementSuffix = value;
    }

    /**
     * Gets the value of the apEmployee property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getApEmployee() {
        return apEmployee;
    }

    /**
     * Sets the value of the apEmployee property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setApEmployee(String value) {
        this.apEmployee = value;
    }

    /**
     * Gets the value of the apPurchaseAmt property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getApPurchaseAmt() {
        return apPurchaseAmt;
    }

    /**
     * Sets the value of the apPurchaseAmt property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setApPurchaseAmt(String value) {
        this.apPurchaseAmt = value;
    }

    /**
     * Gets the value of the apTaxAmt property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getApTaxAmt() {
        return apTaxAmt;
    }

    /**
     * Sets the value of the apTaxAmt property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setApTaxAmt(String value) {
        this.apTaxAmt = value;
    }

    /**
     * Gets the value of the cancelDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCancelDate() {
        return cancelDate;
    }

    /**
     * Sets the value of the cancelDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCancelDate(String value) {
        this.cancelDate = value;
    }

    /**
     * Gets the value of the cancelRefundAmt property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCancelRefundAmt() {
        return cancelRefundAmt;
    }

    /**
     * Sets the value of the cancelRefundAmt property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCancelRefundAmt(String value) {
        this.cancelRefundAmt = value;
    }

    /**
     * Gets the value of the cancelTaxAmt property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCancelTaxAmt() {
        return cancelTaxAmt;
    }

    /**
     * Sets the value of the cancelTaxAmt property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCancelTaxAmt(String value) {
        this.cancelTaxAmt = value;
    }

    /**
     * Gets the value of the coverageMonth property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCoverageMonth() {
        return coverageMonth;
    }

    /**
     * Sets the value of the coverageMonth property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCoverageMonth(String value) {
        this.coverageMonth = value;
    }

    /**
     * Gets the value of the currExpDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCurrExpDate() {
        return currExpDate;
    }

    /**
     * Sets the value of the currExpDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCurrExpDate(String value) {
        this.currExpDate = value;
    }

    /**
     * Gets the value of the currStartDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCurrStartDate() {
        return currStartDate;
    }

    /**
     * Sets the value of the currStartDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCurrStartDate(String value) {
        this.currStartDate = value;
    }

    /**
     * Gets the value of the deductibleAmt property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDeductibleAmt() {
        return deductibleAmt;
    }

    /**
     * Sets the value of the deductibleAmt property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDeductibleAmt(String value) {
        this.deductibleAmt = value;
    }

    /**
     * Gets the value of the payment property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPayment() {
        return payment;
    }

    /**
     * Sets the value of the payment property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPayment(String value) {
        this.payment = value;
    }

    /**
     * Gets the value of the protectPlanName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getProtectPlanName() {
        return protectPlanName;
    }

    /**
     * Sets the value of the protectPlanName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProtectPlanName(String value) {
        this.protectPlanName = value;
    }

    /**
     * Gets the value of the protectionPlan property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getProtectionPlan() {
        return protectionPlan;
    }

    /**
     * Sets the value of the protectionPlan property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProtectionPlan(String value) {
        this.protectionPlan = value;
    }

    /**
     * Gets the value of the purchaseAmt property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPurchaseAmt() {
        return purchaseAmt;
    }

    /**
     * Sets the value of the purchaseAmt property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPurchaseAmt(String value) {
        this.purchaseAmt = value;
    }

    /**
     * Gets the value of the purchaseDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPurchaseDate() {
        return purchaseDate;
    }

    /**
     * Sets the value of the purchaseDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPurchaseDate(String value) {
        this.purchaseDate = value;
    }

    /**
     * Gets the value of the refundCoverageCredit property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRefundCoverageCredit() {
        return refundCoverageCredit;
    }

    /**
     * Sets the value of the refundCoverageCredit property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRefundCoverageCredit(String value) {
        this.refundCoverageCredit = value;
    }

    /**
     * Gets the value of the refundCoverageCreditTax property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRefundCoverageCreditTax() {
        return refundCoverageCreditTax;
    }

    /**
     * Sets the value of the refundCoverageCreditTax property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRefundCoverageCreditTax(String value) {
        this.refundCoverageCreditTax = value;
    }

    /**
     * Gets the value of the responseTime property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getResponseTime() {
        return responseTime;
    }

    /**
     * Sets the value of the responseTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setResponseTime(String value) {
        this.responseTime = value;
    }

    /**
     * Gets the value of the saleUnit property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSaleUnit() {
        return saleUnit;
    }

    /**
     * Sets the value of the saleUnit property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSaleUnit(String value) {
        this.saleUnit = value;
    }

    /**
     * Gets the value of the serviceLoc property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getServiceLoc() {
        return serviceLoc;
    }

    /**
     * Sets the value of the serviceLoc property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setServiceLoc(String value) {
        this.serviceLoc = value;
    }

    /**
     * Gets the value of the serviceProdNum property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getServiceProdNum() {
        return serviceProdNum;
    }

    /**
     * Sets the value of the serviceProdNum property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setServiceProdNum(String value) {
        this.serviceProdNum = value;
    }

    /**
     * Gets the value of the serviceProductType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getServiceProductType() {
        return serviceProductType;
    }

    /**
     * Sets the value of the serviceProductType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setServiceProductType(String value) {
        this.serviceProductType = value;
    }

    /**
     * Gets the value of the taxAmt property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTaxAmt() {
        return taxAmt;
    }

    /**
     * Sets the value of the taxAmt property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTaxAmt(String value) {
        this.taxAmt = value;
    }

}
