//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.05.20 at 11:01:46 AM CDT 
//


package com.searshc.hs.domi.service.merchandise.lookup.details.response;

import java.util.ArrayList;
import java.util.List;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;

import com.searshc.hs.domi.service.merchandise.lookup.common.response.Merchandise;


/**
 * <p>Java class for merchandiseDetails complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="merchandiseDetails">
 *   &lt;complexContent>
 *     &lt;extension base="{}merchandise">
 *       &lt;sequence>
 *         &lt;element name="agreements" type="{}maintAgreement" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="componentFlag" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="deliveryDate" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="lwDMY" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="lwExpiration" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="lwNum" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="notPromoteMAReason" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="notPromoteOtherReason" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="numOfAgreements" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="oriCd" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="pitchDate" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="promoteOtherFlag" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="pwDMY" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="pwExpiration" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="pwNum" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="receiveDate" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="searsPurchaseFlag" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="spPgmMkey" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="sppPgmMkey" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="statusFlag" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="stockNum" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="storeNo" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="usageType" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="xpDMY" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="xpExpiration" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="xpNum" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="xrefCustomer" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "merchandiseDetails", propOrder = {
    "agreements",
    "componentFlag",
    "deliveryDate",
    "lwDMY",
    "lwExpiration",
    "lwNum",
    "notPromoteMAReason",
    "notPromoteOtherReason",
    "numOfAgreements",
    "oriCd",
    "pitchDate",
    "promoteOtherFlag",
    "pwDMY",
    "pwExpiration",
    "pwNum",
    "receiveDate",
    "searsPurchaseFlag",
    "spPgmMkey",
    "sppPgmMkey",
    "statusFlag",
    "stockNum",
    "storeNo",
    "usageType",
    "xpDMY",
    "xpExpiration",
    "xpNum",
    "xrefCustomer"
})
public class MerchandiseDetails
    extends Merchandise
{

    @XmlElement(nillable = true)
    protected List<MaintAgreement> agreements;
    protected String componentFlag;
    protected String deliveryDate;
    protected String lwDMY;
    protected String lwExpiration;
    protected String lwNum;
    protected String notPromoteMAReason;
    protected String notPromoteOtherReason;
    protected int numOfAgreements;
    protected String oriCd;
    protected String pitchDate;
    protected String promoteOtherFlag;
    protected String pwDMY;
    protected String pwExpiration;
    protected String pwNum;
    protected String receiveDate;
    protected String searsPurchaseFlag;
    protected String spPgmMkey;
    protected String sppPgmMkey;
    protected String statusFlag;
    protected String stockNum;
    protected String storeNo;
    protected String usageType;
    protected String xpDMY;
    protected String xpExpiration;
    protected String xpNum;
    protected String xrefCustomer;

    /**
     * Gets the value of the agreements property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the agreements property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAgreements().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link MaintAgreement }
     * 
     * 
     */
    public List<MaintAgreement> getAgreements() {
        if (agreements == null) {
            agreements = new ArrayList<MaintAgreement>();
        }
        return this.agreements;
    }

    /**
     * Gets the value of the componentFlag property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getComponentFlag() {
        return componentFlag;
    }

    /**
     * Sets the value of the componentFlag property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setComponentFlag(String value) {
        this.componentFlag = value;
    }

    /**
     * Gets the value of the deliveryDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDeliveryDate() {
        return deliveryDate;
    }

    /**
     * Sets the value of the deliveryDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDeliveryDate(String value) {
        this.deliveryDate = value;
    }

    /**
     * Gets the value of the lwDMY property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLwDMY() {
        return lwDMY;
    }

    /**
     * Sets the value of the lwDMY property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLwDMY(String value) {
        this.lwDMY = value;
    }

    /**
     * Gets the value of the lwExpiration property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLwExpiration() {
        return lwExpiration;
    }

    /**
     * Sets the value of the lwExpiration property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLwExpiration(String value) {
        this.lwExpiration = value;
    }

    /**
     * Gets the value of the lwNum property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLwNum() {
        return lwNum;
    }

    /**
     * Sets the value of the lwNum property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLwNum(String value) {
        this.lwNum = value;
    }

    /**
     * Gets the value of the notPromoteMAReason property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNotPromoteMAReason() {
        return notPromoteMAReason;
    }

    /**
     * Sets the value of the notPromoteMAReason property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNotPromoteMAReason(String value) {
        this.notPromoteMAReason = value;
    }

    /**
     * Gets the value of the notPromoteOtherReason property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNotPromoteOtherReason() {
        return notPromoteOtherReason;
    }

    /**
     * Sets the value of the notPromoteOtherReason property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNotPromoteOtherReason(String value) {
        this.notPromoteOtherReason = value;
    }

    /**
     * Gets the value of the numOfAgreements property.
     * 
     */
    public int getNumOfAgreements() {
        return numOfAgreements;
    }

    /**
     * Sets the value of the numOfAgreements property.
     * 
     */
    public void setNumOfAgreements(int value) {
        this.numOfAgreements = value;
    }

    /**
     * Gets the value of the oriCd property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOriCd() {
        return oriCd;
    }

    /**
     * Sets the value of the oriCd property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOriCd(String value) {
        this.oriCd = value;
    }

    /**
     * Gets the value of the pitchDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPitchDate() {
        return pitchDate;
    }

    /**
     * Sets the value of the pitchDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPitchDate(String value) {
        this.pitchDate = value;
    }

    /**
     * Gets the value of the promoteOtherFlag property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPromoteOtherFlag() {
        return promoteOtherFlag;
    }

    /**
     * Sets the value of the promoteOtherFlag property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPromoteOtherFlag(String value) {
        this.promoteOtherFlag = value;
    }

    /**
     * Gets the value of the pwDMY property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPwDMY() {
        return pwDMY;
    }

    /**
     * Sets the value of the pwDMY property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPwDMY(String value) {
        this.pwDMY = value;
    }

    /**
     * Gets the value of the pwExpiration property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPwExpiration() {
        return pwExpiration;
    }

    /**
     * Sets the value of the pwExpiration property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPwExpiration(String value) {
        this.pwExpiration = value;
    }

    /**
     * Gets the value of the pwNum property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPwNum() {
        return pwNum;
    }

    /**
     * Sets the value of the pwNum property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPwNum(String value) {
        this.pwNum = value;
    }

    /**
     * Gets the value of the receiveDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getReceiveDate() {
        return receiveDate;
    }

    /**
     * Sets the value of the receiveDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setReceiveDate(String value) {
        this.receiveDate = value;
    }

    /**
     * Gets the value of the searsPurchaseFlag property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSearsPurchaseFlag() {
        return searsPurchaseFlag;
    }

    /**
     * Sets the value of the searsPurchaseFlag property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSearsPurchaseFlag(String value) {
        this.searsPurchaseFlag = value;
    }

    /**
     * Gets the value of the spPgmMkey property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSpPgmMkey() {
        return spPgmMkey;
    }

    /**
     * Sets the value of the spPgmMkey property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSpPgmMkey(String value) {
        this.spPgmMkey = value;
    }

    /**
     * Gets the value of the sppPgmMkey property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSppPgmMkey() {
        return sppPgmMkey;
    }

    /**
     * Sets the value of the sppPgmMkey property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSppPgmMkey(String value) {
        this.sppPgmMkey = value;
    }

    /**
     * Gets the value of the statusFlag property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStatusFlag() {
        return statusFlag;
    }

    /**
     * Sets the value of the statusFlag property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStatusFlag(String value) {
        this.statusFlag = value;
    }

    /**
     * Gets the value of the stockNum property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStockNum() {
        return stockNum;
    }

    /**
     * Sets the value of the stockNum property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStockNum(String value) {
        this.stockNum = value;
    }

    /**
     * Gets the value of the storeNo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStoreNo() {
        return storeNo;
    }

    /**
     * Sets the value of the storeNo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStoreNo(String value) {
        this.storeNo = value;
    }

    /**
     * Gets the value of the usageType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUsageType() {
        return usageType;
    }

    /**
     * Sets the value of the usageType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUsageType(String value) {
        this.usageType = value;
    }

    /**
     * Gets the value of the xpDMY property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getXpDMY() {
        return xpDMY;
    }

    /**
     * Sets the value of the xpDMY property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setXpDMY(String value) {
        this.xpDMY = value;
    }

    /**
     * Gets the value of the xpExpiration property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getXpExpiration() {
        return xpExpiration;
    }

    /**
     * Sets the value of the xpExpiration property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setXpExpiration(String value) {
        this.xpExpiration = value;
    }

    /**
     * Gets the value of the xpNum property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getXpNum() {
        return xpNum;
    }

    /**
     * Sets the value of the xpNum property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setXpNum(String value) {
        this.xpNum = value;
    }

    /**
     * Gets the value of the xrefCustomer property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getXrefCustomer() {
        return xrefCustomer;
    }

    /**
     * Sets the value of the xrefCustomer property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setXrefCustomer(String value) {
        this.xrefCustomer = value;
    }

}
