
package com.searshc.hs.agreement.agreementservice.service;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.jws.soap.SOAPBinding.Style;
import javax.jws.soap.SOAPBinding.Use;

import com.searshc.hs.agreement.agreementservice.domain.request.AddRequest;
import com.searshc.hs.agreement.agreementservice.domain.request.AgreementDetailsRequest;
import com.searshc.hs.agreement.agreementservice.domain.request.AgreementListRequest;
import com.searshc.hs.agreement.agreementservice.domain.request.CancelRequest;
import com.searshc.hs.agreement.agreementservice.domain.request.DetailsRequest;
import com.searshc.hs.agreement.agreementservice.domain.request.LeadDetailsRequest;
import com.searshc.hs.agreement.agreementservice.domain.request.ManualLeadRequestVO;
import com.searshc.hs.agreement.agreementservice.domain.request.QueueCancelListRequest;
import com.searshc.hs.agreement.agreementservice.domain.request.QueueCancelRequest;
import com.searshc.hs.agreement.agreementservice.domain.request.ReprintRequest;
import com.searshc.hs.agreement.agreementservice.domain.request.SettlementRequest;
import com.searshc.hs.agreement.agreementservice.domain.request.TechPASalesRequest;
import com.searshc.hs.agreement.agreementservice.domain.response.AddResponse;
import com.searshc.hs.agreement.agreementservice.domain.response.AgreementDetailResponse;
import com.searshc.hs.agreement.agreementservice.domain.response.AgreementResponse;
import com.searshc.hs.agreement.agreementservice.domain.response.CancelResponse;
import com.searshc.hs.agreement.agreementservice.domain.response.ItemDetailsResponse;
import com.searshc.hs.agreement.agreementservice.domain.response.LeadDetailsResponse;
import com.searshc.hs.agreement.agreementservice.domain.response.ManualLeadResponseVO;
import com.searshc.hs.agreement.agreementservice.domain.response.QueueCancelListResponse;
import com.searshc.hs.agreement.agreementservice.domain.response.QueueCancelResponse;
import com.searshc.hs.agreement.agreementservice.domain.response.ReprintResponse;
import com.searshc.hs.agreement.agreementservice.domain.response.SettlementResponse;
import com.searshc.hs.agreement.agreementservice.domain.response.TechPASalesResponse;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebService(name = "AgreementSoapService", targetNamespace = "http://service.agreementservice.agreement.hs.searshc.com")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE,style=Style.DOCUMENT,use=Use.LITERAL)
public interface AgreementSoapService {

    /**
     * 
     * @param req
     * @return
     *     returns com.sears.hs.agreement.domain.response.AgreementDetailsResponse
     */
    @WebMethod(action = "getAgreementDetails")
    @WebResult(name = "agreementDetailsReturn", targetNamespace = "http://response.domain.agreementservice.agreement.hs.searshc.com", partName="agreementDetailsReturn")
    public AgreementDetailResponse getAgreementDetails(@WebParam(name = "agreementDetailsRequest", targetNamespace = "http://request.domain.agreementservice.agreement.hs.searshc.com", partName="agreementDetailsRequest")
    AgreementDetailsRequest agreementDetailsRequest);

    /**
     * 
     * @param request
     * @return
     *     returns com.sears.hs.agreement.domain.response.LeadDetailsResponse
     */
    @WebMethod(action = "getLeadDetails")
    @WebResult(name = "getLeadDetailsReturn", targetNamespace = "http://response.domain.agreementservice.agreement.hs.searshc.com", partName="getLeadDetailsReturn")
    public LeadDetailsResponse getLeadDetails(
        @WebParam(name = "leadDetailsRequest", targetNamespace = "http://request.domain.agreementservice.agreement.hs.searshc.com", partName="leadDetailsRequest")
        LeadDetailsRequest leadDetailsRequest);

    /**
     * 
     * @param req
     * @return
     *     returns com.sears.hs.agreement.domain.response.QueueCancelResponse
     */
    @WebMethod(action = "queueCancel")
    @WebResult(name = "queueCancelReturn", targetNamespace = "http://response.domain.agreementservice.agreement.hs.searshc.com")
    public QueueCancelResponse queueCancel(
        @WebParam(name = "queueCancelRequest", targetNamespace = "http://request.domain.agreementservice.agreement.hs.searshc.com")
        QueueCancelRequest queueCancelRequest);

    /**
     * 
     * @param req
     * @return
     *     returns com.sears.hs.agreement.domain.response.QueueCancelListResponse
     */
    @WebMethod(action = "queueCancelList")
    @WebResult(name = "queueCancelListReturn", targetNamespace = "http://response.domain.agreementservice.agreement.hs.searshc.com")
    public QueueCancelListResponse queueCancelList(
        @WebParam(name = "queueCancelListRequest", targetNamespace = "http://request.domain.agreementservice.agreement.hs.searshc.com")
        QueueCancelListRequest queueCancelRequest);

    /**
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod(action = "ping")
    @WebResult(name = "pingReturn", targetNamespace = "http://response.domain.agreementservice.agreement.hs.searshc.com")
    public String ping();

    /**
     * 
     * @param req
     * @return
     *     returns com.sears.hs.agreement.domain.response.ListResponse
     */
    @WebMethod(action = "getAgreementList")
    @WebResult(name = "listReturn", targetNamespace = "http://response.domain.agreementservice.agreement.hs.searshc.com")
    public AgreementResponse getAgreementList(
            @WebParam(name = "agreementListRequest", targetNamespace = "http://request.domain.agreementservice.agreement.hs.searshc.com")
            AgreementListRequest agreementListRequest);

    /**
     * 
     * @param req
     * @return
     *     returns com.sears.hs.agreement.domain.response.CancelResponse
     */
    @WebMethod(action = "cancelAgreement")
    @WebResult(name = "cancelReturn", targetNamespace = "http://response.domain.agreementservice.agreement.hs.searshc.com")
    public CancelResponse cancelAgreement(
        @WebParam(name = "cancelRequest", targetNamespace = "http://request.domain.agreementservice.agreement.hs.searshc.com")
        CancelRequest cancelRequest);

    /**
     * 
     * @param req
     * @return
     *     returns com.sears.hs.agreement.domain.response.AddResponse
     */
    @WebMethod(action = "addAgreement")
    @WebResult(name = "addReturn", targetNamespace = "http://response.domain.agreementservice.agreement.hs.searshc.com")
    public AddResponse addAgreement(
        @WebParam(name = "addRequest", targetNamespace = "http://request.domain.agreementservice.agreement.hs.searshc.com")
        AddRequest addRequest);

    /**
     * 
     * @param request
     * @return
     *     returns com.sears.hs.agreement.inbound.domain.response.TechPASalesResponse
     */
    @WebMethod(action = "createTechPA")
    @WebResult(name = "createTechPAReturn", targetNamespace = "http://response.domain.agreementservice.agreement.hs.searshc.com")
    public TechPASalesResponse createTechPA(
        @WebParam(name = "techPSSalesRequest", targetNamespace = "http://request.domain.agreementservice.agreement.hs.searshc.com")
        TechPASalesRequest techPSSalesRequest);

    /**
     * 
     * @param req
     * @return
     *     returns com.sears.hs.agreement.domain.response.ReprintResponse
     */
    @WebMethod(action = "reprint")
    @WebResult(name = "reprintReturn", targetNamespace = "http://response.domain.agreementservice.agreement.hs.searshc.com")
    public ReprintResponse reprint(@WebParam(name = "reprintRequest", targetNamespace = "http://request.domain.agreementservice.agreement.hs.searshc.com")
        ReprintRequest reprintRequest);

    /**
     * 
     * @param req
     * @return
     *     returns com.sears.hs.agreement.domain.response.ItemDetailsResponse
     */
    @WebMethod(action = "getItemDetails")
    @WebResult(name = "itemDetailsReturn", targetNamespace = "http://response.domain.agreementservice.agreement.hs.searshc.com")
    public ItemDetailsResponse getItemDetails(@WebParam(name = "detailsRequest", targetNamespace = "http://request.domain.agreementservice.agreement.hs.searshc.com")
        DetailsRequest detailsRequest);

    /**
     * 
     * @param req
     * @return
     *     returns com.sears.hs.agreement.domain.response.SettlementResponse
     */
    @WebMethod(action = "settlement")
    @WebResult(name = "settlementReturn", targetNamespace = "http://response.domain.agreementservice.agreement.hs.searshc.com")
    public SettlementResponse settlement(
        @WebParam(name = "settlmentRequest", targetNamespace = "http://request.domain.agreementservice.agreement.hs.searshc.com")
        SettlementRequest settlmentRequest);

    /**
     * 
     * @param request
     * @return
     *     returns com.sears.hs.agreement.inbound.domain.response.ManualLeadResponseVO
     */
    @WebMethod(action = "addManualLeadPending")
    @WebResult(name = "addManualLeadPendingReturn", targetNamespace = "http://response.domain.agreementservice.agreement.hs.searshc.com")
    public ManualLeadResponseVO addManualLeadPending(@WebParam(name = "manualLeadPendingRequest", targetNamespace = "http://request.domain.agreementservice.agreement.hs.searshc.com")
        ManualLeadRequestVO manualLeadPendingRequest);

    /**
     * 
     * @param req
     * @return
     *     returns com.sears.hs.agreement.inbound.domain.response.ManualLeadResponseVO
     */
    @WebMethod(action = "addManualLead")
    @WebResult(name = "addManualLeadReturn", targetNamespace = "http://response.domain.agreementservice.agreement.hs.searshc.com")
    public ManualLeadResponseVO addManualLead(
        @WebParam(name = "manualLeadRequest", targetNamespace = "http://request.domain.agreementservice.agreement.hs.searshc.com")
        ManualLeadRequestVO req);

}
