package com.searshc.hs.psc.partorderdirectservice.ws.service;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.7.8
 * 2015-07-06T10:16:11.434-05:00
 * Generated source version: 2.7.8
 * 
 */
@WebService(targetNamespace = "http://service.ws.partorderdirectservice.psc.hs.searshc.com", name = "PartOrderDirectSoapService")
@XmlSeeAlso({com.searshc.hs.psc.partorderdirect.vo.request.ObjectFactory.class, ObjectFactory.class, com.searshc.hs.psc.partorderdirect.vo.response.ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface PartOrderDirectSoapService {

    @WebResult(name = "searchPartOrderDetailsResponseVO", targetNamespace = "http://response.vo.partorderdirect.psc.hs.searshc.com", partName = "searchPartOrderDetailsResponseVO")
    @WebMethod
    public SearchPartOrderDetailsResponseVO searchPartOrderDetails(
        @WebParam(partName = "searchPartOrderDetailsRequestVO", name = "searchPartOrderDetailsRequestVO", targetNamespace = "http://request.vo.partorderdirect.psc.hs.searshc.com")
        SearchPartOrderDetailsRequestVO searchPartOrderDetailsRequestVO
    );

    @WebResult(name = "createPartOrderDirectResponseVO", targetNamespace = "http://response.vo.partorderdirect.psc.hs.searshc.com", partName = "createPartOrderDirectResponseVO")
    @WebMethod
    public CreatePartOrderDirectResponseVO createPartOrder(
        @WebParam(partName = "createPartOrderDirectRequestVO", name = "createPartOrderDirectRequestVO", targetNamespace = "http://request.vo.partorderdirect.psc.hs.searshc.com")
        CreatePartOrderDirectRequestVO createPartOrderDirectRequestVO
    );

    @WebResult(name = "searchPartOrderDirectResponseVO", targetNamespace = "http://response.vo.partorderdirect.psc.hs.searshc.com", partName = "searchPartOrderDirectResponseVO")
    @WebMethod
    public SearchPartOrderDirectResponseVO searchPartOrder(
        @WebParam(partName = "searchPartOrderDirectRequestVO", name = "searchPartOrderDirectRequestVO", targetNamespace = "http://request.vo.partorderdirect.psc.hs.searshc.com")
        SearchPartOrderDirectRequestVO searchPartOrderDirectRequestVO
    );

    @WebResult(name = "updatePartOrderDirectResponseVO", targetNamespace = "http://response.vo.partorderdirect.psc.hs.searshc.com", partName = "updatePartOrderDirectResponseVO")
    @WebMethod
    public UpdatePartOrderDirectResponseVO updatePartOrder(
        @WebParam(partName = "updatePartOrderDirectRequestVO", name = "updatePartOrderDirectRequestVO", targetNamespace = "http://request.vo.partorderdirect.psc.hs.searshc.com")
        UpdatePartOrderDirectRequestVO updatePartOrderDirectRequestVO
    );

    @WebResult(name = "getRefundPartOrderDirectResponseVO", targetNamespace = "http://response.vo.partorderdirect.psc.hs.searshc.com", partName = "getRefundPartOrderDirectResponseVO")
    @WebMethod
    public GetRefundPartOrderDirectResponseVO getRefundInfo(
        @WebParam(partName = "getRefundPartOrderDirectRequestVO", name = "getRefundPartOrderDirectRequestVO", targetNamespace = "http://request.vo.partorderdirect.psc.hs.searshc.com")
        com.searshc.hs.psc.partorderdirect.vo.request.GetRefundPartOrderDirectRequestVO getRefundPartOrderDirectRequestVO
    );
}
