package com.searshc.hs.psc.partorderdirectservice.ws.service;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.7.8
 * 2015-07-06T10:16:11.444-05:00
 * Generated source version: 2.7.8
 * 
 */
@WebServiceClient(name = "PartOrderDirectServiceImplService", 
                  wsdlLocation = "http://hfqahspartsvc1.vm.itg.corp.us.shldcorp.com:8280/HSPRTPartOrderDirectService/services/soap/PartOrderDirectService?wsdl",
                  targetNamespace = "http://service.ws.partorderdirectservice.psc.hs.searshc.com") 
public class PartOrderDirectServiceImplService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://service.ws.partorderdirectservice.psc.hs.searshc.com", "PartOrderDirectServiceImplService");
    public final static QName PartOrderDirectServiceImplPort = new QName("http://service.ws.partorderdirectservice.psc.hs.searshc.com", "PartOrderDirectServiceImplPort");
    static {
        URL url = null;
        try {
            url = new URL("http://hfqahspartsvc1.vm.itg.corp.us.shldcorp.com:8280/HSPRTPartOrderDirectService/services/soap/PartOrderDirectService?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(PartOrderDirectServiceImplService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://hfqahspartsvc1.vm.itg.corp.us.shldcorp.com:8280/HSPRTPartOrderDirectService/services/soap/PartOrderDirectService?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public PartOrderDirectServiceImplService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public PartOrderDirectServiceImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public PartOrderDirectServiceImplService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public PartOrderDirectServiceImplService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public PartOrderDirectServiceImplService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public PartOrderDirectServiceImplService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     *
     * @return
     *     returns PartOrderDirectSoapService
     */
    @WebEndpoint(name = "PartOrderDirectServiceImplPort")
    public PartOrderDirectSoapService getPartOrderDirectServiceImplPort() {
        return super.getPort(PartOrderDirectServiceImplPort, PartOrderDirectSoapService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns PartOrderDirectSoapService
     */
    @WebEndpoint(name = "PartOrderDirectServiceImplPort")
    public PartOrderDirectSoapService getPartOrderDirectServiceImplPort(WebServiceFeature... features) {
        return super.getPort(PartOrderDirectServiceImplPort, PartOrderDirectSoapService.class, features);
    }

}
