//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.01.30 at 04:44:08 PM CST 
//


package com.searshc.hs.agreement.contract.service.domain.response;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import com.searshc.hs.agreement.agreementservice.domain.response.ABaseResponse;


@XmlRootElement(name="HwpDetailsResponse")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "hwpDetailsResponse", propOrder = {
    "hwpContractNumber",
    "hwpProductCode"
})
public class HwpDetailsResponse
    extends ABaseResponse
{
	
	@XmlElement(nillable = true)
	protected String hwpContractNumber;
	
    @XmlElement(nillable = true)
    protected String hwpProductCode;

	public String getHwpContractNumber() {
		return hwpContractNumber;
	}

	public void setHwpContractNumber(String hwpContractNumber) {
		this.hwpContractNumber = hwpContractNumber;
	}

	public String getHwpProductCode() {
		return hwpProductCode;
	}

	public void setHwpProductCode(String hwpProductCode) {
		this.hwpProductCode = hwpProductCode;
	}
}
