//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.01.30 at 04:44:08 PM CST 
//


package com.searshc.hs.agreement.agreementservice.domain.response;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;
import com.searshc.hs.agreement.agreementservice.domain.AgreementDetail;


/**
 * <p>Java class for agreementDetailResponse complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="agreementDetailResponse">
 *   &lt;complexContent>
 *     &lt;extension base="{http://response.domain.agreementservice.agreement.hs.searshc.com}ABaseResponse">
 *       &lt;sequence>
 *         &lt;element name="detail" type="{http://domain.agreementservice.agreement.hs.searshc.com}agreementDetail" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "agreementDetailResponse", propOrder = {
    "detail"
})
public class AgreementDetailResponse
    extends ABaseResponse
{

    protected AgreementDetail detail;

    /**
     * Gets the value of the detail property.
     * 
     * @return
     *     possible object is
     *     {@link AgreementDetail }
     *     
     */
    public AgreementDetail getDetail() {
        return detail;
    }

    /**
     * Sets the value of the detail property.
     * 
     * @param value
     *     allowed object is
     *     {@link AgreementDetail }
     *     
     */
    public void setDetail(AgreementDetail value) {
        this.detail = value;
    }

}
