//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.05.20 at 11:01:46 AM CDT 
//


package com.searshc.hs.domi.service.merchandise.update.response;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;

import com.searshc.hs.base.ABase;



/**
 * <p>Java class for updateMerchandiseResponse complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="updateMerchandiseResponse">
 *   &lt;complexContent>
 *     &lt;extension base="{}aBase">
 *       &lt;sequence>
 *         &lt;element name="division" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="lwExpiration" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="merchandiseCode" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="merchandiseCodeDs" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="pwExpiration" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="xpExpiration" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "updateMerchandiseResponse", propOrder = {
    "division",
    "lwExpiration",
    "merchandiseCode",
    "merchandiseCodeDs",
    "pwExpiration",
    "xpExpiration"
})
public class UpdateMerchandiseResponse
    extends ABase
{

    protected String division;
    protected String lwExpiration;
    protected String merchandiseCode;
    protected String merchandiseCodeDs;
    protected String pwExpiration;
    protected String xpExpiration;

    /**
     * Gets the value of the division property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDivision() {
        return division;
    }

    /**
     * Sets the value of the division property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDivision(String value) {
        this.division = value;
    }

    /**
     * Gets the value of the lwExpiration property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLwExpiration() {
        return lwExpiration;
    }

    /**
     * Sets the value of the lwExpiration property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLwExpiration(String value) {
        this.lwExpiration = value;
    }

    /**
     * Gets the value of the merchandiseCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMerchandiseCode() {
        return merchandiseCode;
    }

    /**
     * Sets the value of the merchandiseCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMerchandiseCode(String value) {
        this.merchandiseCode = value;
    }

    /**
     * Gets the value of the merchandiseCodeDs property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMerchandiseCodeDs() {
        return merchandiseCodeDs;
    }

    /**
     * Sets the value of the merchandiseCodeDs property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMerchandiseCodeDs(String value) {
        this.merchandiseCodeDs = value;
    }

    /**
     * Gets the value of the pwExpiration property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPwExpiration() {
        return pwExpiration;
    }

    /**
     * Sets the value of the pwExpiration property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPwExpiration(String value) {
        this.pwExpiration = value;
    }

    /**
     * Gets the value of the xpExpiration property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getXpExpiration() {
        return xpExpiration;
    }

    /**
     * Sets the value of the xpExpiration property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setXpExpiration(String value) {
        this.xpExpiration = value;
    }

}
