//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.05.20 at 11:01:46 AM CDT 
//


package com.searshc.hs.domi.service.merchandise.lookup.list.response;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.searshc.hs.base.ABase;


/**
 * <p>Java class for agreement complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="agreement">
 *   &lt;complexContent>
 *     &lt;extension base="{}aBase">
 *       &lt;sequence>
 *         &lt;element name="agreementSuffix" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="coverageMonth" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="currExpDate" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="currStartDate" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="originalPrice" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="SPP_PGM_MKEY" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="SP_PGM_MKEY" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="SP_PLAN" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="serviceProductName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="serviceProductType" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="whoBoughtAgreement" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "agreement", propOrder = {
    "agreementSuffix",
    "coverageMonth",
    "currExpDate",
    "currStartDate",
    "originalPrice",
    "spppgmmkey",
    "sppgmmkey",
    "spplan",
    "serviceProductName",
    "serviceProductType",
    "whoBoughtAgreement"
})
@JsonIgnoreProperties(ignoreUnknown = true)
@JsonInclude(JsonInclude.Include.NON_NULL)
public class Agreement
    extends ABase
{

    protected String agreementSuffix;
    protected String coverageMonth;
    protected String currExpDate;
    protected String currStartDate;
    protected String originalPrice;
    @XmlElement(name = "SPP_PGM_MKEY")
    @JsonProperty("SPP_PGM_MKEY")
    protected String spppgmmkey;
    @XmlElement(name = "SP_PGM_MKEY")
    @JsonProperty("SP_PGM_MKEY")
    protected String sppgmmkey;
    @XmlElement(name = "SP_PLAN")
    @JsonProperty("SP_PLAN")
    protected String spplan;
    protected String serviceProductName;
    protected String serviceProductType;
    protected String whoBoughtAgreement;

    /**
     * Gets the value of the agreementSuffix property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAgreementSuffix() {
        return agreementSuffix;
    }

    /**
     * Sets the value of the agreementSuffix property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAgreementSuffix(String value) {
        this.agreementSuffix = value;
    }

    /**
     * Gets the value of the coverageMonth property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCoverageMonth() {
        return coverageMonth;
    }

    /**
     * Sets the value of the coverageMonth property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCoverageMonth(String value) {
        this.coverageMonth = value;
    }

    /**
     * Gets the value of the currExpDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCurrExpDate() {
        return currExpDate;
    }

    /**
     * Sets the value of the currExpDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCurrExpDate(String value) {
        this.currExpDate = value;
    }

    /**
     * Gets the value of the currStartDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCurrStartDate() {
        return currStartDate;
    }

    /**
     * Sets the value of the currStartDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCurrStartDate(String value) {
        this.currStartDate = value;
    }

    /**
     * Gets the value of the originalPrice property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOriginalPrice() {
        return originalPrice;
    }

    /**
     * Sets the value of the originalPrice property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOriginalPrice(String value) {
        this.originalPrice = value;
    }

    /**
     * Gets the value of the spppgmmkey property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSPPPGMMKEY() {
        return spppgmmkey;
    }

    /**
     * Sets the value of the spppgmmkey property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSPPPGMMKEY(String value) {
        this.spppgmmkey = value;
    }

    /**
     * Gets the value of the sppgmmkey property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSPPGMMKEY() {
        return sppgmmkey;
    }

    /**
     * Sets the value of the sppgmmkey property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSPPGMMKEY(String value) {
        this.sppgmmkey = value;
    }

    /**
     * Gets the value of the spplan property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSPPLAN() {
        return spplan;
    }

    /**
     * Sets the value of the spplan property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSPPLAN(String value) {
        this.spplan = value;
    }

    /**
     * Gets the value of the serviceProductName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getServiceProductName() {
        return serviceProductName;
    }

    /**
     * Sets the value of the serviceProductName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setServiceProductName(String value) {
        this.serviceProductName = value;
    }

    /**
     * Gets the value of the serviceProductType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getServiceProductType() {
        return serviceProductType;
    }

    /**
     * Sets the value of the serviceProductType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setServiceProductType(String value) {
        this.serviceProductType = value;
    }

    /**
     * Gets the value of the whoBoughtAgreement property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getWhoBoughtAgreement() {
        return whoBoughtAgreement;
    }

    /**
     * Sets the value of the whoBoughtAgreement property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setWhoBoughtAgreement(String value) {
        this.whoBoughtAgreement = value;
    }

}
