//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.05.20 at 11:01:46 AM CDT 
//


package com.searshc.hs.domi.service.merchandise.lookup.list.response;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.searshc.hs.base.ABase;


/**
 * <p>Java class for lookupMerchandiseListResponse complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="lookupMerchandiseListResponse">
 *   &lt;complexContent>
 *     &lt;extension base="{}aBase">
 *       &lt;sequence>
 *         &lt;element name="custMergeFlag" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="lastItemSuffix" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="merchandiseInfo" type="{}merchandiseInfo" minOccurs="0"/>
 *         &lt;element name="newCustKey" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="newLeadKey" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="totalItemsCount" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="totalRowsReturned" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlRootElement(name="LookupMerchandiseListResponse")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "lookupMerchandiseListResponse", propOrder = {
    "custMergeFlag",
    "lastItemSuffix",
    "merchandiseInfo",
    "newCustKey",
    "newLeadKey",
    "totalItemsCount",
    "totalRowsReturned"
})

@JsonIgnoreProperties(ignoreUnknown = true)
@JsonInclude(JsonInclude.Include.NON_NULL)
public class LookupMerchandiseListResponse
    extends ABase
{

    protected String custMergeFlag;
    protected String lastItemSuffix;
    protected MerchandiseInfo merchandiseInfo;
    protected String newCustKey;
    protected String newLeadKey;
    protected String totalItemsCount;
    protected String totalRowsReturned;

    /**
     * Gets the value of the custMergeFlag property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCustMergeFlag() {
        return custMergeFlag;
    }

    /**
     * Sets the value of the custMergeFlag property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCustMergeFlag(String value) {
        this.custMergeFlag = value;
    }

    /**
     * Gets the value of the lastItemSuffix property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLastItemSuffix() {
        return lastItemSuffix;
    }

    /**
     * Sets the value of the lastItemSuffix property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLastItemSuffix(String value) {
        this.lastItemSuffix = value;
    }

    /**
     * Gets the value of the merchandiseInfo property.
     * 
     * @return
     *     possible object is
     *     {@link MerchandiseInfo }
     *     
     */
    public MerchandiseInfo getMerchandiseInfo() {
        return merchandiseInfo;
    }

    /**
     * Sets the value of the merchandiseInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link MerchandiseInfo }
     *     
     */
    public void setMerchandiseInfo(MerchandiseInfo value) {
        this.merchandiseInfo = value;
    }

    /**
     * Gets the value of the newCustKey property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNewCustKey() {
        return newCustKey;
    }

    /**
     * Sets the value of the newCustKey property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNewCustKey(String value) {
        this.newCustKey = value;
    }

    /**
     * Gets the value of the newLeadKey property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNewLeadKey() {
        return newLeadKey;
    }

    /**
     * Sets the value of the newLeadKey property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNewLeadKey(String value) {
        this.newLeadKey = value;
    }

    /**
     * Gets the value of the totalItemsCount property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTotalItemsCount() {
        return totalItemsCount;
    }

    /**
     * Sets the value of the totalItemsCount property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTotalItemsCount(String value) {
        this.totalItemsCount = value;
    }

    /**
     * Gets the value of the totalRowsReturned property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTotalRowsReturned() {
        return totalRowsReturned;
    }

    /**
     * Sets the value of the totalRowsReturned property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTotalRowsReturned(String value) {
        this.totalRowsReturned = value;
    }

	/* (non-Javadoc)
	 * @see java.lang.Object#toString()
	 */
	@Override
	public String toString() {
		StringBuilder builder = new StringBuilder();
		builder.append("LookupMerchandiseListResponse [lastItemSuffix=");
		builder.append(lastItemSuffix);
		builder.append(", merchandiseInfo=");
		builder.append(merchandiseInfo);
		builder.append(", totalItemsCount=");
		builder.append(totalItemsCount);
		builder.append(", totalRowsReturned=");
		builder.append(totalRowsReturned);
		builder.append("]");
		return builder.toString();
	}

}
