//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.05.20 at 11:01:46 AM CDT 
//


package com.searshc.hs.base;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;

import com.searshc.hs.domi.service.merchandise.create.request.CreateMerchRequest;
import com.searshc.hs.domi.service.merchandise.create.response.CreateMerchResponse;
import com.searshc.hs.domi.service.merchandise.lookup.common.response.Merchandise;
import com.searshc.hs.domi.service.merchandise.lookup.details.request.LookupMerchandiseDetailsRequest;
import com.searshc.hs.domi.service.merchandise.lookup.details.response.LookupMerchandiseDetailsResponse;
import com.searshc.hs.domi.service.merchandise.lookup.details.response.MaintAgreement;
import com.searshc.hs.domi.service.merchandise.lookup.list.request.LookupMerchandiseListRequest;
import com.searshc.hs.domi.service.merchandise.lookup.list.response.Agreement;
import com.searshc.hs.domi.service.merchandise.lookup.list.response.LookupMerchandiseListResponse;
import com.searshc.hs.domi.service.merchandise.update.request.UpdateMerchandiseRequest;
import com.searshc.hs.domi.service.merchandise.update.response.UpdateMerchandiseResponse;


/**
 * <p>Java class for aBase complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="aBase">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */

@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "aBase")
@XmlSeeAlso({
    MaintAgreement.class,
    Agreement.class,
    CreateMerchResponse.class,
    LookupMerchandiseListResponse.class,
    UpdateMerchandiseRequest.class,
    CreateMerchRequest.class,
    LookupMerchandiseDetailsResponse.class,
    UpdateMerchandiseResponse.class,
    Merchandise.class,
    LookupMerchandiseDetailsRequest.class,
    LookupMerchandiseListRequest.class
})
public abstract class ABase {


}
