
package com.searshc.hs.som.thm.domain.telluride;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.7-b01-
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "Bank", targetNamespace = "http://www.epsilon.com/webservices/", wsdlLocation = "telluride.wsdl")
public class Bank
    extends Service
{

    private final static URL BANK_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(com.searshc.hs.som.thm.domain.telluride.Bank.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = com.searshc.hs.som.thm.domain.telluride.Bank.class.getResource("");
            url = new URL(baseUrl, "telluride.wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'telluride.wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        BANK_WSDL_LOCATION = url;
    }

    public Bank(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public Bank() {
        super(BANK_WSDL_LOCATION, new QName("http://www.epsilon.com/webservices/", "Bank"));
    }

    /**
     * 
     * @return
     *     returns BankSoap
     */
    @WebEndpoint(name = "BankSoap")
    public BankSoap getBankSoap() {
        return super.getPort(new QName("http://www.epsilon.com/webservices/", "BankSoap"), BankSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns BankSoap
     */
    @WebEndpoint(name = "BankSoap")
    public BankSoap getBankSoap(WebServiceFeature... features) {
        return super.getPort(new QName("http://www.epsilon.com/webservices/", "BankSoap"), BankSoap.class, features);
    }

    /**
     * 
     * @return
     *     returns BankSoap
     */
    @WebEndpoint(name = "BankSoap12")
    public BankSoap getBankSoap12() {
        return super.getPort(new QName("http://www.epsilon.com/webservices/", "BankSoap12"), BankSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns BankSoap
     */
    @WebEndpoint(name = "BankSoap12")
    public BankSoap getBankSoap12(WebServiceFeature... features) {
        return super.getPort(new QName("http://www.epsilon.com/webservices/", "BankSoap12"), BankSoap.class, features);
    }

}
