
package com.searshc.hs.som.thm.domain.telluride;

import javax.xml.ws.WebFault;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.7-b01-
 * Generated source version: 2.1
 * 
 */
@WebFault(name = "Exception", targetNamespace = "http://www.epsilon.com/webservices/")
public class Exception_Exception
    extends java.lang.Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private com.searshc.hs.som.thm.domain.telluride.Exception faultInfo;

    /**
     * 
     * @param message
     * @param faultInfo
     */
    public Exception_Exception(String message, com.searshc.hs.som.thm.domain.telluride.Exception faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param message
     * @param faultInfo
     * @param cause
     */
    public Exception_Exception(String message, com.searshc.hs.som.thm.domain.telluride.Exception faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: com.searshc.hs.som.thm.domain.telluride.Exception
     */
    public com.searshc.hs.som.thm.domain.telluride.Exception getFaultInfo() {
        return faultInfo;
    }

}
