//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.05.20 at 11:01:46 AM CDT 
//


package com.searshc.hs.domi.service.merchandise.lookup.common.response;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.searshc.hs.base.ABase;
import com.searshc.hs.domi.service.merchandise.lookup.details.response.MerchandiseDetails;
import com.searshc.hs.domi.service.merchandise.lookup.list.response.MerchandiseList;


/**
 * <p>Java class for merchandise complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="merchandise">
 *   &lt;complexContent>
 *     &lt;extension base="{}aBase">
 *       &lt;sequence>
 *         &lt;element name="agreementSuffix" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="brand" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="coverageCode" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="coverageCodeExpDate" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="divisionNum" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="itemInstallFlag" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="itemMaFlag" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="itemNum" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="itemServiceFlag" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="itemSuffix" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="lastPMCheck" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="merchandiseCode" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="merchandiseCodeDs" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="modelNum" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="pendingSOFlag" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="previousThirdParty" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="promoPMCheck" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="promoteMAFlag" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="purchaseDate" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="purchaseInstallFlag" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="salesCheckDate" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="salesCheckNo" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="serialNum" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="serviceLoc" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="specialty" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="whereBought" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "merchandise", propOrder = {
    "agreementSuffix",
    "brand",
    "coverageCode",
    "coverageCodeExpDate",
    "divisionNum",
    "itemInstallFlag",
    "itemMaFlag",
    "itemNum",
    "itemServiceFlag",
    "itemSuffix",
    "lastPMCheck",
    "merchandiseCode",
    "merchandiseCodeDs",
    "modelNum",
    "pendingSOFlag",
    "previousThirdParty",
    "promoPMCheck",
    "promoteMAFlag",
    "purchaseDate",
    "purchaseInstallFlag",
    "salesCheckDate",
    "salesCheckNo",
    "serialNum",
    "serviceLoc",
    "specialty",
    "whereBought",
    "custNum",
    "custType",
    "lastItemSuffix",
    "leadKey"
})
@XmlSeeAlso({
    MerchandiseList.class,
    MerchandiseDetails.class
})
@JsonIgnoreProperties(ignoreUnknown = true)
@JsonInclude(JsonInclude.Include.NON_NULL)
public class Merchandise
    extends ABase
{

    protected String agreementSuffix;
    protected String brand;
    protected String coverageCode;
    protected String coverageCodeExpDate;
    protected String divisionNum;
    protected String itemInstallFlag;
    protected String itemMaFlag;
    protected String itemNum;
    protected String itemServiceFlag;
    protected String itemSuffix;
    protected String lastPMCheck;
    protected String merchandiseCode;
    protected String merchandiseCodeDs;
    protected String modelNum;
    protected String pendingSOFlag;
    protected String previousThirdParty;
    protected String promoPMCheck;
    protected String promoteMAFlag;
    protected String purchaseDate;
    protected String purchaseInstallFlag;
    protected String salesCheckDate;
    protected String salesCheckNo;
    protected String serialNum;
    protected String serviceLoc;
    protected String specialty;
    protected String whereBought;
    protected String custNum;
    protected String custType;
    protected String lastItemSuffix;
    protected String leadKey;

    /**
     * Gets the value of the agreementSuffix property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAgreementSuffix() {
        return agreementSuffix;
    }

    /**
     * Sets the value of the agreementSuffix property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAgreementSuffix(String value) {
        this.agreementSuffix = value;
    }

    /**
     * Gets the value of the brand property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBrand() {
        return brand;
    }

    /**
     * Sets the value of the brand property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBrand(String value) {
        this.brand = value;
    }

    /**
     * Gets the value of the coverageCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCoverageCode() {
        return coverageCode;
    }

    /**
     * Sets the value of the coverageCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCoverageCode(String value) {
        this.coverageCode = value;
    }

    /**
     * Gets the value of the coverageCodeExpDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCoverageCodeExpDate() {
        return coverageCodeExpDate;
    }

    /**
     * Sets the value of the coverageCodeExpDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCoverageCodeExpDate(String value) {
        this.coverageCodeExpDate = value;
    }

    /**
     * Gets the value of the divisionNum property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDivisionNum() {
        return divisionNum;
    }

    /**
     * Sets the value of the divisionNum property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDivisionNum(String value) {
        this.divisionNum = value;
    }

    /**
     * Gets the value of the itemInstallFlag property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getItemInstallFlag() {
        return itemInstallFlag;
    }

    /**
     * Sets the value of the itemInstallFlag property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setItemInstallFlag(String value) {
        this.itemInstallFlag = value;
    }

    /**
     * Gets the value of the itemMaFlag property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getItemMaFlag() {
        return itemMaFlag;
    }

    /**
     * Sets the value of the itemMaFlag property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setItemMaFlag(String value) {
        this.itemMaFlag = value;
    }

    /**
     * Gets the value of the itemNum property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getItemNum() {
        return itemNum;
    }

    /**
     * Sets the value of the itemNum property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setItemNum(String value) {
        this.itemNum = value;
    }

    /**
     * Gets the value of the itemServiceFlag property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getItemServiceFlag() {
        return itemServiceFlag;
    }

    /**
     * Sets the value of the itemServiceFlag property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setItemServiceFlag(String value) {
        this.itemServiceFlag = value;
    }

    /**
     * Gets the value of the itemSuffix property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getItemSuffix() {
        return itemSuffix;
    }

    /**
     * Sets the value of the itemSuffix property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setItemSuffix(String value) {
        this.itemSuffix = value;
    }

    /**
     * Gets the value of the lastPMCheck property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLastPMCheck() {
        return lastPMCheck;
    }

    /**
     * Sets the value of the lastPMCheck property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLastPMCheck(String value) {
        this.lastPMCheck = value;
    }

    /**
     * Gets the value of the merchandiseCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMerchandiseCode() {
        return merchandiseCode;
    }

    /**
     * Sets the value of the merchandiseCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMerchandiseCode(String value) {
        this.merchandiseCode = value;
    }

    /**
     * Gets the value of the merchandiseCodeDs property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMerchandiseCodeDs() {
        return merchandiseCodeDs;
    }

    /**
     * Sets the value of the merchandiseCodeDs property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMerchandiseCodeDs(String value) {
        this.merchandiseCodeDs = value;
    }

    /**
     * Gets the value of the modelNum property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getModelNum() {
        return modelNum;
    }

    /**
     * Sets the value of the modelNum property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setModelNum(String value) {
        this.modelNum = value;
    }

    /**
     * Gets the value of the pendingSOFlag property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPendingSOFlag() {
        return pendingSOFlag;
    }

    /**
     * Sets the value of the pendingSOFlag property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPendingSOFlag(String value) {
        this.pendingSOFlag = value;
    }

    /**
     * Gets the value of the previousThirdParty property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPreviousThirdParty() {
        return previousThirdParty;
    }

    /**
     * Sets the value of the previousThirdParty property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPreviousThirdParty(String value) {
        this.previousThirdParty = value;
    }

    /**
     * Gets the value of the promoPMCheck property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPromoPMCheck() {
        return promoPMCheck;
    }

    /**
     * Sets the value of the promoPMCheck property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPromoPMCheck(String value) {
        this.promoPMCheck = value;
    }

    /**
     * Gets the value of the promoteMAFlag property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPromoteMAFlag() {
        return promoteMAFlag;
    }

    /**
     * Sets the value of the promoteMAFlag property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPromoteMAFlag(String value) {
        this.promoteMAFlag = value;
    }

    /**
     * Gets the value of the purchaseDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPurchaseDate() {
        return purchaseDate;
    }

    /**
     * Sets the value of the purchaseDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPurchaseDate(String value) {
        this.purchaseDate = value;
    }

    /**
     * Gets the value of the purchaseInstallFlag property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPurchaseInstallFlag() {
        return purchaseInstallFlag;
    }

    /**
     * Sets the value of the purchaseInstallFlag property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPurchaseInstallFlag(String value) {
        this.purchaseInstallFlag = value;
    }

    /**
     * Gets the value of the salesCheckDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSalesCheckDate() {
        return salesCheckDate;
    }

    /**
     * Sets the value of the salesCheckDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSalesCheckDate(String value) {
        this.salesCheckDate = value;
    }

    /**
     * Gets the value of the salesCheckNo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSalesCheckNo() {
        return salesCheckNo;
    }

    /**
     * Sets the value of the salesCheckNo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSalesCheckNo(String value) {
        this.salesCheckNo = value;
    }

    /**
     * Gets the value of the serialNum property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSerialNum() {
        return serialNum;
    }

    /**
     * Sets the value of the serialNum property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSerialNum(String value) {
        this.serialNum = value;
    }

    /**
     * Gets the value of the serviceLoc property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getServiceLoc() {
        return serviceLoc;
    }

    /**
     * Sets the value of the serviceLoc property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setServiceLoc(String value) {
        this.serviceLoc = value;
    }

    /**
     * Gets the value of the specialty property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSpecialty() {
        return specialty;
    }

    /**
     * Sets the value of the specialty property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSpecialty(String value) {
        this.specialty = value;
    }

    /**
     * Gets the value of the whereBought property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getWhereBought() {
        return whereBought;
    }

    /**
     * Sets the value of the whereBought property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setWhereBought(String value) {
        this.whereBought = value;
    }

	public String getCustNum() {
		return custNum;
	}

	public void setCustNum(String custNum) {
		this.custNum = custNum;
	}

	public String getCustType() {
		return custType;
	}

	public void setCustType(String custType) {
		this.custType = custType;
	}

	public String getLastItemSuffix() {
		return lastItemSuffix;
	}

	public void setLastItemSuffix(String lastItemSuffix) {
		this.lastItemSuffix = lastItemSuffix;
	}

	public String getLeadKey() {
		return leadKey;
	}

	public void setLeadKey(String leadKey) {
		this.leadKey = leadKey;
	}

	/* (non-Javadoc)
	 * @see java.lang.Object#toString()
	 */
	@Override
	public String toString() {
		StringBuilder builder = new StringBuilder();
		builder.append("Merchandise [brand=");
		builder.append(brand);
		builder.append(", coverageCode=");
		builder.append(coverageCode);
		builder.append(", coverageCodeExpDate=");
		builder.append(coverageCodeExpDate);
		builder.append(", divisionNum=");
		builder.append(divisionNum);
		builder.append(", itemNum=");
		builder.append(itemNum);
		builder.append(", itemSuffix=");
		builder.append(itemSuffix);
		builder.append(", merchandiseCode=");
		builder.append(merchandiseCode);
		builder.append(", merchandiseCodeDs=");
		builder.append(merchandiseCodeDs);
		builder.append(", modelNum=");
		builder.append(modelNum);
		builder.append(", purchaseDate=");
		builder.append(purchaseDate);
		builder.append(", serialNum=");
		builder.append(serialNum);
		builder.append(", custNum=");
		builder.append(custNum);
		builder.append(", custType=");
		builder.append(custType);
		builder.append("]");
		return builder.toString();
	}

}
