//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-833 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.03.04 at 10:15:02 PM IST 
//


package com.searshc.hs.som.thm.domain.npj;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for caseCustomer complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="caseCustomer">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="businessName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="consumerTypeCode" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="custInstructions" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="customerRefNbr" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="noEmailFl" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="noMailFl" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="noPhoneFl" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="preferredLngCode" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="premCustFl" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="socMedScrName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="sywrMemID" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="taxExemptDate" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="taxExemptFl" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="taxExemptNbr" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "caseCustomer", propOrder = {
    "businessName",
    "consumerTypeCode",
    "custInstructions",
    "customerRefNbr",
    "noEmailFl",
    "noMailFl",
    "noPhoneFl",
    "preferredLngCode",
    "premCustFl",
    "socMedScrName",
    "sywrMemID",
    "taxExemptDate",
    "taxExemptFl",
    "taxExemptNbr"
})
@XmlRootElement(name = "caseCustomer")
public class CaseCustomer {

    protected String businessName;
    protected String consumerTypeCode;
    protected String custInstructions;
    protected String customerRefNbr;
    protected String noEmailFl;
    protected String noMailFl;
    protected String noPhoneFl;
    protected String preferredLngCode;
    protected String premCustFl;
    protected String socMedScrName;
    protected String sywrMemID;
    protected String taxExemptDate;
    protected String taxExemptFl;
    protected String taxExemptNbr;

    /**
     * Gets the value of the businessName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBusinessName() {
        return businessName;
    }

    /**
     * Sets the value of the businessName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBusinessName(String value) {
        this.businessName = value;
    }

    /**
     * Gets the value of the consumerTypeCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getConsumerTypeCode() {
        return consumerTypeCode;
    }

    /**
     * Sets the value of the consumerTypeCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setConsumerTypeCode(String value) {
        this.consumerTypeCode = value;
    }

    /**
     * Gets the value of the custInstructions property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCustInstructions() {
        return custInstructions;
    }

    /**
     * Sets the value of the custInstructions property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCustInstructions(String value) {
        this.custInstructions = value;
    }

    /**
     * Gets the value of the customerRefNbr property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCustomerRefNbr() {
        return customerRefNbr;
    }

    /**
     * Sets the value of the customerRefNbr property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCustomerRefNbr(String value) {
        this.customerRefNbr = value;
    }

    /**
     * Gets the value of the noEmailFl property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNoEmailFl() {
        return noEmailFl;
    }

    /**
     * Sets the value of the noEmailFl property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNoEmailFl(String value) {
        this.noEmailFl = value;
    }

    /**
     * Gets the value of the noMailFl property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNoMailFl() {
        return noMailFl;
    }

    /**
     * Sets the value of the noMailFl property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNoMailFl(String value) {
        this.noMailFl = value;
    }

    /**
     * Gets the value of the noPhoneFl property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNoPhoneFl() {
        return noPhoneFl;
    }

    /**
     * Sets the value of the noPhoneFl property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNoPhoneFl(String value) {
        this.noPhoneFl = value;
    }

    /**
     * Gets the value of the preferredLngCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPreferredLngCode() {
        return preferredLngCode;
    }

    /**
     * Sets the value of the preferredLngCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPreferredLngCode(String value) {
        this.preferredLngCode = value;
    }

    /**
     * Gets the value of the premCustFl property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPremCustFl() {
        return premCustFl;
    }

    /**
     * Sets the value of the premCustFl property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPremCustFl(String value) {
        this.premCustFl = value;
    }

    /**
     * Gets the value of the socMedScrName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSocMedScrName() {
        return socMedScrName;
    }

    /**
     * Sets the value of the socMedScrName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSocMedScrName(String value) {
        this.socMedScrName = value;
    }

    /**
     * Gets the value of the sywrMemID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSywrMemID() {
        return sywrMemID;
    }

    /**
     * Sets the value of the sywrMemID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSywrMemID(String value) {
        this.sywrMemID = value;
    }

    /**
     * Gets the value of the taxExemptDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTaxExemptDate() {
        return taxExemptDate;
    }

    /**
     * Sets the value of the taxExemptDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTaxExemptDate(String value) {
        this.taxExemptDate = value;
    }

    /**
     * Gets the value of the taxExemptFl property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTaxExemptFl() {
        return taxExemptFl;
    }

    /**
     * Sets the value of the taxExemptFl property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTaxExemptFl(String value) {
        this.taxExemptFl = value;
    }

    /**
     * Gets the value of the taxExemptNbr property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTaxExemptNbr() {
        return taxExemptNbr;
    }

    /**
     * Sets the value of the taxExemptNbr property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTaxExemptNbr(String value) {
        this.taxExemptNbr = value;
    }

}
