//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-833 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.03.04 at 10:15:02 PM IST 
//


package com.searshc.hs.som.thm.domain.npj;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for customerSearchCriteria complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="customerSearchCriteria">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}alternateSearch" minOccurs="0"/>
 *         &lt;element ref="{}primarySearch" minOccurs="0"/>
 *         &lt;element ref="{}representativeSearch" minOccurs="0"/>
 *         &lt;element ref="{}salesCheckSearch" minOccurs="0"/>
 *         &lt;element name="setNumber" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="systemId" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "customerSearchCriteria", propOrder = {
    "alternateSearch",
    "primarySearch",
    "representativeSearch",
    "salesCheckSearch",
    "setNumber",
    "systemId"
})
@XmlRootElement(name = "customerSearchCriteria")
public class CustomerSearchCriteria {

    protected AlternateSearch alternateSearch;
    protected PrimarySearch primarySearch;
    protected RepresentativeSearch representativeSearch;
    protected SalesCheckSearch salesCheckSearch;
    protected int setNumber;
    protected String systemId;

    /**
     * Gets the value of the alternateSearch property.
     * 
     * @return
     *     possible object is
     *     {@link AlternateSearch }
     *     
     */
    public AlternateSearch getAlternateSearch() {
        return alternateSearch;
    }

    /**
     * Sets the value of the alternateSearch property.
     * 
     * @param value
     *     allowed object is
     *     {@link AlternateSearch }
     *     
     */
    public void setAlternateSearch(AlternateSearch value) {
        this.alternateSearch = value;
    }

    /**
     * Gets the value of the primarySearch property.
     * 
     * @return
     *     possible object is
     *     {@link PrimarySearch }
     *     
     */
    public PrimarySearch getPrimarySearch() {
        return primarySearch;
    }

    /**
     * Sets the value of the primarySearch property.
     * 
     * @param value
     *     allowed object is
     *     {@link PrimarySearch }
     *     
     */
    public void setPrimarySearch(PrimarySearch value) {
        this.primarySearch = value;
    }

    /**
     * Gets the value of the representativeSearch property.
     * 
     * @return
     *     possible object is
     *     {@link RepresentativeSearch }
     *     
     */
    public RepresentativeSearch getRepresentativeSearch() {
        return representativeSearch;
    }

    /**
     * Sets the value of the representativeSearch property.
     * 
     * @param value
     *     allowed object is
     *     {@link RepresentativeSearch }
     *     
     */
    public void setRepresentativeSearch(RepresentativeSearch value) {
        this.representativeSearch = value;
    }

    /**
     * Gets the value of the salesCheckSearch property.
     * 
     * @return
     *     possible object is
     *     {@link SalesCheckSearch }
     *     
     */
    public SalesCheckSearch getSalesCheckSearch() {
        return salesCheckSearch;
    }

    /**
     * Sets the value of the salesCheckSearch property.
     * 
     * @param value
     *     allowed object is
     *     {@link SalesCheckSearch }
     *     
     */
    public void setSalesCheckSearch(SalesCheckSearch value) {
        this.salesCheckSearch = value;
    }

    /**
     * Gets the value of the setNumber property.
     * 
     */
    public int getSetNumber() {
        return setNumber;
    }

    /**
     * Sets the value of the setNumber property.
     * 
     */
    public void setSetNumber(int value) {
        this.setNumber = value;
    }

    /**
     * Gets the value of the systemId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSystemId() {
        return systemId;
    }

    /**
     * Sets the value of the systemId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSystemId(String value) {
        this.systemId = value;
    }

}
