//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-833 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.03.04 at 10:15:02 PM IST 
//


package com.searshc.hs.som.thm.domain.npj;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for emailOptIn complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="emailOptIn">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="emailAddress" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="MMHOptInCd" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="SRSOptInCd" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "emailOptIn", propOrder = {
    "emailAddress",
    "mmhOptInCd",
    "srsOptInCd"
})
@XmlRootElement(name = "emailOptIns")
public class EmailOptIns {

    protected String emailAddress;
    @XmlElement(name = "MMHOptInCd")
    protected String mmhOptInCd;
    @XmlElement(name = "SRSOptInCd")
    protected String srsOptInCd;

    /**
     * Gets the value of the emailAddress property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEmailAddress() {
        return emailAddress;
    }

    /**
     * Sets the value of the emailAddress property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEmailAddress(String value) {
        this.emailAddress = value;
    }

    /**
     * Gets the value of the mmhOptInCd property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMMHOptInCd() {
        return mmhOptInCd;
    }

    /**
     * Sets the value of the mmhOptInCd property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMMHOptInCd(String value) {
        this.mmhOptInCd = value;
    }

    /**
     * Gets the value of the srsOptInCd property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSRSOptInCd() {
        return srsOptInCd;
    }

    /**
     * Sets the value of the srsOptInCd property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSRSOptInCd(String value) {
        this.srsOptInCd = value;
    }

}
