//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-833 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.03.04 at 10:15:02 PM IST 
//


package com.searshc.hs.som.thm.domain.npj;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for npjCustomer complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="npjCustomer">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="accountExpMonth" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="accountExpYear" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="accountNumber" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="accountType" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="addressFlag" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="agreementNumber" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="aptFlag" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="bestCustomer" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="cfClubMemberInd" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="clubExpirationDate" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="clubMember" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="clubName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="commBusinessCode" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="commDiscountPct" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="commEinTaxNumber" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="commFlag" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="commPOFlag" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="crossStreets" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="custFlag" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="custInstructionsFlag" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="custLocation" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="custPricing" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="customerLeadInd" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="emailCaptureEmpNo" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="emailCaptureUnit" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="emailOptIns" type="{}emailOptIn" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="emailSourceCd" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="emailSourceFunc" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="emailSvcCd" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="empCompany" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="empFlag" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="empRetireInd" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="employeeUnit" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="employee_ID" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="instructions" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="locationSuffix" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="locationType" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="memberShipNo" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="merchandiseCode" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="numAccounts" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="numItems" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="numOfCurrFurPA" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="numOfExpiredPA" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="numOfOpenSO" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="paperLead" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="pendingSO" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="recordSource" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="resource" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="salesLeadFlag" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="solicitMa" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="solicitOther" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="sourceCode" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="specialPrice" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="storeNum" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="svcClubCd" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="sywrMemID" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="taxEffDate" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="taxExemptFlag" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="taxExemptID" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="taxExpDate" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="thirdParty" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="transactionSeqNum" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="unitIndicator" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="unitType" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="updateTime" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="updateTimeStamp" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "npjCustomer", propOrder = {
    "accountExpMonth",
    "accountExpYear",
    "accountNumber",
    "accountType",
    "addressFlag",
    "agreementNumber",
    "aptFlag",
    "bestCustomer",
    "cfClubMemberInd",
    "clubExpirationDate",
    "clubMember",
    "clubName",
    "commBusinessCode",
    "commDiscountPct",
    "commEinTaxNumber",
    "commFlag",
    "commPOFlag",
    "crossStreets",
    "custFlag",
    "custInstructionsFlag",
    "custLocation",
    "custPricing",
    "customerLeadInd",
    "emailCaptureEmpNo",
    "emailCaptureUnit",
    "emailOptIns",
    "emailSourceCd",
    "emailSourceFunc",
    "emailSvcCd",
    "empCompany",
    "empFlag",
    "empRetireInd",
    "employeeUnit",
    "employeeID",
    "instructions",
    "locationSuffix",
    "locationType",
    "memberShipNo",
    "merchandiseCode",
    "numAccounts",
    "numItems",
    "numOfCurrFurPA",
    "numOfExpiredPA",
    "numOfOpenSO",
    "paperLead",
    "pendingSO",
    "recordSource",
    "resource",
    "salesLeadFlag",
    "solicitMa",
    "solicitOther",
    "sourceCode",
    "specialPrice",
    "storeNum",
    "svcClubCd",
    "sywrMemID",
    "taxEffDate",
    "taxExemptFlag",
    "taxExemptID",
    "taxExpDate",
    "thirdParty",
    "transactionSeqNum",
    "unitIndicator",
    "unitType",
    "updateTime",
    "updateTimeStamp"
})
@XmlRootElement(name = "npjCustomer")
public class NpjCustomer {

    protected String accountExpMonth;
    protected String accountExpYear;
    protected String accountNumber;
    protected String accountType;
    protected String addressFlag;
    protected String agreementNumber;
    protected String aptFlag;
    protected String bestCustomer;
    protected String cfClubMemberInd;
    protected String clubExpirationDate;
    protected String clubMember;
    protected String clubName;
    protected String commBusinessCode;
    protected String commDiscountPct;
    protected String commEinTaxNumber;
    protected String commFlag;
    protected String commPOFlag;
    protected String crossStreets;
    protected String custFlag;
    protected String custInstructionsFlag;
    protected String custLocation;
    protected String custPricing;
    protected String customerLeadInd;
    protected String emailCaptureEmpNo;
    protected String emailCaptureUnit;
    @XmlElement(nillable = true)
    protected List<EmailOptIns> emailOptIns;
    protected String emailSourceCd;
    protected String emailSourceFunc;
    protected String emailSvcCd;
    protected String empCompany;
    protected String empFlag;
    protected String empRetireInd;
    protected String employeeUnit;
    @XmlElement(name = "employee_ID")
    protected String employeeID;
    protected String instructions;
    protected String locationSuffix;
    protected String locationType;
    protected String memberShipNo;
    protected String merchandiseCode;
    protected String numAccounts;
    protected String numItems;
    protected String numOfCurrFurPA;
    protected String numOfExpiredPA;
    protected String numOfOpenSO;
    protected String paperLead;
    protected String pendingSO;
    protected String recordSource;
    protected String resource;
    protected String salesLeadFlag;
    protected String solicitMa;
    protected String solicitOther;
    protected String sourceCode;
    protected String specialPrice;
    protected String storeNum;
    protected String svcClubCd;
    protected String sywrMemID;
    protected String taxEffDate;
    protected String taxExemptFlag;
    protected String taxExemptID;
    protected String taxExpDate;
    protected String thirdParty;
    protected String transactionSeqNum;
    protected String unitIndicator;
    protected String unitType;
    protected String updateTime;
    protected String updateTimeStamp;

    /**
     * Gets the value of the accountExpMonth property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAccountExpMonth() {
        return accountExpMonth;
    }

    /**
     * Sets the value of the accountExpMonth property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAccountExpMonth(String value) {
        this.accountExpMonth = value;
    }

    /**
     * Gets the value of the accountExpYear property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAccountExpYear() {
        return accountExpYear;
    }

    /**
     * Sets the value of the accountExpYear property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAccountExpYear(String value) {
        this.accountExpYear = value;
    }

    /**
     * Gets the value of the accountNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAccountNumber() {
        return accountNumber;
    }

    /**
     * Sets the value of the accountNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAccountNumber(String value) {
        this.accountNumber = value;
    }

    /**
     * Gets the value of the accountType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAccountType() {
        return accountType;
    }

    /**
     * Sets the value of the accountType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAccountType(String value) {
        this.accountType = value;
    }

    /**
     * Gets the value of the addressFlag property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAddressFlag() {
        return addressFlag;
    }

    /**
     * Sets the value of the addressFlag property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAddressFlag(String value) {
        this.addressFlag = value;
    }

    /**
     * Gets the value of the agreementNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAgreementNumber() {
        return agreementNumber;
    }

    /**
     * Sets the value of the agreementNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAgreementNumber(String value) {
        this.agreementNumber = value;
    }

    /**
     * Gets the value of the aptFlag property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAptFlag() {
        return aptFlag;
    }

    /**
     * Sets the value of the aptFlag property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAptFlag(String value) {
        this.aptFlag = value;
    }

    /**
     * Gets the value of the bestCustomer property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBestCustomer() {
        return bestCustomer;
    }

    /**
     * Sets the value of the bestCustomer property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBestCustomer(String value) {
        this.bestCustomer = value;
    }

    /**
     * Gets the value of the cfClubMemberInd property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCfClubMemberInd() {
        return cfClubMemberInd;
    }

    /**
     * Sets the value of the cfClubMemberInd property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCfClubMemberInd(String value) {
        this.cfClubMemberInd = value;
    }

    /**
     * Gets the value of the clubExpirationDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getClubExpirationDate() {
        return clubExpirationDate;
    }

    /**
     * Sets the value of the clubExpirationDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setClubExpirationDate(String value) {
        this.clubExpirationDate = value;
    }

    /**
     * Gets the value of the clubMember property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getClubMember() {
        return clubMember;
    }

    /**
     * Sets the value of the clubMember property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setClubMember(String value) {
        this.clubMember = value;
    }

    /**
     * Gets the value of the clubName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getClubName() {
        return clubName;
    }

    /**
     * Sets the value of the clubName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setClubName(String value) {
        this.clubName = value;
    }

    /**
     * Gets the value of the commBusinessCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCommBusinessCode() {
        return commBusinessCode;
    }

    /**
     * Sets the value of the commBusinessCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCommBusinessCode(String value) {
        this.commBusinessCode = value;
    }

    /**
     * Gets the value of the commDiscountPct property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCommDiscountPct() {
        return commDiscountPct;
    }

    /**
     * Sets the value of the commDiscountPct property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCommDiscountPct(String value) {
        this.commDiscountPct = value;
    }

    /**
     * Gets the value of the commEinTaxNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCommEinTaxNumber() {
        return commEinTaxNumber;
    }

    /**
     * Sets the value of the commEinTaxNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCommEinTaxNumber(String value) {
        this.commEinTaxNumber = value;
    }

    /**
     * Gets the value of the commFlag property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCommFlag() {
        return commFlag;
    }

    /**
     * Sets the value of the commFlag property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCommFlag(String value) {
        this.commFlag = value;
    }

    /**
     * Gets the value of the commPOFlag property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCommPOFlag() {
        return commPOFlag;
    }

    /**
     * Sets the value of the commPOFlag property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCommPOFlag(String value) {
        this.commPOFlag = value;
    }

    /**
     * Gets the value of the crossStreets property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCrossStreets() {
        return crossStreets;
    }

    /**
     * Sets the value of the crossStreets property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCrossStreets(String value) {
        this.crossStreets = value;
    }

    /**
     * Gets the value of the custFlag property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCustFlag() {
        return custFlag;
    }

    /**
     * Sets the value of the custFlag property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCustFlag(String value) {
        this.custFlag = value;
    }

    /**
     * Gets the value of the custInstructionsFlag property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCustInstructionsFlag() {
        return custInstructionsFlag;
    }

    /**
     * Sets the value of the custInstructionsFlag property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCustInstructionsFlag(String value) {
        this.custInstructionsFlag = value;
    }

    /**
     * Gets the value of the custLocation property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCustLocation() {
        return custLocation;
    }

    /**
     * Sets the value of the custLocation property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCustLocation(String value) {
        this.custLocation = value;
    }

    /**
     * Gets the value of the custPricing property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCustPricing() {
        return custPricing;
    }

    /**
     * Sets the value of the custPricing property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCustPricing(String value) {
        this.custPricing = value;
    }

    /**
     * Gets the value of the customerLeadInd property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCustomerLeadInd() {
        return customerLeadInd;
    }

    /**
     * Sets the value of the customerLeadInd property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCustomerLeadInd(String value) {
        this.customerLeadInd = value;
    }

    /**
     * Gets the value of the emailCaptureEmpNo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEmailCaptureEmpNo() {
        return emailCaptureEmpNo;
    }

    /**
     * Sets the value of the emailCaptureEmpNo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEmailCaptureEmpNo(String value) {
        this.emailCaptureEmpNo = value;
    }

    /**
     * Gets the value of the emailCaptureUnit property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEmailCaptureUnit() {
        return emailCaptureUnit;
    }

    /**
     * Sets the value of the emailCaptureUnit property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEmailCaptureUnit(String value) {
        this.emailCaptureUnit = value;
    }

    /**
     * Gets the value of the emailOptIns property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the emailOptIns property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getEmailOptIns().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link EmailOptIns }
     * 
     * 
     */
    public List<EmailOptIns> getEmailOptIns() {
        if (emailOptIns == null) {
            emailOptIns = new ArrayList<EmailOptIns>();
        }
        return this.emailOptIns;
    }

    /**
     * Gets the value of the emailSourceCd property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEmailSourceCd() {
        return emailSourceCd;
    }

    /**
     * Sets the value of the emailSourceCd property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEmailSourceCd(String value) {
        this.emailSourceCd = value;
    }

    /**
     * Gets the value of the emailSourceFunc property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEmailSourceFunc() {
        return emailSourceFunc;
    }

    /**
     * Sets the value of the emailSourceFunc property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEmailSourceFunc(String value) {
        this.emailSourceFunc = value;
    }

    /**
     * Gets the value of the emailSvcCd property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEmailSvcCd() {
        return emailSvcCd;
    }

    /**
     * Sets the value of the emailSvcCd property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEmailSvcCd(String value) {
        this.emailSvcCd = value;
    }

    /**
     * Gets the value of the empCompany property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEmpCompany() {
        return empCompany;
    }

    /**
     * Sets the value of the empCompany property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEmpCompany(String value) {
        this.empCompany = value;
    }

    /**
     * Gets the value of the empFlag property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEmpFlag() {
        return empFlag;
    }

    /**
     * Sets the value of the empFlag property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEmpFlag(String value) {
        this.empFlag = value;
    }

    /**
     * Gets the value of the empRetireInd property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEmpRetireInd() {
        return empRetireInd;
    }

    /**
     * Sets the value of the empRetireInd property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEmpRetireInd(String value) {
        this.empRetireInd = value;
    }

    /**
     * Gets the value of the employeeUnit property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEmployeeUnit() {
        return employeeUnit;
    }

    /**
     * Sets the value of the employeeUnit property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEmployeeUnit(String value) {
        this.employeeUnit = value;
    }

    /**
     * Gets the value of the employeeID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEmployeeID() {
        return employeeID;
    }

    /**
     * Sets the value of the employeeID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEmployeeID(String value) {
        this.employeeID = value;
    }

    /**
     * Gets the value of the instructions property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getInstructions() {
        return instructions;
    }

    /**
     * Sets the value of the instructions property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setInstructions(String value) {
        this.instructions = value;
    }

    /**
     * Gets the value of the locationSuffix property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLocationSuffix() {
        return locationSuffix;
    }

    /**
     * Sets the value of the locationSuffix property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLocationSuffix(String value) {
        this.locationSuffix = value;
    }

    /**
     * Gets the value of the locationType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLocationType() {
        return locationType;
    }

    /**
     * Sets the value of the locationType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLocationType(String value) {
        this.locationType = value;
    }

    /**
     * Gets the value of the memberShipNo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMemberShipNo() {
        return memberShipNo;
    }

    /**
     * Sets the value of the memberShipNo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMemberShipNo(String value) {
        this.memberShipNo = value;
    }

    /**
     * Gets the value of the merchandiseCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMerchandiseCode() {
        return merchandiseCode;
    }

    /**
     * Sets the value of the merchandiseCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMerchandiseCode(String value) {
        this.merchandiseCode = value;
    }

    /**
     * Gets the value of the numAccounts property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNumAccounts() {
        return numAccounts;
    }

    /**
     * Sets the value of the numAccounts property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNumAccounts(String value) {
        this.numAccounts = value;
    }

    /**
     * Gets the value of the numItems property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNumItems() {
        return numItems;
    }

    /**
     * Sets the value of the numItems property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNumItems(String value) {
        this.numItems = value;
    }

    /**
     * Gets the value of the numOfCurrFurPA property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNumOfCurrFurPA() {
        return numOfCurrFurPA;
    }

    /**
     * Sets the value of the numOfCurrFurPA property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNumOfCurrFurPA(String value) {
        this.numOfCurrFurPA = value;
    }

    /**
     * Gets the value of the numOfExpiredPA property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNumOfExpiredPA() {
        return numOfExpiredPA;
    }

    /**
     * Sets the value of the numOfExpiredPA property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNumOfExpiredPA(String value) {
        this.numOfExpiredPA = value;
    }

    /**
     * Gets the value of the numOfOpenSO property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNumOfOpenSO() {
        return numOfOpenSO;
    }

    /**
     * Sets the value of the numOfOpenSO property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNumOfOpenSO(String value) {
        this.numOfOpenSO = value;
    }

    /**
     * Gets the value of the paperLead property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPaperLead() {
        return paperLead;
    }

    /**
     * Sets the value of the paperLead property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPaperLead(String value) {
        this.paperLead = value;
    }

    /**
     * Gets the value of the pendingSO property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPendingSO() {
        return pendingSO;
    }

    /**
     * Sets the value of the pendingSO property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPendingSO(String value) {
        this.pendingSO = value;
    }

    /**
     * Gets the value of the recordSource property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRecordSource() {
        return recordSource;
    }

    /**
     * Sets the value of the recordSource property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRecordSource(String value) {
        this.recordSource = value;
    }

    /**
     * Gets the value of the resource property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getResource() {
        return resource;
    }

    /**
     * Sets the value of the resource property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setResource(String value) {
        this.resource = value;
    }

    /**
     * Gets the value of the salesLeadFlag property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSalesLeadFlag() {
        return salesLeadFlag;
    }

    /**
     * Sets the value of the salesLeadFlag property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSalesLeadFlag(String value) {
        this.salesLeadFlag = value;
    }

    /**
     * Gets the value of the solicitMa property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSolicitMa() {
        return solicitMa;
    }

    /**
     * Sets the value of the solicitMa property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSolicitMa(String value) {
        this.solicitMa = value;
    }

    /**
     * Gets the value of the solicitOther property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSolicitOther() {
        return solicitOther;
    }

    /**
     * Sets the value of the solicitOther property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSolicitOther(String value) {
        this.solicitOther = value;
    }

    /**
     * Gets the value of the sourceCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSourceCode() {
        return sourceCode;
    }

    /**
     * Sets the value of the sourceCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSourceCode(String value) {
        this.sourceCode = value;
    }

    /**
     * Gets the value of the specialPrice property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSpecialPrice() {
        return specialPrice;
    }

    /**
     * Sets the value of the specialPrice property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSpecialPrice(String value) {
        this.specialPrice = value;
    }

    /**
     * Gets the value of the storeNum property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStoreNum() {
        return storeNum;
    }

    /**
     * Sets the value of the storeNum property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStoreNum(String value) {
        this.storeNum = value;
    }

    /**
     * Gets the value of the svcClubCd property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSvcClubCd() {
        return svcClubCd;
    }

    /**
     * Sets the value of the svcClubCd property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSvcClubCd(String value) {
        this.svcClubCd = value;
    }

    /**
     * Gets the value of the sywrMemID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSywrMemID() {
        return sywrMemID;
    }

    /**
     * Sets the value of the sywrMemID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSywrMemID(String value) {
        this.sywrMemID = value;
    }

    /**
     * Gets the value of the taxEffDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTaxEffDate() {
        return taxEffDate;
    }

    /**
     * Sets the value of the taxEffDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTaxEffDate(String value) {
        this.taxEffDate = value;
    }

    /**
     * Gets the value of the taxExemptFlag property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTaxExemptFlag() {
        return taxExemptFlag;
    }

    /**
     * Sets the value of the taxExemptFlag property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTaxExemptFlag(String value) {
        this.taxExemptFlag = value;
    }

    /**
     * Gets the value of the taxExemptID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTaxExemptID() {
        return taxExemptID;
    }

    /**
     * Sets the value of the taxExemptID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTaxExemptID(String value) {
        this.taxExemptID = value;
    }

    /**
     * Gets the value of the taxExpDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTaxExpDate() {
        return taxExpDate;
    }

    /**
     * Sets the value of the taxExpDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTaxExpDate(String value) {
        this.taxExpDate = value;
    }

    /**
     * Gets the value of the thirdParty property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getThirdParty() {
        return thirdParty;
    }

    /**
     * Sets the value of the thirdParty property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setThirdParty(String value) {
        this.thirdParty = value;
    }

    /**
     * Gets the value of the transactionSeqNum property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTransactionSeqNum() {
        return transactionSeqNum;
    }

    /**
     * Sets the value of the transactionSeqNum property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTransactionSeqNum(String value) {
        this.transactionSeqNum = value;
    }

    /**
     * Gets the value of the unitIndicator property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUnitIndicator() {
        return unitIndicator;
    }

    /**
     * Sets the value of the unitIndicator property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUnitIndicator(String value) {
        this.unitIndicator = value;
    }

    /**
     * Gets the value of the unitType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUnitType() {
        return unitType;
    }

    /**
     * Sets the value of the unitType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUnitType(String value) {
        this.unitType = value;
    }

    /**
     * Gets the value of the updateTime property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUpdateTime() {
        return updateTime;
    }

    /**
     * Sets the value of the updateTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUpdateTime(String value) {
        this.updateTime = value;
    }

    /**
     * Gets the value of the updateTimeStamp property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUpdateTimeStamp() {
        return updateTimeStamp;
    }

    /**
     * Sets the value of the updateTimeStamp property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUpdateTimeStamp(String value) {
        this.updateTimeStamp = value;
    }

}
