//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-833 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.03.04 at 10:15:02 PM IST 
//


package com.searshc.hs.som.thm.domain.npj;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.searshc.hs.som.thm.domain package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Customer_QNAME = new QName("", "customer");
    private final static QName _ContactData_QNAME = new QName("", "contactData");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.searshc.hs.som.thm.domain
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link CaseCustomer }
     * 
     */
    public CaseCustomer createCaseCustomer() {
        return new CaseCustomer();
    }

    /**
     * Create an instance of {@link EmailOptIns }
     * 
     */
    public EmailOptIns createEmailOptIns() {
        return new EmailOptIns();
    }

    /**
     * Create an instance of {@link RepresentativeSearch }
     * 
     */
    public RepresentativeSearch createRepresentativeSearch() {
        return new RepresentativeSearch();
    }

    /**
     * Create an instance of {@link SalesCheckSearch }
     * 
     */
    public SalesCheckSearch createSalesCheckSearch() {
        return new SalesCheckSearch();
    }

    /**
     * Create an instance of {@link PhoneData }
     * 
     */
    public PhoneData createPhoneData() {
        return new PhoneData();
    }

    /**
     * Create an instance of {@link ContactData }
     * 
     */
    public ContactData createContactData() {
        return new ContactData();
    }

    /**
     * Create an instance of {@link CustomerSearchCriteria }
     * 
     */
    public CustomerSearchCriteria createCustomerSearchCriteria() {
        return new CustomerSearchCriteria();
    }

    /**
     * Create an instance of {@link EmailData }
     * 
     */
    public EmailData createEmailData() {
        return new EmailData();
    }

    /**
     * Create an instance of {@link CaseCustomerSearchResult }
     * 
     */
    public CaseCustomerSearchResult createCaseCustomerSearchResult() {
        return new CaseCustomerSearchResult();
    }

    /**
     * Create an instance of {@link CustomerDetails }
     * 
     */
    public CustomerDetails createCustomerDetails() {
        return new CustomerDetails();
    }

    /**
     * Create an instance of {@link AlternateSearch }
     * 
     */
    public AlternateSearch createAlternateSearch() {
        return new AlternateSearch();
    }

    /**
     * Create an instance of {@link CaseCountResult }
     * 
     */
    public CaseCountResult createCaseCountResult() {
        return new CaseCountResult();
    }

    /**
     * Create an instance of {@link Customer }
     * 
     */
    public Customer createCustomer() {
        return new Customer();
    }

    /**
     * Create an instance of {@link AddressData }
     * 
     */
    public AddressData createAddressData() {
        return new AddressData();
    }

    /**
     * Create an instance of {@link NameData }
     * 
     */
    public NameData createNameData() {
        return new NameData();
    }

    /**
     * Create an instance of {@link NpjCustomer }
     * 
     */
    public NpjCustomer createNpjCustomer() {
        return new NpjCustomer();
    }

    /**
     * Create an instance of {@link CustomerData }
     * 
     */
    public CustomerData createCustomerData() {
        return new CustomerData();
    }

    /**
     * Create an instance of {@link SearchCriteria }
     * 
     */
    public SearchCriteria createSearchCriteria() {
        return new SearchCriteria();
    }

    /**
     * Create an instance of {@link PrimarySearch }
     * 
     */
    public PrimarySearch createPrimarySearch() {
        return new PrimarySearch();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Customer }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "customer")
    public JAXBElement<Customer> createCustomer(Customer value) {
        return new JAXBElement<Customer>(_Customer_QNAME, Customer.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ContactData }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "contactData")
    public JAXBElement<ContactData> createContactData(ContactData value) {
        return new JAXBElement<ContactData>(_ContactData_QNAME, ContactData.class, null, value);
    }

}
