
package com.epsilon.webservices;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;

import javax.xml.namespace.QName;

import com.searshc.rewards.profile.service.soap.ProfileSoapImplService;

/**
 * This class was generated by Apache CXF 3.1.11
 * 2017-04-14T18:02:39.523+05:30
 * Generated source version: 3.1.11
 * 
 */
public final class ProfileSoap_ProfileSoapImplPort_Client {

    private static final QName SERVICE_NAME = new QName("http://soap.service.profile.rewards.sears.com/", "ProfileSoapImplService");

    private ProfileSoap_ProfileSoapImplPort_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = ProfileSoapImplService.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        ProfileSoapImplService ss = new ProfileSoapImplService(wsdlURL, SERVICE_NAME);
        ProfileSoap port = ss.getProfileSoapImplPort();  
        
        {
        System.out.println("Invoking memberReplaceCard...");
        java.lang.String _memberReplaceCard_originalMemberNumber = "_memberReplaceCard_originalMemberNumber100608319";
        java.lang.String _memberReplaceCard_newMemberNumber = "_memberReplaceCard_newMemberNumber528236322";
        java.lang.String _memberReplaceCard_messageVersion = "_memberReplaceCard_messageVersion2074125617";
        com.epsilon.webservices.MemberReplaceCardResponse.MemberReplaceCardResult _memberReplaceCard__return = port.memberReplaceCard(_memberReplaceCard_originalMemberNumber, _memberReplaceCard_newMemberNumber, _memberReplaceCard_messageVersion);
        System.out.println("memberReplaceCard.result=" + _memberReplaceCard__return);


        }
        {
        System.out.println("Invoking updateMemberPrimaryProfile...");
        java.lang.String _updateMemberPrimaryProfile_messageVersion = "_updateMemberPrimaryProfile_messageVersion-1919152698";
        java.lang.String _updateMemberPrimaryProfile_memberNumber = "_updateMemberPrimaryProfile_memberNumber840823643";
        java.lang.String _updateMemberPrimaryProfile_requestorID = "_updateMemberPrimaryProfile_requestorID-628535934";
        java.lang.String _updateMemberPrimaryProfile_storeNumber = "_updateMemberPrimaryProfile_storeNumber-1334145403";
        java.lang.String _updateMemberPrimaryProfile_terminal = "_updateMemberPrimaryProfile_terminal-1693819925";
        java.lang.String _updateMemberPrimaryProfile_currentDate = "_updateMemberPrimaryProfile_currentDate1150143546";
        java.lang.String _updateMemberPrimaryProfile_currentTime = "_updateMemberPrimaryProfile_currentTime949875420";
        java.lang.String _updateMemberPrimaryProfile_prefix = "_updateMemberPrimaryProfile_prefix-1916606840";
        java.lang.String _updateMemberPrimaryProfile_firstName = "_updateMemberPrimaryProfile_firstName706263222";
        java.lang.String _updateMemberPrimaryProfile_lastName = "_updateMemberPrimaryProfile_lastName-2018878001";
        java.lang.String _updateMemberPrimaryProfile_middleInitial = "_updateMemberPrimaryProfile_middleInitial384053148";
        java.lang.String _updateMemberPrimaryProfile_suffix = "_updateMemberPrimaryProfile_suffix-88519375";
        java.lang.String _updateMemberPrimaryProfile_authFirstName = "_updateMemberPrimaryProfile_authFirstName-1836908672";
        java.lang.String _updateMemberPrimaryProfile_authLastName = "_updateMemberPrimaryProfile_authLastName3892073";
        java.lang.String _updateMemberPrimaryProfile_clubDNPStatus = "_updateMemberPrimaryProfile_clubDNPStatus-1485570758";
        java.lang.String _updateMemberPrimaryProfile_clubMembershipUpdatedBy = "_updateMemberPrimaryProfile_clubMembershipUpdatedBy173423367";
        java.lang.String _updateMemberPrimaryProfile_dateUpdated = "_updateMemberPrimaryProfile_dateUpdated-1213021955";
        java.lang.String _updateMemberPrimaryProfile_dob = "_updateMemberPrimaryProfile_dob835131500";
        java.lang.String _updateMemberPrimaryProfile_testAccount = "_updateMemberPrimaryProfile_testAccount1037183204";
        java.lang.String _updateMemberPrimaryProfile_accountStatus = "_updateMemberPrimaryProfile_accountStatus-856854280";
        java.lang.String _updateMemberPrimaryProfile_statusChangeReasonCode = "_updateMemberPrimaryProfile_statusChangeReasonCode718362746";
        java.lang.String _updateMemberPrimaryProfile_shcAssociateInd = "_updateMemberPrimaryProfile_shcAssociateInd1913675332";
        java.lang.String _updateMemberPrimaryProfile_wirelessPermissionFlag = "_updateMemberPrimaryProfile_wirelessPermissionFlag-961563557";
        java.lang.String _updateMemberPrimaryProfile_languagePreference = "_updateMemberPrimaryProfile_languagePreference1206325609";
        java.lang.String _updateMemberPrimaryProfile_address1 = "_updateMemberPrimaryProfile_address11737462117";
        java.lang.String _updateMemberPrimaryProfile_address2 = "_updateMemberPrimaryProfile_address2914148759";
        java.lang.String _updateMemberPrimaryProfile_city = "_updateMemberPrimaryProfile_city1673781530";
        java.lang.String _updateMemberPrimaryProfile_state = "_updateMemberPrimaryProfile_state885569166";
        java.lang.String _updateMemberPrimaryProfile_zipCode = "_updateMemberPrimaryProfile_zipCode-1031560942";
        java.lang.String _updateMemberPrimaryProfile_zipCodeExtension = "_updateMemberPrimaryProfile_zipCodeExtension959325881";
        java.lang.String _updateMemberPrimaryProfile_countryCode = "_updateMemberPrimaryProfile_countryCode1436109244";
        java.lang.String _updateMemberPrimaryProfile_emailAddress = "_updateMemberPrimaryProfile_emailAddress-225895942";
        java.lang.String _updateMemberPrimaryProfile_emailValidation = "_updateMemberPrimaryProfile_emailValidation650541244";
        java.lang.String _updateMemberPrimaryProfile_clubEmailOptStatus = "_updateMemberPrimaryProfile_clubEmailOptStatus-1604463260";
        java.lang.String _updateMemberPrimaryProfile_tnCStatus = "_updateMemberPrimaryProfile_tnCStatus2009640350";
        java.lang.String _updateMemberPrimaryProfile_tnCVersion = "_updateMemberPrimaryProfile_tnCVersion817766777";
        java.lang.String _updateMemberPrimaryProfile_charity = "_updateMemberPrimaryProfile_charity59093961";
        java.lang.String _updateMemberPrimaryProfile_profileUpdate = "_updateMemberPrimaryProfile_profileUpdate-532644952";
        com.epsilon.webservices.ArrayOfPOSPrompt _updateMemberPrimaryProfile_posPrompt = new com.epsilon.webservices.ArrayOfPOSPrompt();
        java.util.List<com.epsilon.webservices.POSPromptQuestions> _updateMemberPrimaryProfile_posPromptPOSPromptQuestions = new java.util.ArrayList<com.epsilon.webservices.POSPromptQuestions>();
        com.epsilon.webservices.POSPromptQuestions _updateMemberPrimaryProfile_posPromptPOSPromptQuestionsVal1 = new com.epsilon.webservices.POSPromptQuestions();
        _updateMemberPrimaryProfile_posPromptPOSPromptQuestionsVal1.setPromptGroupName("PromptGroupName-1901964605");
        _updateMemberPrimaryProfile_posPromptPOSPromptQuestionsVal1.setQuestionPackageID("QuestionPackageID618554653");
        _updateMemberPrimaryProfile_posPromptPOSPromptQuestionsVal1.setAttributeID("AttributeID-909138351");
        _updateMemberPrimaryProfile_posPromptPOSPromptQuestionsVal1.setAnswerChoice("AnswerChoice2040707104");
        _updateMemberPrimaryProfile_posPromptPOSPromptQuestionsVal1.setQuestionTextID("QuestionTextID435233272");
        com.epsilon.webservices.POSPromptQuestions.AnswerChoices _updateMemberPrimaryProfile_posPromptPOSPromptQuestionsVal1AnswerChoices = new com.epsilon.webservices.POSPromptQuestions.AnswerChoices();
        java.util.List<com.epsilon.webservices.POSPromptQuestions.AnswerChoices.AnswerOption> _updateMemberPrimaryProfile_posPromptPOSPromptQuestionsVal1AnswerChoicesAnswerOption = new java.util.ArrayList<com.epsilon.webservices.POSPromptQuestions.AnswerChoices.AnswerOption>();
        _updateMemberPrimaryProfile_posPromptPOSPromptQuestionsVal1AnswerChoices.getAnswerOption().addAll(_updateMemberPrimaryProfile_posPromptPOSPromptQuestionsVal1AnswerChoicesAnswerOption);
        _updateMemberPrimaryProfile_posPromptPOSPromptQuestionsVal1.setAnswerChoices(_updateMemberPrimaryProfile_posPromptPOSPromptQuestionsVal1AnswerChoices);
        _updateMemberPrimaryProfile_posPromptPOSPromptQuestionsVal1.setQuestionRuleID("QuestionRuleID-1144225130");
        com.epsilon.webservices.POSPromptQuestions.FollowupQuestions _updateMemberPrimaryProfile_posPromptPOSPromptQuestionsVal1FollowupQuestions = new com.epsilon.webservices.POSPromptQuestions.FollowupQuestions();
        java.util.List<com.epsilon.webservices.POSPromptQuestions.FollowupQuestions.FollowupQuestion> _updateMemberPrimaryProfile_posPromptPOSPromptQuestionsVal1FollowupQuestionsFollowupQuestion = new java.util.ArrayList<com.epsilon.webservices.POSPromptQuestions.FollowupQuestions.FollowupQuestion>();
        _updateMemberPrimaryProfile_posPromptPOSPromptQuestionsVal1FollowupQuestions.getFollowupQuestion().addAll(_updateMemberPrimaryProfile_posPromptPOSPromptQuestionsVal1FollowupQuestionsFollowupQuestion);
        _updateMemberPrimaryProfile_posPromptPOSPromptQuestionsVal1.setFollowupQuestions(_updateMemberPrimaryProfile_posPromptPOSPromptQuestionsVal1FollowupQuestions);
        _updateMemberPrimaryProfile_posPromptPOSPromptQuestions.add(_updateMemberPrimaryProfile_posPromptPOSPromptQuestionsVal1);
        _updateMemberPrimaryProfile_posPrompt.getPOSPromptQuestions().addAll(_updateMemberPrimaryProfile_posPromptPOSPromptQuestions);
        com.epsilon.webservices.AdditionalAttributes _updateMemberPrimaryProfile_additionalAttributes = new com.epsilon.webservices.AdditionalAttributes();
        java.util.List<com.epsilon.webservices.AdditionalAttribute> _updateMemberPrimaryProfile_additionalAttributesAdditionalAttribute = new java.util.ArrayList<com.epsilon.webservices.AdditionalAttribute>();
        com.epsilon.webservices.AdditionalAttribute _updateMemberPrimaryProfile_additionalAttributesAdditionalAttributeVal1 = new com.epsilon.webservices.AdditionalAttribute();
        _updateMemberPrimaryProfile_additionalAttributesAdditionalAttributeVal1.setAttrName("AttrName-617394208");
        _updateMemberPrimaryProfile_additionalAttributesAdditionalAttributeVal1.setAttrValue("AttrValue214932326");
        _updateMemberPrimaryProfile_additionalAttributesAdditionalAttribute.add(_updateMemberPrimaryProfile_additionalAttributesAdditionalAttributeVal1);
        _updateMemberPrimaryProfile_additionalAttributes.getAdditionalAttribute().addAll(_updateMemberPrimaryProfile_additionalAttributesAdditionalAttribute);
        com.epsilon.webservices.ArrayOfPhone _updateMemberPrimaryProfile_phoneNumbers = new com.epsilon.webservices.ArrayOfPhone();
        java.util.List<com.epsilon.webservices.Phone> _updateMemberPrimaryProfile_phoneNumbersPhone = new java.util.ArrayList<com.epsilon.webservices.Phone>();
        com.epsilon.webservices.Phone _updateMemberPrimaryProfile_phoneNumbersPhoneVal1 = new com.epsilon.webservices.Phone();
        _updateMemberPrimaryProfile_phoneNumbersPhoneVal1.setPhoneType("PhoneType1301340472");
        _updateMemberPrimaryProfile_phoneNumbersPhoneVal1.setPreferredPhoneType("PreferredPhoneType-160181817");
        _updateMemberPrimaryProfile_phoneNumbersPhoneVal1.setPhoneNumber("PhoneNumber-1826212229");
        _updateMemberPrimaryProfile_phoneNumbersPhoneVal1.setCarrierCode("CarrierCode1013219528");
        _updateMemberPrimaryProfile_phoneNumbersPhoneVal1.setPhoneValidated("PhoneValidated-666685359");
        _updateMemberPrimaryProfile_phoneNumbersPhone.add(_updateMemberPrimaryProfile_phoneNumbersPhoneVal1);
        _updateMemberPrimaryProfile_phoneNumbers.getPhone().addAll(_updateMemberPrimaryProfile_phoneNumbersPhone);
        com.epsilon.webservices.ArrayOfAffinity _updateMemberPrimaryProfile_affinities = new com.epsilon.webservices.ArrayOfAffinity();
        java.util.List<com.epsilon.webservices.Affinity> _updateMemberPrimaryProfile_affinitiesAffinity = new java.util.ArrayList<com.epsilon.webservices.Affinity>();
        com.epsilon.webservices.Affinity _updateMemberPrimaryProfile_affinitiesAffinityVal1 = new com.epsilon.webservices.Affinity();
        _updateMemberPrimaryProfile_affinitiesAffinityVal1.setAffinityID("AffinityID212029077");
        _updateMemberPrimaryProfile_affinitiesAffinityVal1.setAffinityStatus("AffinityStatus868117985");
        _updateMemberPrimaryProfile_affinitiesAffinityVal1.setAffiliationCode("AffiliationCode1170030139");
        _updateMemberPrimaryProfile_affinitiesAffinityVal1.setOfferCode("OfferCode-909825082");
        _updateMemberPrimaryProfile_affinitiesAffinityVal1.setAffinityAdditionalAttributes("AffinityAdditionalAttributes-1228092415");
        _updateMemberPrimaryProfile_affinitiesAffinityVal1.setAffinityNumber("AffinityNumber-2106634478");
        _updateMemberPrimaryProfile_affinitiesAffinityVal1.setAffinityStartTS("AffinityStartTS-270606449");
        _updateMemberPrimaryProfile_affinitiesAffinityVal1.setAffinityEndTS("AffinityEndTS-589178377");
        _updateMemberPrimaryProfile_affinitiesAffinity.add(_updateMemberPrimaryProfile_affinitiesAffinityVal1);
        _updateMemberPrimaryProfile_affinities.getAffinity().addAll(_updateMemberPrimaryProfile_affinitiesAffinity);
        com.epsilon.webservices.ArrayOfAttr _updateMemberPrimaryProfile_attributes = new com.epsilon.webservices.ArrayOfAttr();
        java.util.List<com.epsilon.webservices.ArrayOfAttr.Attr> _updateMemberPrimaryProfile_attributesAttr = new java.util.ArrayList<com.epsilon.webservices.ArrayOfAttr.Attr>();
        com.epsilon.webservices.ArrayOfAttr.Attr _updateMemberPrimaryProfile_attributesAttrVal1 = new com.epsilon.webservices.ArrayOfAttr.Attr();
        _updateMemberPrimaryProfile_attributesAttrVal1.setAttrname("Attrname454804600");
        _updateMemberPrimaryProfile_attributesAttrVal1.setAttrvalue("Attrvalue526099476");
        _updateMemberPrimaryProfile_attributesAttr.add(_updateMemberPrimaryProfile_attributesAttrVal1);
        _updateMemberPrimaryProfile_attributes.getAttr().addAll(_updateMemberPrimaryProfile_attributesAttr);
        com.epsilon.webservices.UpdateMemberPrimaryProfileResponse.UpdateMemberPrimaryProfileResult _updateMemberPrimaryProfile__return = port.updateMemberPrimaryProfile(_updateMemberPrimaryProfile_messageVersion, _updateMemberPrimaryProfile_memberNumber, _updateMemberPrimaryProfile_requestorID, _updateMemberPrimaryProfile_storeNumber, _updateMemberPrimaryProfile_terminal, _updateMemberPrimaryProfile_currentDate, _updateMemberPrimaryProfile_currentTime, _updateMemberPrimaryProfile_prefix, _updateMemberPrimaryProfile_firstName, _updateMemberPrimaryProfile_lastName, _updateMemberPrimaryProfile_middleInitial, _updateMemberPrimaryProfile_suffix, _updateMemberPrimaryProfile_authFirstName, _updateMemberPrimaryProfile_authLastName, _updateMemberPrimaryProfile_clubDNPStatus, _updateMemberPrimaryProfile_clubMembershipUpdatedBy, _updateMemberPrimaryProfile_dateUpdated, _updateMemberPrimaryProfile_dob, _updateMemberPrimaryProfile_testAccount, _updateMemberPrimaryProfile_accountStatus, _updateMemberPrimaryProfile_statusChangeReasonCode, _updateMemberPrimaryProfile_shcAssociateInd, _updateMemberPrimaryProfile_wirelessPermissionFlag, _updateMemberPrimaryProfile_languagePreference, _updateMemberPrimaryProfile_address1, _updateMemberPrimaryProfile_address2, _updateMemberPrimaryProfile_city, _updateMemberPrimaryProfile_state, _updateMemberPrimaryProfile_zipCode, _updateMemberPrimaryProfile_zipCodeExtension, _updateMemberPrimaryProfile_countryCode, _updateMemberPrimaryProfile_emailAddress, _updateMemberPrimaryProfile_emailValidation, _updateMemberPrimaryProfile_clubEmailOptStatus, _updateMemberPrimaryProfile_tnCStatus, _updateMemberPrimaryProfile_tnCVersion, _updateMemberPrimaryProfile_charity, _updateMemberPrimaryProfile_profileUpdate, _updateMemberPrimaryProfile_posPrompt, _updateMemberPrimaryProfile_additionalAttributes, _updateMemberPrimaryProfile_phoneNumbers, _updateMemberPrimaryProfile_affinities, _updateMemberPrimaryProfile_attributes);
        System.out.println("updateMemberPrimaryProfile.result=" + _updateMemberPrimaryProfile__return);


        }
        {
        System.out.println("Invoking dateTimeOnServer...");
        java.lang.Object _dateTimeOnServer_parameters = null;
        java.lang.Object _dateTimeOnServer__return = port.dateTimeOnServer(_dateTimeOnServer_parameters);
        System.out.println("dateTimeOnServer.result=" + _dateTimeOnServer__return);


        }
        {
        System.out.println("Invoking updateMemberPin...");
        java.lang.String _updateMemberPin_messageVersion = "_updateMemberPin_messageVersion-579444508";
        java.lang.String _updateMemberPin_memberNumber = "_updateMemberPin_memberNumber-1218722177";
        java.lang.String _updateMemberPin_requestorID = "_updateMemberPin_requestorID-575120535";
        java.lang.String _updateMemberPin_currentDate = "_updateMemberPin_currentDate1907903476";
        java.lang.String _updateMemberPin_currentTime = "_updateMemberPin_currentTime2112101468";
        java.lang.String _updateMemberPin_pinNumber = "_updateMemberPin_pinNumber172650461";
        com.epsilon.webservices.UpdateMemberPinResponse.UpdateMemberPinResult _updateMemberPin__return = port.updateMemberPin(_updateMemberPin_messageVersion, _updateMemberPin_memberNumber, _updateMemberPin_requestorID, _updateMemberPin_currentDate, _updateMemberPin_currentTime, _updateMemberPin_pinNumber);
        System.out.println("updateMemberPin.result=" + _updateMemberPin__return);


        }
        {
        System.out.println("Invoking updateMemberEmail...");
        java.lang.String _updateMemberEmail_messageVersion = "_updateMemberEmail_messageVersion608199704";
        java.lang.String _updateMemberEmail_memberNumber = "_updateMemberEmail_memberNumber31890187";
        java.lang.String _updateMemberEmail_requestorID = "_updateMemberEmail_requestorID-744235247";
        java.lang.String _updateMemberEmail_currentDate = "_updateMemberEmail_currentDate2016308053";
        java.lang.String _updateMemberEmail_currentTime = "_updateMemberEmail_currentTime1925808561";
        java.lang.String _updateMemberEmail_emailAddress = "_updateMemberEmail_emailAddress1721629570";
        java.lang.String _updateMemberEmail_emailValidation = "_updateMemberEmail_emailValidation1189927241";
        java.lang.String _updateMemberEmail_clubEmailOptStatus = "_updateMemberEmail_clubEmailOptStatus2093572888";
        java.lang.String _updateMemberEmail_clubMembershipUpdatedBy = "_updateMemberEmail_clubMembershipUpdatedBy-228805472";
        com.epsilon.webservices.UpdateMemberEmailResponse.UpdateMemberEmailResult _updateMemberEmail__return = port.updateMemberEmail(_updateMemberEmail_messageVersion, _updateMemberEmail_memberNumber, _updateMemberEmail_requestorID, _updateMemberEmail_currentDate, _updateMemberEmail_currentTime, _updateMemberEmail_emailAddress, _updateMemberEmail_emailValidation, _updateMemberEmail_clubEmailOptStatus, _updateMemberEmail_clubMembershipUpdatedBy);
        System.out.println("updateMemberEmail.result=" + _updateMemberEmail__return);


        }
        {
        System.out.println("Invoking createMember...");
        java.lang.String _createMember_memberNumber = "_createMember_memberNumber1777373719";
        java.lang.String _createMember_emailAddress = "_createMember_emailAddress1902370280";
        java.lang.String _createMember_emailValidation = "_createMember_emailValidation1677021858";
        java.lang.String _createMember_prefix = "_createMember_prefix1326246175";
        java.lang.String _createMember_suffix = "_createMember_suffix-1519457504";
        java.lang.String _createMember_firstName = "_createMember_firstName-1636981467";
        java.lang.String _createMember_middleInitial = "_createMember_middleInitial1787340131";
        java.lang.String _createMember_testAccount = "_createMember_testAccount600791824";
        java.lang.String _createMember_lastName = "_createMember_lastName-1234504752";
        java.lang.String _createMember_address1 = "_createMember_address1-95025536";
        java.lang.String _createMember_address2 = "_createMember_address2353049505";
        java.lang.String _createMember_city = "_createMember_city626385676";
        java.lang.String _createMember_state = "_createMember_state77251512";
        java.lang.String _createMember_zipCode = "_createMember_zipCode-1537450509";
        java.lang.String _createMember_zipCodeExtension = "_createMember_zipCodeExtension1708759452";
        java.lang.String _createMember_countryCode = "_createMember_countryCode-2003271493";
        java.lang.String _createMember_dob = "_createMember_dob1516239504";
        java.lang.String _createMember_currentDate = "_createMember_currentDate201625703";
        java.lang.String _createMember_currentTime = "_createMember_currentTime362104050";
        java.lang.String _createMember_clubMembershipCreatedBy = "_createMember_clubMembershipCreatedBy-1363364251";
        java.lang.String _createMember_clubDNPStatus = "_createMember_clubDNPStatus-1224690121";
        java.lang.String _createMember_shcAssociateInd = "_createMember_shcAssociateInd-468753559";
        java.lang.String _createMember_cardDesignType = "_createMember_cardDesignType396137541";
        java.lang.String _createMember_wirelessPermissionFlag = "_createMember_wirelessPermissionFlag-203519543";
        java.lang.String _createMember_clubEmailOptStatus = "_createMember_clubEmailOptStatus-1939118856";
        java.lang.String _createMember_preferredLanguage = "_createMember_preferredLanguage745806877";
        java.lang.String _createMember_storeNumber = "_createMember_storeNumber1058223386";
        java.lang.String _createMember_terminal = "_createMember_terminal-1305985491";
        java.lang.String _createMember_requestorID = "_createMember_requestorID1139734543";
        java.lang.String _createMember_messageVersion = "_createMember_messageVersion1004575090";
        java.lang.String _createMember_enrollmentOfferCode = "_createMember_enrollmentOfferCode-1578636284";
        java.lang.String _createMember_pinNumber = "_createMember_pinNumber-1948050506";
        java.lang.String _createMember_tnCStatus = "_createMember_tnCStatus1944402539";
        java.lang.String _createMember_tnCVersion = "_createMember_tnCVersion-1746641513";
        com.epsilon.webservices.ArrayOfPhone _createMember_phoneNumbers = new com.epsilon.webservices.ArrayOfPhone();
        java.util.List<com.epsilon.webservices.Phone> _createMember_phoneNumbersPhone = new java.util.ArrayList<com.epsilon.webservices.Phone>();
        com.epsilon.webservices.Phone _createMember_phoneNumbersPhoneVal1 = new com.epsilon.webservices.Phone();
        _createMember_phoneNumbersPhoneVal1.setPhoneType("PhoneType-1667902719");
        _createMember_phoneNumbersPhoneVal1.setPreferredPhoneType("PreferredPhoneType-553854983");
        _createMember_phoneNumbersPhoneVal1.setPhoneNumber("PhoneNumber-1411035212");
        _createMember_phoneNumbersPhoneVal1.setCarrierCode("CarrierCode-734119251");
        _createMember_phoneNumbersPhoneVal1.setPhoneValidated("PhoneValidated-45049309");
        _createMember_phoneNumbersPhone.add(_createMember_phoneNumbersPhoneVal1);
        _createMember_phoneNumbers.getPhone().addAll(_createMember_phoneNumbersPhone);
        com.epsilon.webservices.ArrayOfAffinity _createMember_affinities = new com.epsilon.webservices.ArrayOfAffinity();
        java.util.List<com.epsilon.webservices.Affinity> _createMember_affinitiesAffinity = new java.util.ArrayList<com.epsilon.webservices.Affinity>();
        com.epsilon.webservices.Affinity _createMember_affinitiesAffinityVal1 = new com.epsilon.webservices.Affinity();
        _createMember_affinitiesAffinityVal1.setAffinityID("AffinityID-1205701679");
        _createMember_affinitiesAffinityVal1.setAffinityStatus("AffinityStatus1911594894");
        _createMember_affinitiesAffinityVal1.setAffiliationCode("AffiliationCode-1794402627");
        _createMember_affinitiesAffinityVal1.setOfferCode("OfferCode-1507742094");
        _createMember_affinitiesAffinityVal1.setAffinityAdditionalAttributes("AffinityAdditionalAttributes-1672830350");
        _createMember_affinitiesAffinityVal1.setAffinityNumber("AffinityNumber-915623649");
        _createMember_affinitiesAffinityVal1.setAffinityStartTS("AffinityStartTS1477671659");
        _createMember_affinitiesAffinityVal1.setAffinityEndTS("AffinityEndTS-847877360");
        _createMember_affinitiesAffinity.add(_createMember_affinitiesAffinityVal1);
        _createMember_affinities.getAffinity().addAll(_createMember_affinitiesAffinity);
        com.epsilon.webservices.ArrayOfAttr _createMember_attributes = new com.epsilon.webservices.ArrayOfAttr();
        java.util.List<com.epsilon.webservices.ArrayOfAttr.Attr> _createMember_attributesAttr = new java.util.ArrayList<com.epsilon.webservices.ArrayOfAttr.Attr>();
        com.epsilon.webservices.ArrayOfAttr.Attr _createMember_attributesAttrVal1 = new com.epsilon.webservices.ArrayOfAttr.Attr();
        _createMember_attributesAttrVal1.setAttrname("Attrname1251413438");
        _createMember_attributesAttrVal1.setAttrvalue("Attrvalue-119489841");
        _createMember_attributesAttr.add(_createMember_attributesAttrVal1);
        _createMember_attributes.getAttr().addAll(_createMember_attributesAttr);
        com.epsilon.webservices.CreateMemberResponse.CreateMemberResult _createMember__return = port.createMember(_createMember_memberNumber, _createMember_emailAddress, _createMember_emailValidation, _createMember_prefix, _createMember_suffix, _createMember_firstName, _createMember_middleInitial, _createMember_testAccount, _createMember_lastName, _createMember_address1, _createMember_address2, _createMember_city, _createMember_state, _createMember_zipCode, _createMember_zipCodeExtension, _createMember_countryCode, _createMember_dob, _createMember_currentDate, _createMember_currentTime, _createMember_clubMembershipCreatedBy, _createMember_clubDNPStatus, _createMember_shcAssociateInd, _createMember_cardDesignType, _createMember_wirelessPermissionFlag, _createMember_clubEmailOptStatus, _createMember_preferredLanguage, _createMember_storeNumber, _createMember_terminal, _createMember_requestorID, _createMember_messageVersion, _createMember_enrollmentOfferCode, _createMember_pinNumber, _createMember_tnCStatus, _createMember_tnCVersion, _createMember_phoneNumbers, _createMember_affinities, _createMember_attributes);
        System.out.println("createMember.result=" + _createMember__return);


        }
        {
        System.out.println("Invoking updateEmailConfirmed...");
        java.lang.String _updateEmailConfirmed_messageVersion = "_updateEmailConfirmed_messageVersion1985405419";
        java.lang.String _updateEmailConfirmed_memberNumber = "_updateEmailConfirmed_memberNumber972929182";
        java.lang.String _updateEmailConfirmed_requestorID = "_updateEmailConfirmed_requestorID-15397929";
        java.lang.String _updateEmailConfirmed_currentDate = "_updateEmailConfirmed_currentDate-711595442";
        java.lang.String _updateEmailConfirmed_currentTime = "_updateEmailConfirmed_currentTime867367348";
        java.lang.String _updateEmailConfirmed_emailAddress = "_updateEmailConfirmed_emailAddress1538637534";
        java.lang.String _updateEmailConfirmed_emailConfirmed = "_updateEmailConfirmed_emailConfirmed1717279221";
        com.epsilon.webservices.UpdateEmailConfirmedResponse.UpdateEmailConfirmedResult _updateEmailConfirmed__return = port.updateEmailConfirmed(_updateEmailConfirmed_messageVersion, _updateEmailConfirmed_memberNumber, _updateEmailConfirmed_requestorID, _updateEmailConfirmed_currentDate, _updateEmailConfirmed_currentTime, _updateEmailConfirmed_emailAddress, _updateEmailConfirmed_emailConfirmed);
        System.out.println("updateEmailConfirmed.result=" + _updateEmailConfirmed__return);


        }
        {
        System.out.println("Invoking updateMemberAffinitySubscriptions...");
        java.lang.String _updateMemberAffinitySubscriptions_memberNumber = "_updateMemberAffinitySubscriptions_memberNumber-2136626982";
        com.epsilon.webservices.ArrayOfAffinity _updateMemberAffinitySubscriptions_affinities = new com.epsilon.webservices.ArrayOfAffinity();
        java.util.List<com.epsilon.webservices.Affinity> _updateMemberAffinitySubscriptions_affinitiesAffinity = new java.util.ArrayList<com.epsilon.webservices.Affinity>();
        com.epsilon.webservices.Affinity _updateMemberAffinitySubscriptions_affinitiesAffinityVal1 = new com.epsilon.webservices.Affinity();
        _updateMemberAffinitySubscriptions_affinitiesAffinityVal1.setAffinityID("AffinityID-168211340");
        _updateMemberAffinitySubscriptions_affinitiesAffinityVal1.setAffinityStatus("AffinityStatus-823096167");
        _updateMemberAffinitySubscriptions_affinitiesAffinityVal1.setAffiliationCode("AffiliationCode328052856");
        _updateMemberAffinitySubscriptions_affinitiesAffinityVal1.setOfferCode("OfferCode-1745788990");
        _updateMemberAffinitySubscriptions_affinitiesAffinityVal1.setAffinityAdditionalAttributes("AffinityAdditionalAttributes1521288387");
        _updateMemberAffinitySubscriptions_affinitiesAffinityVal1.setAffinityNumber("AffinityNumber-1591682621");
        _updateMemberAffinitySubscriptions_affinitiesAffinityVal1.setAffinityStartTS("AffinityStartTS-215661504");
        _updateMemberAffinitySubscriptions_affinitiesAffinityVal1.setAffinityEndTS("AffinityEndTS-1959558875");
        _updateMemberAffinitySubscriptions_affinitiesAffinity.add(_updateMemberAffinitySubscriptions_affinitiesAffinityVal1);
        _updateMemberAffinitySubscriptions_affinities.getAffinity().addAll(_updateMemberAffinitySubscriptions_affinitiesAffinity);
        java.lang.String _updateMemberAffinitySubscriptions_messageVersion = "_updateMemberAffinitySubscriptions_messageVersion-908869350";
        java.lang.String _updateMemberAffinitySubscriptions_requestorID = "_updateMemberAffinitySubscriptions_requestorID-122796068";
        java.lang.String _updateMemberAffinitySubscriptions_storeNumber = "_updateMemberAffinitySubscriptions_storeNumber-2040755908";
        java.lang.String _updateMemberAffinitySubscriptions_terminal = "_updateMemberAffinitySubscriptions_terminal840030463";
        java.lang.String _updateMemberAffinitySubscriptions_associateId = "_updateMemberAffinitySubscriptions_associateId-130307450";
        java.lang.String _updateMemberAffinitySubscriptions_user = "_updateMemberAffinitySubscriptions_user-1960655720";
        com.epsilon.webservices.UpdateMemberAffinitySubscriptionsResponse.UpdateMemberAffinitySubscriptionsResult _updateMemberAffinitySubscriptions__return = port.updateMemberAffinitySubscriptions(_updateMemberAffinitySubscriptions_memberNumber, _updateMemberAffinitySubscriptions_affinities, _updateMemberAffinitySubscriptions_messageVersion, _updateMemberAffinitySubscriptions_requestorID, _updateMemberAffinitySubscriptions_storeNumber, _updateMemberAffinitySubscriptions_terminal, _updateMemberAffinitySubscriptions_associateId, _updateMemberAffinitySubscriptions_user);
        System.out.println("updateMemberAffinitySubscriptions.result=" + _updateMemberAffinitySubscriptions__return);


        }
        {
        System.out.println("Invoking validatePin...");
        java.lang.String _validatePin_memberNumber = "_validatePin_memberNumber575687233";
        java.lang.String _validatePin_requestorID = "_validatePin_requestorID1477798501";
        java.lang.String _validatePin_currentDate = "_validatePin_currentDate595575448";
        java.lang.String _validatePin_currentTime = "_validatePin_currentTime2113467073";
        java.lang.String _validatePin_pinNumber = "_validatePin_pinNumber-2075170276";
        java.lang.String _validatePin_messageVersion = "_validatePin_messageVersion-1494459121";
        com.epsilon.webservices.ValidatePinResponse.ValidatePinResult _validatePin__return = port.validatePin(_validatePin_memberNumber, _validatePin_requestorID, _validatePin_currentDate, _validatePin_currentTime, _validatePin_pinNumber, _validatePin_messageVersion);
        System.out.println("validatePin.result=" + _validatePin__return);


        }
        {
        System.out.println("Invoking getMemberPrimaryProfile...");
        java.lang.String _getMemberPrimaryProfile_memberNumber = "_getMemberPrimaryProfile_memberNumber2033097887";
        java.lang.String _getMemberPrimaryProfile_messageVersion = "_getMemberPrimaryProfile_messageVersion-261243556";
        com.epsilon.webservices.GetMemberPrimaryProfileResponse.GetMemberPrimaryProfileResult _getMemberPrimaryProfile__return = port.getMemberPrimaryProfile(_getMemberPrimaryProfile_memberNumber, _getMemberPrimaryProfile_messageVersion);
        System.out.println("getMemberPrimaryProfile.result=" + _getMemberPrimaryProfile__return);


        }
        {
        System.out.println("Invoking updateMemberPrompts...");
        com.epsilon.webservices.UpdateMemberPrompts _updateMemberPrompts_parameters = new com.epsilon.webservices.UpdateMemberPrompts();
        _updateMemberPrompts_parameters.setMemberNumber("MemberNumber-1485250071");
        _updateMemberPrompts_parameters.setMessageVersion("MessageVersion-627130601");
        _updateMemberPrompts_parameters.setRequestorID("RequestorID1342633497");
        _updateMemberPrompts_parameters.setCurrentDate("CurrentDate-298485494");
        _updateMemberPrompts_parameters.setCurrentTime("CurrentTime1477103782");
        _updateMemberPrompts_parameters.setStoreNumber("StoreNumber916922112");
        _updateMemberPrompts_parameters.setTerminal("Terminal-1853824411");
        com.epsilon.webservices.ArrayOfPOSPromptQuestions _updateMemberPrompts_parametersPOSPrompt = new com.epsilon.webservices.ArrayOfPOSPromptQuestions();
        java.util.List<com.epsilon.webservices.POSPromptQuestions> _updateMemberPrompts_parametersPOSPromptPOSPromptQuestions = new java.util.ArrayList<com.epsilon.webservices.POSPromptQuestions>();
        com.epsilon.webservices.POSPromptQuestions _updateMemberPrompts_parametersPOSPromptPOSPromptQuestionsVal1 = new com.epsilon.webservices.POSPromptQuestions();
        _updateMemberPrompts_parametersPOSPromptPOSPromptQuestionsVal1.setPromptGroupName("PromptGroupName-32032847");
        _updateMemberPrompts_parametersPOSPromptPOSPromptQuestionsVal1.setQuestionPackageID("QuestionPackageID-874876926");
        _updateMemberPrompts_parametersPOSPromptPOSPromptQuestionsVal1.setAttributeID("AttributeID-1033092615");
        _updateMemberPrompts_parametersPOSPromptPOSPromptQuestionsVal1.setAnswerChoice("AnswerChoice-770605635");
        _updateMemberPrompts_parametersPOSPromptPOSPromptQuestionsVal1.setQuestionTextID("QuestionTextID-629722533");
        com.epsilon.webservices.POSPromptQuestions.AnswerChoices _updateMemberPrompts_parametersPOSPromptPOSPromptQuestionsVal1AnswerChoices = new com.epsilon.webservices.POSPromptQuestions.AnswerChoices();
        java.util.List<com.epsilon.webservices.POSPromptQuestions.AnswerChoices.AnswerOption> _updateMemberPrompts_parametersPOSPromptPOSPromptQuestionsVal1AnswerChoicesAnswerOption = new java.util.ArrayList<com.epsilon.webservices.POSPromptQuestions.AnswerChoices.AnswerOption>();
        _updateMemberPrompts_parametersPOSPromptPOSPromptQuestionsVal1AnswerChoices.getAnswerOption().addAll(_updateMemberPrompts_parametersPOSPromptPOSPromptQuestionsVal1AnswerChoicesAnswerOption);
        _updateMemberPrompts_parametersPOSPromptPOSPromptQuestionsVal1.setAnswerChoices(_updateMemberPrompts_parametersPOSPromptPOSPromptQuestionsVal1AnswerChoices);
        _updateMemberPrompts_parametersPOSPromptPOSPromptQuestionsVal1.setQuestionRuleID("QuestionRuleID-426376581");
        com.epsilon.webservices.POSPromptQuestions.FollowupQuestions _updateMemberPrompts_parametersPOSPromptPOSPromptQuestionsVal1FollowupQuestions = new com.epsilon.webservices.POSPromptQuestions.FollowupQuestions();
        java.util.List<com.epsilon.webservices.POSPromptQuestions.FollowupQuestions.FollowupQuestion> _updateMemberPrompts_parametersPOSPromptPOSPromptQuestionsVal1FollowupQuestionsFollowupQuestion = new java.util.ArrayList<com.epsilon.webservices.POSPromptQuestions.FollowupQuestions.FollowupQuestion>();
        _updateMemberPrompts_parametersPOSPromptPOSPromptQuestionsVal1FollowupQuestions.getFollowupQuestion().addAll(_updateMemberPrompts_parametersPOSPromptPOSPromptQuestionsVal1FollowupQuestionsFollowupQuestion);
        _updateMemberPrompts_parametersPOSPromptPOSPromptQuestionsVal1.setFollowupQuestions(_updateMemberPrompts_parametersPOSPromptPOSPromptQuestionsVal1FollowupQuestions);
        _updateMemberPrompts_parametersPOSPromptPOSPromptQuestions.add(_updateMemberPrompts_parametersPOSPromptPOSPromptQuestionsVal1);
        _updateMemberPrompts_parametersPOSPrompt.getPOSPromptQuestions().addAll(_updateMemberPrompts_parametersPOSPromptPOSPromptQuestions);
        _updateMemberPrompts_parameters.setPOSPrompt(_updateMemberPrompts_parametersPOSPrompt);
        com.epsilon.webservices.ArrayOfAdditionalAttribute _updateMemberPrompts_parametersAdditionalAttributes = new com.epsilon.webservices.ArrayOfAdditionalAttribute();
        java.util.List<com.epsilon.webservices.AdditionalAttribute> _updateMemberPrompts_parametersAdditionalAttributesAdditionalAttribute = new java.util.ArrayList<com.epsilon.webservices.AdditionalAttribute>();
        com.epsilon.webservices.AdditionalAttribute _updateMemberPrompts_parametersAdditionalAttributesAdditionalAttributeVal1 = new com.epsilon.webservices.AdditionalAttribute();
        _updateMemberPrompts_parametersAdditionalAttributesAdditionalAttributeVal1.setAttrName("AttrName1739160161");
        _updateMemberPrompts_parametersAdditionalAttributesAdditionalAttributeVal1.setAttrValue("AttrValue990010212");
        _updateMemberPrompts_parametersAdditionalAttributesAdditionalAttribute.add(_updateMemberPrompts_parametersAdditionalAttributesAdditionalAttributeVal1);
        _updateMemberPrompts_parametersAdditionalAttributes.getAdditionalAttribute().addAll(_updateMemberPrompts_parametersAdditionalAttributesAdditionalAttribute);
        _updateMemberPrompts_parameters.setAdditionalAttributes(_updateMemberPrompts_parametersAdditionalAttributes);
        com.epsilon.webservices.AdditionalResponseInfo _updateMemberPrompts_parametersAdditionalResponseInfo = new com.epsilon.webservices.AdditionalResponseInfo();
        java.util.List<com.epsilon.webservices.Info> _updateMemberPrompts_parametersAdditionalResponseInfoInfo = new java.util.ArrayList<com.epsilon.webservices.Info>();
        com.epsilon.webservices.Info _updateMemberPrompts_parametersAdditionalResponseInfoInfoVal1 = new com.epsilon.webservices.Info();
        _updateMemberPrompts_parametersAdditionalResponseInfoInfoVal1.setKey("Key1057189213");
        _updateMemberPrompts_parametersAdditionalResponseInfoInfoVal1.setValue("Value1894715047");
        _updateMemberPrompts_parametersAdditionalResponseInfoInfo.add(_updateMemberPrompts_parametersAdditionalResponseInfoInfoVal1);
        _updateMemberPrompts_parametersAdditionalResponseInfo.getInfo().addAll(_updateMemberPrompts_parametersAdditionalResponseInfoInfo);
        _updateMemberPrompts_parameters.setAdditionalResponseInfo(_updateMemberPrompts_parametersAdditionalResponseInfo);
        com.epsilon.webservices.GetMemberPrompt _updateMemberPrompts_parametersGetMemberPrompt = new com.epsilon.webservices.GetMemberPrompt();
        com.epsilon.webservices.ArrayOfPromptGroup _updateMemberPrompts_parametersGetMemberPromptPromptGroups = new com.epsilon.webservices.ArrayOfPromptGroup();
        java.util.List<com.epsilon.webservices.PromptGroup> _updateMemberPrompts_parametersGetMemberPromptPromptGroupsPromptGroup = new java.util.ArrayList<com.epsilon.webservices.PromptGroup>();
        _updateMemberPrompts_parametersGetMemberPromptPromptGroups.getPromptGroup().addAll(_updateMemberPrompts_parametersGetMemberPromptPromptGroupsPromptGroup);
        _updateMemberPrompts_parametersGetMemberPrompt.setPromptGroups(_updateMemberPrompts_parametersGetMemberPromptPromptGroups);
        _updateMemberPrompts_parameters.setGetMemberPrompt(_updateMemberPrompts_parametersGetMemberPrompt);
        com.epsilon.webservices.UpdateMemberPromptsResponse _updateMemberPrompts__return = port.updateMemberPrompts(_updateMemberPrompts_parameters);
        System.out.println("updateMemberPrompts.result=" + _updateMemberPrompts__return);


        }
        {
        System.out.println("Invoking getPartnerEnrollmentDetails...");
        java.lang.String _getPartnerEnrollmentDetails_memberNumber = "_getPartnerEnrollmentDetails_memberNumber-366517619";
        java.lang.String _getPartnerEnrollmentDetails_source = "_getPartnerEnrollmentDetails_source546644763";
        java.lang.String _getPartnerEnrollmentDetails_requestorID = "_getPartnerEnrollmentDetails_requestorID-1807484229";
        java.lang.String _getPartnerEnrollmentDetails_storeNumber = "_getPartnerEnrollmentDetails_storeNumber-1394836527";
        java.lang.String _getPartnerEnrollmentDetails_registerNumber = "_getPartnerEnrollmentDetails_registerNumber503250889";
        java.lang.String _getPartnerEnrollmentDetails_transactionNumber = "_getPartnerEnrollmentDetails_transactionNumber767496664";
        java.lang.String _getPartnerEnrollmentDetails_associateID = "_getPartnerEnrollmentDetails_associateID-1040023861";
        java.lang.String _getPartnerEnrollmentDetails_date = "_getPartnerEnrollmentDetails_date1812554695";
        java.lang.String _getPartnerEnrollmentDetails_time = "_getPartnerEnrollmentDetails_time1287491997";
        java.lang.String _getPartnerEnrollmentDetails_aliasName = "_getPartnerEnrollmentDetails_aliasName-1420865094";
        java.lang.String _getPartnerEnrollmentDetails_messageVersion = "_getPartnerEnrollmentDetails_messageVersion-1701651689";
        com.epsilon.webservices.GetPartnerEnrollmentDetailsResponse.GetPartnerEnrollmentDetailsResult _getPartnerEnrollmentDetails__return = port.getPartnerEnrollmentDetails(_getPartnerEnrollmentDetails_memberNumber, _getPartnerEnrollmentDetails_source, _getPartnerEnrollmentDetails_requestorID, _getPartnerEnrollmentDetails_storeNumber, _getPartnerEnrollmentDetails_registerNumber, _getPartnerEnrollmentDetails_transactionNumber, _getPartnerEnrollmentDetails_associateID, _getPartnerEnrollmentDetails_date, _getPartnerEnrollmentDetails_time, _getPartnerEnrollmentDetails_aliasName, _getPartnerEnrollmentDetails_messageVersion);
        System.out.println("getPartnerEnrollmentDetails.result=" + _getPartnerEnrollmentDetails__return);


        }
        {
        System.out.println("Invoking getMemberPrompts...");
        java.lang.String _getMemberPrompts_memberNumber = "_getMemberPrompts_memberNumber1233038833";
        java.lang.String _getMemberPrompts_messageVersion = "_getMemberPrompts_messageVersion1918865744";
        java.lang.String _getMemberPrompts_requestorID = "_getMemberPrompts_requestorID-32613066";
        com.epsilon.webservices.ArrayOfPromptGroup _getMemberPrompts_promptGroups = new com.epsilon.webservices.ArrayOfPromptGroup();
        java.util.List<com.epsilon.webservices.PromptGroup> _getMemberPrompts_promptGroupsPromptGroup = new java.util.ArrayList<com.epsilon.webservices.PromptGroup>();
        com.epsilon.webservices.PromptGroup _getMemberPrompts_promptGroupsPromptGroupVal1 = new com.epsilon.webservices.PromptGroup();
        _getMemberPrompts_promptGroupsPromptGroupVal1.setMaxPOSPrompt("MaxPOSPrompt1296114568");
        _getMemberPrompts_promptGroupsPromptGroupVal1.setPromptGroupName("PromptGroupName1642252197");
        _getMemberPrompts_promptGroupsPromptGroup.add(_getMemberPrompts_promptGroupsPromptGroupVal1);
        _getMemberPrompts_promptGroups.getPromptGroup().addAll(_getMemberPrompts_promptGroupsPromptGroup);
        javax.xml.datatype.XMLGregorianCalendar _getMemberPrompts_currentDate = javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2017-04-14T18:02:39.580+05:30");
        java.lang.String _getMemberPrompts_currentTime = "_getMemberPrompts_currentTime-1250056783";
        java.lang.String _getMemberPrompts_storeNumber = "_getMemberPrompts_storeNumber-443293290";
        java.lang.String _getMemberPrompts_terminal = "_getMemberPrompts_terminal-1413004865";
        java.lang.String _getMemberPrompts_includeAnswers = "_getMemberPrompts_includeAnswers-276034118";
        com.epsilon.webservices.GetMemberPromptsResponse.GetMemberPromptsResult _getMemberPrompts__return = port.getMemberPrompts(_getMemberPrompts_memberNumber, _getMemberPrompts_messageVersion, _getMemberPrompts_requestorID, _getMemberPrompts_promptGroups, _getMemberPrompts_currentDate, _getMemberPrompts_currentTime, _getMemberPrompts_storeNumber, _getMemberPrompts_terminal, _getMemberPrompts_includeAnswers);
        System.out.println("getMemberPrompts.result=" + _getMemberPrompts__return);


        }
        {
        System.out.println("Invoking updateMemberExtendedProfile...");
        java.lang.String _updateMemberExtendedProfile_memberNumber = "_updateMemberExtendedProfile_memberNumber309235476";
        com.epsilon.webservices.ArrayOfExtendedProfilePreference _updateMemberExtendedProfile_extendedProfilePreferences = new com.epsilon.webservices.ArrayOfExtendedProfilePreference();
        java.util.List<com.epsilon.webservices.ExtendedProfilePreference2> _updateMemberExtendedProfile_extendedProfilePreferencesExtendedProfilePreference = new java.util.ArrayList<com.epsilon.webservices.ExtendedProfilePreference2>();
        com.epsilon.webservices.ExtendedProfilePreference2 _updateMemberExtendedProfile_extendedProfilePreferencesExtendedProfilePreferenceVal1 = new com.epsilon.webservices.ExtendedProfilePreference2();
        _updateMemberExtendedProfile_extendedProfilePreferencesExtendedProfilePreferenceVal1.setPreferenceCode("PreferenceCode-546057052");
        _updateMemberExtendedProfile_extendedProfilePreferencesExtendedProfilePreferenceVal1.setPreferenceResponseCode("PreferenceResponseCode-1119546");
        _updateMemberExtendedProfile_extendedProfilePreferencesExtendedProfilePreferenceVal1.setPreferenceValue("PreferenceValue1851243354");
        _updateMemberExtendedProfile_extendedProfilePreferencesExtendedProfilePreference.add(_updateMemberExtendedProfile_extendedProfilePreferencesExtendedProfilePreferenceVal1);
        _updateMemberExtendedProfile_extendedProfilePreferences.getExtendedProfilePreference().addAll(_updateMemberExtendedProfile_extendedProfilePreferencesExtendedProfilePreference);
        com.epsilon.webservices.UpdateMemberExtendedProfileResponse.UpdateMemberExtendedProfileResult _updateMemberExtendedProfile__return = port.updateMemberExtendedProfile(_updateMemberExtendedProfile_memberNumber, _updateMemberExtendedProfile_extendedProfilePreferences);
        System.out.println("updateMemberExtendedProfile.result=" + _updateMemberExtendedProfile__return);


        }
        {
        System.out.println("Invoking getMemberAffinitySubscriptions...");
        java.lang.String _getMemberAffinitySubscriptions_memberNumber = "_getMemberAffinitySubscriptions_memberNumber-1144172645";
        java.lang.String _getMemberAffinitySubscriptions_messageVersion = "_getMemberAffinitySubscriptions_messageVersion-549801566";
        java.lang.String _getMemberAffinitySubscriptions_requestorID = "_getMemberAffinitySubscriptions_requestorID-911553817";
        java.lang.String _getMemberAffinitySubscriptions_storeNumber = "_getMemberAffinitySubscriptions_storeNumber1476424220";
        java.lang.String _getMemberAffinitySubscriptions_terminal = "_getMemberAffinitySubscriptions_terminal-737995850";
        java.lang.String _getMemberAffinitySubscriptions_associateId = "_getMemberAffinitySubscriptions_associateId112988540";
        java.lang.String _getMemberAffinitySubscriptions_currentDate = "_getMemberAffinitySubscriptions_currentDate1027345372";
        java.lang.String _getMemberAffinitySubscriptions_currentTime = "_getMemberAffinitySubscriptions_currentTime1909239634";
        com.epsilon.webservices.GetMemberAffinitySubscriptionsResponse.GetMemberAffinitySubscriptionsResult _getMemberAffinitySubscriptions__return = port.getMemberAffinitySubscriptions(_getMemberAffinitySubscriptions_memberNumber, _getMemberAffinitySubscriptions_messageVersion, _getMemberAffinitySubscriptions_requestorID, _getMemberAffinitySubscriptions_storeNumber, _getMemberAffinitySubscriptions_terminal, _getMemberAffinitySubscriptions_associateId, _getMemberAffinitySubscriptions_currentDate, _getMemberAffinitySubscriptions_currentTime);
        System.out.println("getMemberAffinitySubscriptions.result=" + _getMemberAffinitySubscriptions__return);


        }
        {
        System.out.println("Invoking getMemberAuditLookup...");
        java.lang.String _getMemberAuditLookup_memberNumber = "_getMemberAuditLookup_memberNumber1063821036";
        java.lang.String _getMemberAuditLookup_messageVersion = "_getMemberAuditLookup_messageVersion1656099392";
        java.lang.String _getMemberAuditLookup_auditType = "_getMemberAuditLookup_auditType1520933160";
        java.lang.String _getMemberAuditLookup_requestorID = "_getMemberAuditLookup_requestorID-383860066";
        java.lang.String _getMemberAuditLookup_startDateTime = "_getMemberAuditLookup_startDateTime-846511910";
        java.lang.String _getMemberAuditLookup_endDateTime = "_getMemberAuditLookup_endDateTime-922795571";
        com.epsilon.webservices.GetMemberAuditLookupResponse.GetMemberAuditResult _getMemberAuditLookup__return = port.getMemberAuditLookup(_getMemberAuditLookup_memberNumber, _getMemberAuditLookup_messageVersion, _getMemberAuditLookup_auditType, _getMemberAuditLookup_requestorID, _getMemberAuditLookup_startDateTime, _getMemberAuditLookup_endDateTime);
        System.out.println("getMemberAuditLookup.result=" + _getMemberAuditLookup__return);


        }
        {
        System.out.println("Invoking getMemberLevel...");
        java.lang.String _getMemberLevel_memberNumber = "_getMemberLevel_memberNumber1041286851";
        java.lang.String _getMemberLevel_messageVersion = "_getMemberLevel_messageVersion-755689013";
        java.lang.String _getMemberLevel_requestorID = "_getMemberLevel_requestorID-2040686980";
        com.epsilon.webservices.GetMemberLevelResponse.GetMemberLevelResult _getMemberLevel__return = port.getMemberLevel(_getMemberLevel_memberNumber, _getMemberLevel_messageVersion, _getMemberLevel_requestorID);
        System.out.println("getMemberLevel.result=" + _getMemberLevel__return);


        }
        {
        System.out.println("Invoking getMemberTargetedOffers...");
        com.epsilon.webservices.GetMemberTargetedOffers _getMemberTargetedOffers_parameters = new com.epsilon.webservices.GetMemberTargetedOffers();
        _getMemberTargetedOffers_parameters.setMemberNumber("MemberNumber-1499725878");
        _getMemberTargetedOffers_parameters.setStartDTTM("StartDTTM-104514052");
        _getMemberTargetedOffers_parameters.setEndDTTM("EndDTTM-738003495");
        _getMemberTargetedOffers_parameters.setLanguagePreference("LanguagePreference-1243833429");
        _getMemberTargetedOffers_parameters.setMessageVersion("MessageVersion-529298726");
        _getMemberTargetedOffers_parameters.setRequestorID("RequestorID824202395");
        _getMemberTargetedOffers_parameters.setOfferNumber("OfferNumber-520692391");
        _getMemberTargetedOffers_parameters.setCouponNumber("CouponNumber1379258598");
        _getMemberTargetedOffers_parameters.setLiveDate("LiveDate1613507853");
        java.lang.Object _getMemberTargetedOffers__return = port.getMemberTargetedOffers(_getMemberTargetedOffers_parameters);
        System.out.println("getMemberTargetedOffers.result=" + _getMemberTargetedOffers__return);


        }
        {
        System.out.println("Invoking validateMember...");
        java.lang.String _validateMember_memberNumber = "_validateMember_memberNumber1965699653";
        java.lang.String _validateMember_firstName = "_validateMember_firstName-637181957";
        java.lang.String _validateMember_lastName = "_validateMember_lastName-2046592684";
        java.lang.String _validateMember_messageVersion = "_validateMember_messageVersion-1288094823";
        com.epsilon.webservices.ValidateMemberResponse.ValidateMemberResult _validateMember__return = port.validateMember(_validateMember_memberNumber, _validateMember_firstName, _validateMember_lastName, _validateMember_messageVersion);
        System.out.println("validateMember.result=" + _validateMember__return);


        }
        {
        System.out.println("Invoking registerMember...");
        java.lang.String _registerMember_memberNumber = "_registerMember_memberNumber1664706596";
        java.lang.String _registerMember_emailAddress = "_registerMember_emailAddress-953942171";
        java.lang.String _registerMember_emailValidation = "_registerMember_emailValidation-1107282679";
        java.lang.String _registerMember_zipCode = "_registerMember_zipCode1805442505";
        java.lang.String _registerMember_zipCodeExtension = "_registerMember_zipCodeExtension-249307450";
        java.lang.String _registerMember_shcAssociateInd = "_registerMember_shcAssociateInd1154044229";
        java.lang.String _registerMember_messageVersion = "_registerMember_messageVersion1474526088";
        java.lang.String _registerMember_currentDate = "_registerMember_currentDate327864116";
        java.lang.String _registerMember_currentTime = "_registerMember_currentTime-2081014203";
        com.epsilon.webservices.RegisterMemberResponse.RegisterMemberResult _registerMember__return = port.registerMember(_registerMember_memberNumber, _registerMember_emailAddress, _registerMember_emailValidation, _registerMember_zipCode, _registerMember_zipCodeExtension, _registerMember_shcAssociateInd, _registerMember_messageVersion, _registerMember_currentDate, _registerMember_currentTime);
        System.out.println("registerMember.result=" + _registerMember__return);


        }
        {
        System.out.println("Invoking createPartnerEnrollmentDetails...");
        java.lang.String _createPartnerEnrollmentDetails_memberUniqueId = "_createPartnerEnrollmentDetails_memberUniqueId818196137";
        java.lang.String _createPartnerEnrollmentDetails_memberNumber = "_createPartnerEnrollmentDetails_memberNumber2066528904";
        java.lang.String _createPartnerEnrollmentDetails_registrationUniqueId = "_createPartnerEnrollmentDetails_registrationUniqueId1312330034";
        java.lang.String _createPartnerEnrollmentDetails_serviceRegistrationNumber = "_createPartnerEnrollmentDetails_serviceRegistrationNumber603403432";
        java.lang.String _createPartnerEnrollmentDetails_enrollmentDate = "_createPartnerEnrollmentDetails_enrollmentDate1561396365";
        java.lang.String _createPartnerEnrollmentDetails_unenrollmentDate = "_createPartnerEnrollmentDetails_unenrollmentDate1153113338";
        java.lang.String _createPartnerEnrollmentDetails_mobileNumber = "_createPartnerEnrollmentDetails_mobileNumber-1275412596";
        java.lang.String _createPartnerEnrollmentDetails_registrationIndicator = "_createPartnerEnrollmentDetails_registrationIndicator-1121042807";
        java.lang.String _createPartnerEnrollmentDetails_enrollmentIndicator = "_createPartnerEnrollmentDetails_enrollmentIndicator1353423285";
        java.lang.String _createPartnerEnrollmentDetails_source = "_createPartnerEnrollmentDetails_source258752075";
        java.lang.String _createPartnerEnrollmentDetails_serviceEnrollmentDate = "_createPartnerEnrollmentDetails_serviceEnrollmentDate-1919517582";
        java.lang.String _createPartnerEnrollmentDetails_serviceUnenrollmentDate = "_createPartnerEnrollmentDetails_serviceUnenrollmentDate620484087";
        java.lang.String _createPartnerEnrollmentDetails_storeNumber = "_createPartnerEnrollmentDetails_storeNumber1437654461";
        java.lang.String _createPartnerEnrollmentDetails_requestorID = "_createPartnerEnrollmentDetails_requestorID-1763947034";
        java.lang.String _createPartnerEnrollmentDetails_registerNumber = "_createPartnerEnrollmentDetails_registerNumber1974020017";
        java.lang.String _createPartnerEnrollmentDetails_transactionNumber = "_createPartnerEnrollmentDetails_transactionNumber-37016675";
        java.lang.String _createPartnerEnrollmentDetails_associateID = "_createPartnerEnrollmentDetails_associateID-40987282";
        java.lang.String _createPartnerEnrollmentDetails_date = "_createPartnerEnrollmentDetails_date168191740";
        java.lang.String _createPartnerEnrollmentDetails_time = "_createPartnerEnrollmentDetails_time913823012";
        java.lang.String _createPartnerEnrollmentDetails_aliasName = "_createPartnerEnrollmentDetails_aliasName1472450083";
        java.lang.String _createPartnerEnrollmentDetails_messageVersion = "_createPartnerEnrollmentDetails_messageVersion826013778";
        com.epsilon.webservices.CreatePartnerEnrollmentDetailsResponse.CreatePartnerEnrollmentDetailsResult _createPartnerEnrollmentDetails__return = port.createPartnerEnrollmentDetails(_createPartnerEnrollmentDetails_memberUniqueId, _createPartnerEnrollmentDetails_memberNumber, _createPartnerEnrollmentDetails_registrationUniqueId, _createPartnerEnrollmentDetails_serviceRegistrationNumber, _createPartnerEnrollmentDetails_enrollmentDate, _createPartnerEnrollmentDetails_unenrollmentDate, _createPartnerEnrollmentDetails_mobileNumber, _createPartnerEnrollmentDetails_registrationIndicator, _createPartnerEnrollmentDetails_enrollmentIndicator, _createPartnerEnrollmentDetails_source, _createPartnerEnrollmentDetails_serviceEnrollmentDate, _createPartnerEnrollmentDetails_serviceUnenrollmentDate, _createPartnerEnrollmentDetails_storeNumber, _createPartnerEnrollmentDetails_requestorID, _createPartnerEnrollmentDetails_registerNumber, _createPartnerEnrollmentDetails_transactionNumber, _createPartnerEnrollmentDetails_associateID, _createPartnerEnrollmentDetails_date, _createPartnerEnrollmentDetails_time, _createPartnerEnrollmentDetails_aliasName, _createPartnerEnrollmentDetails_messageVersion);
        System.out.println("createPartnerEnrollmentDetails.result=" + _createPartnerEnrollmentDetails__return);


        }
        {
        System.out.println("Invoking getRewardBalance...");
        java.lang.String _getRewardBalance_requestorID = "_getRewardBalance_requestorID-97771385";
        java.lang.String _getRewardBalance_storeNumber = "_getRewardBalance_storeNumber-912574869";
        java.lang.String _getRewardBalance_currentDate = "_getRewardBalance_currentDate-1964776492";
        java.lang.String _getRewardBalance_currentTime = "_getRewardBalance_currentTime-111307895";
        java.lang.String _getRewardBalance_associateID = "_getRewardBalance_associateID-1017669237";
        java.lang.String _getRewardBalance_memberNumber = "_getRewardBalance_memberNumber-183243813";
        java.lang.String _getRewardBalance_pointType = "_getRewardBalance_pointType-1840129408";
        java.lang.String _getRewardBalance_messageVersion = "_getRewardBalance_messageVersion-1572600354";
        com.epsilon.webservices.GetRewardBalanceResponse.GetRewardBalanceResult _getRewardBalance__return = port.getRewardBalance(_getRewardBalance_requestorID, _getRewardBalance_storeNumber, _getRewardBalance_currentDate, _getRewardBalance_currentTime, _getRewardBalance_associateID, _getRewardBalance_memberNumber, _getRewardBalance_pointType, _getRewardBalance_messageVersion);
        System.out.println("getRewardBalance.result=" + _getRewardBalance__return);


        }
        {
        System.out.println("Invoking getMemberLookup...");
        java.lang.String _getMemberLookup_messageVersion = "_getMemberLookup_messageVersion2000389534";
        java.lang.String _getMemberLookup_memberNumber = "_getMemberLookup_memberNumber-1717669707";
        java.lang.String _getMemberLookup_emailAddress = "_getMemberLookup_emailAddress-1539395165";
        java.lang.String _getMemberLookup_id = "_getMemberLookup_id1192356116";
        java.lang.String _getMemberLookup_type = "_getMemberLookup_type493419947";
        java.lang.String _getMemberLookup_phoneNumber = "_getMemberLookup_phoneNumber-807594343";
        java.lang.String _getMemberLookup_storeNumber = "_getMemberLookup_storeNumber-1147125050";
        java.lang.String _getMemberLookup_terminal = "_getMemberLookup_terminal1195801734";
        java.lang.String _getMemberLookup_requestorID = "_getMemberLookup_requestorID-318039822";
        java.lang.String _getMemberLookup_searchType = "_getMemberLookup_searchType-1872640964";
        java.lang.String _getMemberLookup_currentDate = "_getMemberLookup_currentDate-878891995";
        java.lang.String _getMemberLookup_currentTime = "_getMemberLookup_currentTime-1481644818";
        java.lang.String _getMemberLookup_maxRecords = "_getMemberLookup_maxRecords-388722094";
        java.lang.String _getMemberLookup_maxPOSPrompt = "_getMemberLookup_maxPOSPrompt-318215336";
        com.epsilon.webservices.ArrayOfPromptGroup _getMemberLookup_promptGroups = new com.epsilon.webservices.ArrayOfPromptGroup();
        java.util.List<com.epsilon.webservices.PromptGroup> _getMemberLookup_promptGroupsPromptGroup = new java.util.ArrayList<com.epsilon.webservices.PromptGroup>();
        com.epsilon.webservices.PromptGroup _getMemberLookup_promptGroupsPromptGroupVal1 = new com.epsilon.webservices.PromptGroup();
        _getMemberLookup_promptGroupsPromptGroupVal1.setMaxPOSPrompt("MaxPOSPrompt-973454959");
        _getMemberLookup_promptGroupsPromptGroupVal1.setPromptGroupName("PromptGroupName-324987516");
        _getMemberLookup_promptGroupsPromptGroup.add(_getMemberLookup_promptGroupsPromptGroupVal1);
        _getMemberLookup_promptGroups.getPromptGroup().addAll(_getMemberLookup_promptGroupsPromptGroup);
        java.lang.String _getMemberLookup_firstName = "_getMemberLookup_firstName1842085322";
        java.lang.String _getMemberLookup_lastName = "_getMemberLookup_lastName598632932";
        java.lang.String _getMemberLookup_zipCode = "_getMemberLookup_zipCode141797271";
        com.epsilon.webservices.GetMemberLookupResponse.GetMemberLookupResult _getMemberLookup__return = port.getMemberLookup(_getMemberLookup_messageVersion, _getMemberLookup_memberNumber, _getMemberLookup_emailAddress, _getMemberLookup_id, _getMemberLookup_type, _getMemberLookup_phoneNumber, _getMemberLookup_storeNumber, _getMemberLookup_terminal, _getMemberLookup_requestorID, _getMemberLookup_searchType, _getMemberLookup_currentDate, _getMemberLookup_currentTime, _getMemberLookup_maxRecords, _getMemberLookup_maxPOSPrompt, _getMemberLookup_promptGroups, _getMemberLookup_firstName, _getMemberLookup_lastName, _getMemberLookup_zipCode);
        System.out.println("getMemberLookup.result=" + _getMemberLookup__return);


        }
        {
        System.out.println("Invoking getMemberExtendedProfile...");
        java.lang.String _getMemberExtendedProfile_memberNumber = "_getMemberExtendedProfile_memberNumber-193677750";
        java.lang.String _getMemberExtendedProfile_messageVersion = "_getMemberExtendedProfile_messageVersion90657341";
        com.epsilon.webservices.GetMemberExtendedProfileResponse.GetMemberExtendedProfileResult _getMemberExtendedProfile__return = port.getMemberExtendedProfile(_getMemberExtendedProfile_memberNumber, _getMemberExtendedProfile_messageVersion);
        System.out.println("getMemberExtendedProfile.result=" + _getMemberExtendedProfile__return);


        }

        System.exit(0);
    }

}
