package com.epsilon.webservices;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.1.11
 * 2017-04-14T18:02:39.615+05:30
 * Generated source version: 3.1.11
 * 
 */
@WebService(targetNamespace = "http://www.epsilon.com/webservices/", name = "ProfileSoap")
@XmlSeeAlso({ObjectFactory.class, com.epsilon.webservices.common.ObjectFactory.class})
public interface ProfileSoap {

    @WebMethod(operationName = "MemberReplaceCard", action = "http://www.epsilon.com/webservices/MemberReplaceCard")
    @RequestWrapper(localName = "MemberReplaceCard", targetNamespace = "http://www.epsilon.com/webservices/", className = "com.epsilon.webservices.MemberReplaceCard")
    @ResponseWrapper(localName = "MemberReplaceCardResponse", targetNamespace = "http://www.epsilon.com/webservices/", className = "com.epsilon.webservices.MemberReplaceCardResponse")
    @WebResult(name = "MemberReplaceCardResult", targetNamespace = "http://www.epsilon.com/webservices/")
    public com.epsilon.webservices.MemberReplaceCardResponse.MemberReplaceCardResult memberReplaceCard(
        @WebParam(name = "OriginalMemberNumber", targetNamespace = "http://www.epsilon.com/webservices/")
        java.lang.String originalMemberNumber,
        @WebParam(name = "NewMemberNumber", targetNamespace = "http://www.epsilon.com/webservices/")
        java.lang.String newMemberNumber,
        @WebParam(name = "MessageVersion", targetNamespace = "http://www.epsilon.com/webservices/")
        java.lang.String messageVersion
    );

    @WebMethod(operationName = "UpdateMemberPrimaryProfile", action = "http://www.epsilon.com/webservices/UpdateMemberPrimaryProfile")
    @RequestWrapper(localName = "UpdateMemberPrimaryProfile", targetNamespace = "http://www.epsilon.com/webservices/", className = "com.epsilon.webservices.UpdateMemberPrimaryProfile")
    @ResponseWrapper(localName = "UpdateMemberPrimaryProfileResponse", targetNamespace = "http://www.epsilon.com/webservices/", className = "com.epsilon.webservices.UpdateMemberPrimaryProfileResponse")
    @WebResult(name = "UpdateMemberPrimaryProfileResult", targetNamespace = "http://www.epsilon.com/webservices/")
    public com.epsilon.webservices.UpdateMemberPrimaryProfileResponse.UpdateMemberPrimaryProfileResult updateMemberPrimaryProfile(
        @WebParam(name = "MessageVersion", targetNamespace = "http://www.epsilon.com/webservices/")
        java.lang.String messageVersion,
        @WebParam(name = "MemberNumber", targetNamespace = "http://www.epsilon.com/webservices/")
        java.lang.String memberNumber,
        @WebParam(name = "RequestorID", targetNamespace = "http://www.epsilon.com/webservices/")
        java.lang.String requestorID,
        @WebParam(name = "StoreNumber", targetNamespace = "http://www.epsilon.com/webservices/")
        java.lang.String storeNumber,
        @WebParam(name = "Terminal", targetNamespace = "http://www.epsilon.com/webservices/")
        java.lang.String terminal,
        @WebParam(name = "CurrentDate", targetNamespace = "http://www.epsilon.com/webservices/")
        java.lang.String currentDate,
        @WebParam(name = "CurrentTime", targetNamespace = "http://www.epsilon.com/webservices/")
        java.lang.String currentTime,
        @WebParam(name = "Prefix", targetNamespace = "http://www.epsilon.com/webservices/")
        java.lang.String prefix,
        @WebParam(name = "FirstName", targetNamespace = "http://www.epsilon.com/webservices/")
        java.lang.String firstName,
        @WebParam(name = "LastName", targetNamespace = "http://www.epsilon.com/webservices/")
        java.lang.String lastName,
        @WebParam(name = "MiddleInitial", targetNamespace = "http://www.epsilon.com/webservices/")
        java.lang.String middleInitial,
        @WebParam(name = "Suffix", targetNamespace = "http://www.epsilon.com/webservices/")
        java.lang.String suffix,
        @WebParam(name = "AuthFirstName", targetNamespace = "http://www.epsilon.com/webservices/")
        java.lang.String authFirstName,
        @WebParam(name = "AuthLastName", targetNamespace = "http://www.epsilon.com/webservices/")
        java.lang.String authLastName,
        @WebParam(name = "ClubDNPStatus", targetNamespace = "http://www.epsilon.com/webservices/")
        java.lang.String clubDNPStatus,
        @WebParam(name = "ClubMembershipUpdatedBy", targetNamespace = "http://www.epsilon.com/webservices/")
        java.lang.String clubMembershipUpdatedBy,
        @WebParam(name = "DateUpdated", targetNamespace = "http://www.epsilon.com/webservices/")
        java.lang.String dateUpdated,
        @WebParam(name = "DOB", targetNamespace = "http://www.epsilon.com/webservices/")
        java.lang.String dob,
        @WebParam(name = "TestAccount", targetNamespace = "http://www.epsilon.com/webservices/")
        java.lang.String testAccount,
        @WebParam(name = "AccountStatus", targetNamespace = "http://www.epsilon.com/webservices/")
        java.lang.String accountStatus,
        @WebParam(name = "StatusChangeReasonCode", targetNamespace = "http://www.epsilon.com/webservices/")
        java.lang.String statusChangeReasonCode,
        @WebParam(name = "SHCAssociateInd", targetNamespace = "http://www.epsilon.com/webservices/")
        java.lang.String shcAssociateInd,
        @WebParam(name = "WirelessPermissionFlag", targetNamespace = "http://www.epsilon.com/webservices/")
        java.lang.String wirelessPermissionFlag,
        @WebParam(name = "LanguagePreference", targetNamespace = "http://www.epsilon.com/webservices/")
        java.lang.String languagePreference,
        @WebParam(name = "Address1", targetNamespace = "http://www.epsilon.com/webservices/")
        java.lang.String address1,
        @WebParam(name = "Address2", targetNamespace = "http://www.epsilon.com/webservices/")
        java.lang.String address2,
        @WebParam(name = "City", targetNamespace = "http://www.epsilon.com/webservices/")
        java.lang.String city,
        @WebParam(name = "State", targetNamespace = "http://www.epsilon.com/webservices/")
        java.lang.String state,
        @WebParam(name = "ZipCode", targetNamespace = "http://www.epsilon.com/webservices/")
        java.lang.String zipCode,
        @WebParam(name = "ZipCodeExtension", targetNamespace = "http://www.epsilon.com/webservices/")
        java.lang.String zipCodeExtension,
        @WebParam(name = "CountryCode", targetNamespace = "http://www.epsilon.com/webservices/")
        java.lang.String countryCode,
        @WebParam(name = "EmailAddress", targetNamespace = "http://www.epsilon.com/webservices/")
        java.lang.String emailAddress,
        @WebParam(name = "EmailValidation", targetNamespace = "http://www.epsilon.com/webservices/")
        java.lang.String emailValidation,
        @WebParam(name = "ClubEmailOptStatus", targetNamespace = "http://www.epsilon.com/webservices/")
        java.lang.String clubEmailOptStatus,
        @WebParam(name = "TnCStatus", targetNamespace = "http://www.epsilon.com/webservices/")
        java.lang.String tnCStatus,
        @WebParam(name = "TnCVersion", targetNamespace = "http://www.epsilon.com/webservices/")
        java.lang.String tnCVersion,
        @WebParam(name = "Charity", targetNamespace = "http://www.epsilon.com/webservices/")
        java.lang.String charity,
        @WebParam(name = "ProfileUpdate", targetNamespace = "http://www.epsilon.com/webservices/")
        java.lang.String profileUpdate,
        @WebParam(name = "POSPrompt", targetNamespace = "http://www.epsilon.com/webservices/")
        com.epsilon.webservices.ArrayOfPOSPrompt posPrompt,
        @WebParam(name = "AdditionalAttributes", targetNamespace = "http://www.epsilon.com/webservices/")
        com.epsilon.webservices.AdditionalAttributes additionalAttributes,
        @WebParam(name = "PhoneNumbers", targetNamespace = "http://www.epsilon.com/webservices/")
        com.epsilon.webservices.ArrayOfPhone phoneNumbers,
        @WebParam(name = "Affinities", targetNamespace = "http://www.epsilon.com/webservices/")
        com.epsilon.webservices.ArrayOfAffinity affinities,
        @WebParam(name = "Attributes", targetNamespace = "http://www.epsilon.com/webservices/")
        com.epsilon.webservices.ArrayOfAttr attributes
    );

    @WebMethod(operationName = "DateTimeOnServer", action = "http://www.epsilon.com/webservices/DateTimeOnServer")
    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
    @WebResult(name = "DateTimeOnServerResponse", targetNamespace = "http://www.epsilon.com/webservices/", partName = "parameters")
    public java.lang.Object dateTimeOnServer(
        @WebParam(partName = "parameters", name = "DateTimeOnServer", targetNamespace = "http://www.epsilon.com/webservices/")
        java.lang.Object parameters
    );

    @WebMethod(operationName = "UpdateMemberPin", action = "http://www.epsilon.com/webservices/UpdateMemberPin")
    @RequestWrapper(localName = "UpdateMemberPin", targetNamespace = "http://www.epsilon.com/webservices/", className = "com.epsilon.webservices.UpdateMemberPin")
    @ResponseWrapper(localName = "UpdateMemberPinResponse", targetNamespace = "http://www.epsilon.com/webservices/", className = "com.epsilon.webservices.UpdateMemberPinResponse")
    @WebResult(name = "UpdateMemberPinResult", targetNamespace = "http://www.epsilon.com/webservices/")
    public com.epsilon.webservices.UpdateMemberPinResponse.UpdateMemberPinResult updateMemberPin(
        @WebParam(name = "MessageVersion", targetNamespace = "http://www.epsilon.com/webservices/")
        java.lang.String messageVersion,
        @WebParam(name = "MemberNumber", targetNamespace = "http://www.epsilon.com/webservices/")
        java.lang.String memberNumber,
        @WebParam(name = "RequestorID", targetNamespace = "http://www.epsilon.com/webservices/")
        java.lang.String requestorID,
        @WebParam(name = "CurrentDate", targetNamespace = "http://www.epsilon.com/webservices/")
        java.lang.String currentDate,
        @WebParam(name = "CurrentTime", targetNamespace = "http://www.epsilon.com/webservices/")
        java.lang.String currentTime,
        @WebParam(name = "PinNumber", targetNamespace = "http://www.epsilon.com/webservices/")
        java.lang.String pinNumber
    );

    @WebMethod(operationName = "UpdateMemberEmail", action = "http://www.epsilon.com/webservices/UpdateMemberEmail")
    @RequestWrapper(localName = "UpdateMemberEmail", targetNamespace = "http://www.epsilon.com/webservices/", className = "com.epsilon.webservices.UpdateMemberEmail")
    @ResponseWrapper(localName = "UpdateMemberEmailResponse", targetNamespace = "http://www.epsilon.com/webservices/", className = "com.epsilon.webservices.UpdateMemberEmailResponse")
    @WebResult(name = "UpdateMemberEmailResult", targetNamespace = "http://www.epsilon.com/webservices/")
    public com.epsilon.webservices.UpdateMemberEmailResponse.UpdateMemberEmailResult updateMemberEmail(
        @WebParam(name = "MessageVersion", targetNamespace = "http://www.epsilon.com/webservices/")
        java.lang.String messageVersion,
        @WebParam(name = "MemberNumber", targetNamespace = "http://www.epsilon.com/webservices/")
        java.lang.String memberNumber,
        @WebParam(name = "RequestorID", targetNamespace = "http://www.epsilon.com/webservices/")
        java.lang.String requestorID,
        @WebParam(name = "CurrentDate", targetNamespace = "http://www.epsilon.com/webservices/")
        java.lang.String currentDate,
        @WebParam(name = "CurrentTime", targetNamespace = "http://www.epsilon.com/webservices/")
        java.lang.String currentTime,
        @WebParam(name = "EmailAddress", targetNamespace = "http://www.epsilon.com/webservices/")
        java.lang.String emailAddress,
        @WebParam(name = "EmailValidation", targetNamespace = "http://www.epsilon.com/webservices/")
        java.lang.String emailValidation,
        @WebParam(name = "ClubEmailOptStatus", targetNamespace = "http://www.epsilon.com/webservices/")
        java.lang.String clubEmailOptStatus,
        @WebParam(name = "ClubMembershipUpdatedBy", targetNamespace = "http://www.epsilon.com/webservices/")
        java.lang.String clubMembershipUpdatedBy
    );

    @WebMethod(operationName = "CreateMember", action = "http://www.epsilon.com/webservices/CreateMember")
    @RequestWrapper(localName = "CreateMember", targetNamespace = "http://www.epsilon.com/webservices/", className = "com.epsilon.webservices.CreateMember")
    @ResponseWrapper(localName = "CreateMemberResponse", targetNamespace = "http://www.epsilon.com/webservices/", className = "com.epsilon.webservices.CreateMemberResponse")
    @WebResult(name = "CreateMemberResult", targetNamespace = "http://www.epsilon.com/webservices/")
    public com.epsilon.webservices.CreateMemberResponse.CreateMemberResult createMember(
        @WebParam(name = "MemberNumber", targetNamespace = "http://www.epsilon.com/webservices/")
        java.lang.String memberNumber,
        @WebParam(name = "EmailAddress", targetNamespace = "http://www.epsilon.com/webservices/")
        java.lang.String emailAddress,
        @WebParam(name = "EmailValidation", targetNamespace = "http://www.epsilon.com/webservices/")
        java.lang.String emailValidation,
        @WebParam(name = "Prefix", targetNamespace = "http://www.epsilon.com/webservices/")
        java.lang.String prefix,
        @WebParam(name = "Suffix", targetNamespace = "http://www.epsilon.com/webservices/")
        java.lang.String suffix,
        @WebParam(name = "FirstName", targetNamespace = "http://www.epsilon.com/webservices/")
        java.lang.String firstName,
        @WebParam(name = "MiddleInitial", targetNamespace = "http://www.epsilon.com/webservices/")
        java.lang.String middleInitial,
        @WebParam(name = "TestAccount", targetNamespace = "http://www.epsilon.com/webservices/")
        java.lang.String testAccount,
        @WebParam(name = "LastName", targetNamespace = "http://www.epsilon.com/webservices/")
        java.lang.String lastName,
        @WebParam(name = "Address1", targetNamespace = "http://www.epsilon.com/webservices/")
        java.lang.String address1,
        @WebParam(name = "Address2", targetNamespace = "http://www.epsilon.com/webservices/")
        java.lang.String address2,
        @WebParam(name = "City", targetNamespace = "http://www.epsilon.com/webservices/")
        java.lang.String city,
        @WebParam(name = "State", targetNamespace = "http://www.epsilon.com/webservices/")
        java.lang.String state,
        @WebParam(name = "ZipCode", targetNamespace = "http://www.epsilon.com/webservices/")
        java.lang.String zipCode,
        @WebParam(name = "ZipCodeExtension", targetNamespace = "http://www.epsilon.com/webservices/")
        java.lang.String zipCodeExtension,
        @WebParam(name = "CountryCode", targetNamespace = "http://www.epsilon.com/webservices/")
        java.lang.String countryCode,
        @WebParam(name = "DOB", targetNamespace = "http://www.epsilon.com/webservices/")
        java.lang.String dob,
        @WebParam(name = "CurrentDate", targetNamespace = "http://www.epsilon.com/webservices/")
        java.lang.String currentDate,
        @WebParam(name = "CurrentTime", targetNamespace = "http://www.epsilon.com/webservices/")
        java.lang.String currentTime,
        @WebParam(name = "ClubMembershipCreatedBy", targetNamespace = "http://www.epsilon.com/webservices/")
        java.lang.String clubMembershipCreatedBy,
        @WebParam(name = "ClubDNPStatus", targetNamespace = "http://www.epsilon.com/webservices/")
        java.lang.String clubDNPStatus,
        @WebParam(name = "SHCAssociateInd", targetNamespace = "http://www.epsilon.com/webservices/")
        java.lang.String shcAssociateInd,
        @WebParam(name = "CardDesignType", targetNamespace = "http://www.epsilon.com/webservices/")
        java.lang.String cardDesignType,
        @WebParam(name = "WirelessPermissionFlag", targetNamespace = "http://www.epsilon.com/webservices/")
        java.lang.String wirelessPermissionFlag,
        @WebParam(name = "ClubEmailOptStatus", targetNamespace = "http://www.epsilon.com/webservices/")
        java.lang.String clubEmailOptStatus,
        @WebParam(name = "PreferredLanguage", targetNamespace = "http://www.epsilon.com/webservices/")
        java.lang.String preferredLanguage,
        @WebParam(name = "StoreNumber", targetNamespace = "http://www.epsilon.com/webservices/")
        java.lang.String storeNumber,
        @WebParam(name = "Terminal", targetNamespace = "http://www.epsilon.com/webservices/")
        java.lang.String terminal,
        @WebParam(name = "RequestorID", targetNamespace = "http://www.epsilon.com/webservices/")
        java.lang.String requestorID,
        @WebParam(name = "MessageVersion", targetNamespace = "http://www.epsilon.com/webservices/")
        java.lang.String messageVersion,
        @WebParam(name = "EnrollmentOfferCode", targetNamespace = "http://www.epsilon.com/webservices/")
        java.lang.String enrollmentOfferCode,
        @WebParam(name = "PinNumber", targetNamespace = "http://www.epsilon.com/webservices/")
        java.lang.String pinNumber,
        @WebParam(name = "TnCStatus", targetNamespace = "http://www.epsilon.com/webservices/")
        java.lang.String tnCStatus,
        @WebParam(name = "TnCVersion", targetNamespace = "http://www.epsilon.com/webservices/")
        java.lang.String tnCVersion,
        @WebParam(name = "PhoneNumbers", targetNamespace = "http://www.epsilon.com/webservices/")
        com.epsilon.webservices.ArrayOfPhone phoneNumbers,
        @WebParam(name = "Affinities", targetNamespace = "http://www.epsilon.com/webservices/")
        com.epsilon.webservices.ArrayOfAffinity affinities,
        @WebParam(name = "Attributes", targetNamespace = "http://www.epsilon.com/webservices/")
        com.epsilon.webservices.ArrayOfAttr attributes
    );

    @WebMethod(operationName = "UpdateEmailConfirmed", action = "http://www.epsilon.com/webservices/UpdateEmailConfirmed")
    @RequestWrapper(localName = "UpdateEmailConfirmed", targetNamespace = "http://www.epsilon.com/webservices/", className = "com.epsilon.webservices.UpdateEmailConfirmed")
    @ResponseWrapper(localName = "UpdateEmailConfirmedResponse", targetNamespace = "http://www.epsilon.com/webservices/", className = "com.epsilon.webservices.UpdateEmailConfirmedResponse")
    @WebResult(name = "UpdateEmailConfirmedResult", targetNamespace = "http://www.epsilon.com/webservices/")
    public com.epsilon.webservices.UpdateEmailConfirmedResponse.UpdateEmailConfirmedResult updateEmailConfirmed(
        @WebParam(name = "MessageVersion", targetNamespace = "http://www.epsilon.com/webservices/")
        java.lang.String messageVersion,
        @WebParam(name = "MemberNumber", targetNamespace = "http://www.epsilon.com/webservices/")
        java.lang.String memberNumber,
        @WebParam(name = "RequestorID", targetNamespace = "http://www.epsilon.com/webservices/")
        java.lang.String requestorID,
        @WebParam(name = "CurrentDate", targetNamespace = "http://www.epsilon.com/webservices/")
        java.lang.String currentDate,
        @WebParam(name = "CurrentTime", targetNamespace = "http://www.epsilon.com/webservices/")
        java.lang.String currentTime,
        @WebParam(name = "EmailAddress", targetNamespace = "http://www.epsilon.com/webservices/")
        java.lang.String emailAddress,
        @WebParam(name = "EmailConfirmed", targetNamespace = "http://www.epsilon.com/webservices/")
        java.lang.String emailConfirmed
    );

    @WebMethod(operationName = "UpdateMemberAffinitySubscriptions", action = "http://www.epsilon.com/webservices/UpdateMemberAffinitySubscriptions")
    @RequestWrapper(localName = "UpdateMemberAffinitySubscriptions", targetNamespace = "http://www.epsilon.com/webservices/", className = "com.epsilon.webservices.UpdateMemberAffinitySubscriptions")
    @ResponseWrapper(localName = "UpdateMemberAffinitySubscriptionsResponse", targetNamespace = "http://www.epsilon.com/webservices/", className = "com.epsilon.webservices.UpdateMemberAffinitySubscriptionsResponse")
    @WebResult(name = "UpdateMemberAffinitySubscriptionsResult", targetNamespace = "http://www.epsilon.com/webservices/")
    public com.epsilon.webservices.UpdateMemberAffinitySubscriptionsResponse.UpdateMemberAffinitySubscriptionsResult updateMemberAffinitySubscriptions(
        @WebParam(name = "MemberNumber", targetNamespace = "http://www.epsilon.com/webservices/")
        java.lang.String memberNumber,
        @WebParam(name = "Affinities", targetNamespace = "http://www.epsilon.com/webservices/")
        com.epsilon.webservices.ArrayOfAffinity affinities,
        @WebParam(name = "MessageVersion", targetNamespace = "http://www.epsilon.com/webservices/")
        java.lang.String messageVersion,
        @WebParam(name = "RequestorID", targetNamespace = "http://www.epsilon.com/webservices/")
        java.lang.String requestorID,
        @WebParam(name = "StoreNumber", targetNamespace = "http://www.epsilon.com/webservices/")
        java.lang.String storeNumber,
        @WebParam(name = "Terminal", targetNamespace = "http://www.epsilon.com/webservices/")
        java.lang.String terminal,
        @WebParam(name = "AssociateId", targetNamespace = "http://www.epsilon.com/webservices/")
        java.lang.String associateId,
        @WebParam(name = "User", targetNamespace = "http://www.epsilon.com/webservices/")
        java.lang.String user
    );

    @WebMethod(operationName = "ValidatePin", action = "http://www.epsilon.com/webservices/ValidatePin")
    @RequestWrapper(localName = "ValidatePin", targetNamespace = "http://www.epsilon.com/webservices/", className = "com.epsilon.webservices.ValidatePin")
    @ResponseWrapper(localName = "ValidatePinResponse", targetNamespace = "http://www.epsilon.com/webservices/", className = "com.epsilon.webservices.ValidatePinResponse")
    @WebResult(name = "ValidatePinResult", targetNamespace = "http://www.epsilon.com/webservices/")
    public com.epsilon.webservices.ValidatePinResponse.ValidatePinResult validatePin(
        @WebParam(name = "MemberNumber", targetNamespace = "http://www.epsilon.com/webservices/")
        java.lang.String memberNumber,
        @WebParam(name = "RequestorID", targetNamespace = "http://www.epsilon.com/webservices/")
        java.lang.String requestorID,
        @WebParam(name = "CurrentDate", targetNamespace = "http://www.epsilon.com/webservices/")
        java.lang.String currentDate,
        @WebParam(name = "CurrentTime", targetNamespace = "http://www.epsilon.com/webservices/")
        java.lang.String currentTime,
        @WebParam(name = "PinNumber", targetNamespace = "http://www.epsilon.com/webservices/")
        java.lang.String pinNumber,
        @WebParam(name = "MessageVersion", targetNamespace = "http://www.epsilon.com/webservices/")
        java.lang.String messageVersion
    );

    @WebMethod(operationName = "GetMemberPrimaryProfile", action = "http://www.epsilon.com/webservices/GetMemberPrimaryProfile")
    @RequestWrapper(localName = "GetMemberPrimaryProfile", targetNamespace = "http://www.epsilon.com/webservices/", className = "com.epsilon.webservices.GetMemberPrimaryProfile")
    @ResponseWrapper(localName = "GetMemberPrimaryProfileResponse", targetNamespace = "http://www.epsilon.com/webservices/", className = "com.epsilon.webservices.GetMemberPrimaryProfileResponse")
    @WebResult(name = "GetMemberPrimaryProfileResult", targetNamespace = "http://www.epsilon.com/webservices/")
    public com.epsilon.webservices.GetMemberPrimaryProfileResponse.GetMemberPrimaryProfileResult getMemberPrimaryProfile(
        @WebParam(name = "MemberNumber", targetNamespace = "http://www.epsilon.com/webservices/")
        java.lang.String memberNumber,
        @WebParam(name = "MessageVersion", targetNamespace = "http://www.epsilon.com/webservices/")
        java.lang.String messageVersion
    );

    @WebMethod(operationName = "UpdateMemberPrompts", action = "http://www.epsilon.com/webservices/UpdateMemberPrompts")
    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
    @WebResult(name = "UpdateMemberPromptsResponse", targetNamespace = "http://www.epsilon.com/webservices/", partName = "parameters")
    public UpdateMemberPromptsResponse updateMemberPrompts(
        @WebParam(partName = "parameters", name = "UpdateMemberPrompts", targetNamespace = "http://www.epsilon.com/webservices/")
        UpdateMemberPrompts parameters
    );

    @WebMethod(operationName = "GetPartnerEnrollmentDetails", action = "http://www.epsilon.com/webservices/GetPartnerEnrollmentDetails")
    @RequestWrapper(localName = "GetPartnerEnrollmentDetails", targetNamespace = "http://www.epsilon.com/webservices/", className = "com.epsilon.webservices.GetPartnerEnrollmentDetails")
    @ResponseWrapper(localName = "GetPartnerEnrollmentDetailsResponse", targetNamespace = "http://www.epsilon.com/webservices/", className = "com.epsilon.webservices.GetPartnerEnrollmentDetailsResponse")
    @WebResult(name = "GetPartnerEnrollmentDetailsResult", targetNamespace = "http://www.epsilon.com/webservices/")
    public com.epsilon.webservices.GetPartnerEnrollmentDetailsResponse.GetPartnerEnrollmentDetailsResult getPartnerEnrollmentDetails(
        @WebParam(name = "MemberNumber", targetNamespace = "http://www.epsilon.com/webservices/")
        java.lang.String memberNumber,
        @WebParam(name = "Source", targetNamespace = "http://www.epsilon.com/webservices/")
        java.lang.String source,
        @WebParam(name = "RequestorID", targetNamespace = "http://www.epsilon.com/webservices/")
        java.lang.String requestorID,
        @WebParam(name = "StoreNumber", targetNamespace = "http://www.epsilon.com/webservices/")
        java.lang.String storeNumber,
        @WebParam(name = "RegisterNumber", targetNamespace = "http://www.epsilon.com/webservices/")
        java.lang.String registerNumber,
        @WebParam(name = "TransactionNumber", targetNamespace = "http://www.epsilon.com/webservices/")
        java.lang.String transactionNumber,
        @WebParam(name = "AssociateID", targetNamespace = "http://www.epsilon.com/webservices/")
        java.lang.String associateID,
        @WebParam(name = "Date", targetNamespace = "http://www.epsilon.com/webservices/")
        java.lang.String date,
        @WebParam(name = "Time", targetNamespace = "http://www.epsilon.com/webservices/")
        java.lang.String time,
        @WebParam(name = "AliasName", targetNamespace = "http://www.epsilon.com/webservices/")
        java.lang.String aliasName,
        @WebParam(name = "MessageVersion", targetNamespace = "http://www.epsilon.com/webservices/")
        java.lang.String messageVersion
    );

    @WebMethod(operationName = "GetMemberPrompts", action = "http://www.epsilon.com/webservices/GetMemberPrompts")
    @RequestWrapper(localName = "GetMemberPrompts", targetNamespace = "http://www.epsilon.com/webservices/", className = "com.epsilon.webservices.GetMemberPrompts")
    @ResponseWrapper(localName = "GetMemberPromptsResponse", targetNamespace = "http://www.epsilon.com/webservices/", className = "com.epsilon.webservices.GetMemberPromptsResponse")
    @WebResult(name = "GetMemberPromptsResult", targetNamespace = "http://www.epsilon.com/webservices/")
    public com.epsilon.webservices.GetMemberPromptsResponse.GetMemberPromptsResult getMemberPrompts(
        @WebParam(name = "MemberNumber", targetNamespace = "http://www.epsilon.com/webservices/")
        java.lang.String memberNumber,
        @WebParam(name = "MessageVersion", targetNamespace = "http://www.epsilon.com/webservices/")
        java.lang.String messageVersion,
        @WebParam(name = "RequestorID", targetNamespace = "http://www.epsilon.com/webservices/")
        java.lang.String requestorID,
        @WebParam(name = "PromptGroups", targetNamespace = "http://www.epsilon.com/webservices/")
        com.epsilon.webservices.ArrayOfPromptGroup promptGroups,
        @WebParam(name = "CurrentDate", targetNamespace = "http://www.epsilon.com/webservices/")
        javax.xml.datatype.XMLGregorianCalendar currentDate,
        @WebParam(name = "CurrentTime", targetNamespace = "http://www.epsilon.com/webservices/")
        java.lang.String currentTime,
        @WebParam(name = "StoreNumber", targetNamespace = "http://www.epsilon.com/webservices/")
        java.lang.String storeNumber,
        @WebParam(name = "Terminal", targetNamespace = "http://www.epsilon.com/webservices/")
        java.lang.String terminal,
        @WebParam(name = "IncludeAnswers", targetNamespace = "http://www.epsilon.com/webservices/")
        java.lang.String includeAnswers
    );

    @WebMethod(operationName = "UpdateMemberExtendedProfile", action = "http://www.epsilon.com/webservices/UpdateMemberExtendedProfile")
    @RequestWrapper(localName = "UpdateMemberExtendedProfile", targetNamespace = "http://www.epsilon.com/webservices/", className = "com.epsilon.webservices.UpdateMemberExtendedProfile")
    @ResponseWrapper(localName = "UpdateMemberExtendedProfileResponse", targetNamespace = "http://www.epsilon.com/webservices/", className = "com.epsilon.webservices.UpdateMemberExtendedProfileResponse")
    @WebResult(name = "UpdateMemberExtendedProfileResult", targetNamespace = "http://www.epsilon.com/webservices/")
    public com.epsilon.webservices.UpdateMemberExtendedProfileResponse.UpdateMemberExtendedProfileResult updateMemberExtendedProfile(
        @WebParam(name = "MemberNumber", targetNamespace = "http://www.epsilon.com/webservices/")
        java.lang.String memberNumber,
        @WebParam(name = "ExtendedProfilePreferences", targetNamespace = "http://www.epsilon.com/webservices/")
        com.epsilon.webservices.ArrayOfExtendedProfilePreference extendedProfilePreferences
    );

    @WebMethod(operationName = "GetMemberAffinitySubscriptions", action = "http://www.epsilon.com/webservices/GetMemberAffinitySubscriptions")
    @RequestWrapper(localName = "GetMemberAffinitySubscriptions", targetNamespace = "http://www.epsilon.com/webservices/", className = "com.epsilon.webservices.GetMemberAffinitySubscriptions")
    @ResponseWrapper(localName = "GetMemberAffinitySubscriptionsResponse", targetNamespace = "http://www.epsilon.com/webservices/", className = "com.epsilon.webservices.GetMemberAffinitySubscriptionsResponse")
    @WebResult(name = "GetMemberAffinitySubscriptionsResult", targetNamespace = "http://www.epsilon.com/webservices/")
    public com.epsilon.webservices.GetMemberAffinitySubscriptionsResponse.GetMemberAffinitySubscriptionsResult getMemberAffinitySubscriptions(
        @WebParam(name = "MemberNumber", targetNamespace = "http://www.epsilon.com/webservices/")
        java.lang.String memberNumber,
        @WebParam(name = "MessageVersion", targetNamespace = "http://www.epsilon.com/webservices/")
        java.lang.String messageVersion,
        @WebParam(name = "RequestorID", targetNamespace = "http://www.epsilon.com/webservices/")
        java.lang.String requestorID,
        @WebParam(name = "StoreNumber", targetNamespace = "http://www.epsilon.com/webservices/")
        java.lang.String storeNumber,
        @WebParam(name = "Terminal", targetNamespace = "http://www.epsilon.com/webservices/")
        java.lang.String terminal,
        @WebParam(name = "AssociateId", targetNamespace = "http://www.epsilon.com/webservices/")
        java.lang.String associateId,
        @WebParam(name = "CurrentDate", targetNamespace = "http://www.epsilon.com/webservices/")
        java.lang.String currentDate,
        @WebParam(name = "CurrentTime", targetNamespace = "http://www.epsilon.com/webservices/")
        java.lang.String currentTime
    );

    @WebMethod(operationName = "GetMemberAuditLookup", action = "http://www.epsilon.com/webservices/GetMemberAuditLookup")
    @RequestWrapper(localName = "GetMemberAuditLookup", targetNamespace = "http://www.epsilon.com/webservices/", className = "com.epsilon.webservices.GetMemberAuditLookup")
    @ResponseWrapper(localName = "GetMemberAuditLookupResponse", targetNamespace = "http://www.epsilon.com/webservices/", className = "com.epsilon.webservices.GetMemberAuditLookupResponse")
    @WebResult(name = "GetMemberAuditResult", targetNamespace = "http://www.epsilon.com/webservices/")
    public com.epsilon.webservices.GetMemberAuditLookupResponse.GetMemberAuditResult getMemberAuditLookup(
        @WebParam(name = "MemberNumber", targetNamespace = "http://www.epsilon.com/webservices/")
        java.lang.String memberNumber,
        @WebParam(name = "MessageVersion", targetNamespace = "http://www.epsilon.com/webservices/")
        java.lang.String messageVersion,
        @WebParam(name = "AuditType", targetNamespace = "http://www.epsilon.com/webservices/")
        java.lang.String auditType,
        @WebParam(name = "RequestorID", targetNamespace = "http://www.epsilon.com/webservices/")
        java.lang.String requestorID,
        @WebParam(name = "StartDateTime", targetNamespace = "http://www.epsilon.com/webservices/")
        java.lang.String startDateTime,
        @WebParam(name = "EndDateTime", targetNamespace = "http://www.epsilon.com/webservices/")
        java.lang.String endDateTime
    );

    @WebMethod(operationName = "GetMemberLevel", action = "http://www.epsilon.com/webservices/GetMemberLevel")
    @RequestWrapper(localName = "GetMemberLevel", targetNamespace = "http://www.epsilon.com/webservices/", className = "com.epsilon.webservices.GetMemberLevel")
    @ResponseWrapper(localName = "GetMemberLevelResponse", targetNamespace = "http://www.epsilon.com/webservices/", className = "com.epsilon.webservices.GetMemberLevelResponse")
    @WebResult(name = "GetMemberLevelResult", targetNamespace = "http://www.epsilon.com/webservices/")
    public com.epsilon.webservices.GetMemberLevelResponse.GetMemberLevelResult getMemberLevel(
        @WebParam(name = "MemberNumber", targetNamespace = "http://www.epsilon.com/webservices/")
        java.lang.String memberNumber,
        @WebParam(name = "MessageVersion", targetNamespace = "http://www.epsilon.com/webservices/")
        java.lang.String messageVersion,
        @WebParam(name = "RequestorID", targetNamespace = "http://www.epsilon.com/webservices/")
        java.lang.String requestorID
    );

    @WebMethod(operationName = "GetMemberTargetedOffers", action = "http://www.epsilon.com/webservices/GetMemberTargetedOffers")
    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
    @WebResult(name = "GetMemberTargetedOffersResponse", targetNamespace = "http://www.epsilon.com/webservices/", partName = "parameters")
    public java.lang.Object getMemberTargetedOffers(
        @WebParam(partName = "parameters", name = "GetMemberTargetedOffers", targetNamespace = "http://www.epsilon.com/webservices/")
        GetMemberTargetedOffers parameters
    );

    @WebMethod(operationName = "ValidateMember", action = "http://www.epsilon.com/webservices/ValidateMember")
    @RequestWrapper(localName = "ValidateMember", targetNamespace = "http://www.epsilon.com/webservices/", className = "com.epsilon.webservices.ValidateMember")
    @ResponseWrapper(localName = "ValidateMemberResponse", targetNamespace = "http://www.epsilon.com/webservices/", className = "com.epsilon.webservices.ValidateMemberResponse")
    @WebResult(name = "ValidateMemberResult", targetNamespace = "http://www.epsilon.com/webservices/")
    public com.epsilon.webservices.ValidateMemberResponse.ValidateMemberResult validateMember(
        @WebParam(name = "MemberNumber", targetNamespace = "http://www.epsilon.com/webservices/")
        java.lang.String memberNumber,
        @WebParam(name = "FirstName", targetNamespace = "http://www.epsilon.com/webservices/")
        java.lang.String firstName,
        @WebParam(name = "LastName", targetNamespace = "http://www.epsilon.com/webservices/")
        java.lang.String lastName,
        @WebParam(name = "MessageVersion", targetNamespace = "http://www.epsilon.com/webservices/")
        java.lang.String messageVersion
    );

    @WebMethod(operationName = "RegisterMember", action = "http://www.epsilon.com/webservices/RegisterMember")
    @RequestWrapper(localName = "RegisterMember", targetNamespace = "http://www.epsilon.com/webservices/", className = "com.epsilon.webservices.RegisterMember")
    @ResponseWrapper(localName = "RegisterMemberResponse", targetNamespace = "http://www.epsilon.com/webservices/", className = "com.epsilon.webservices.RegisterMemberResponse")
    @WebResult(name = "RegisterMemberResult", targetNamespace = "http://www.epsilon.com/webservices/")
    public com.epsilon.webservices.RegisterMemberResponse.RegisterMemberResult registerMember(
        @WebParam(name = "MemberNumber", targetNamespace = "http://www.epsilon.com/webservices/")
        java.lang.String memberNumber,
        @WebParam(name = "EmailAddress", targetNamespace = "http://www.epsilon.com/webservices/")
        java.lang.String emailAddress,
        @WebParam(name = "EmailValidation", targetNamespace = "http://www.epsilon.com/webservices/")
        java.lang.String emailValidation,
        @WebParam(name = "ZipCode", targetNamespace = "http://www.epsilon.com/webservices/")
        java.lang.String zipCode,
        @WebParam(name = "ZipCodeExtension", targetNamespace = "http://www.epsilon.com/webservices/")
        java.lang.String zipCodeExtension,
        @WebParam(name = "SHCAssociateInd", targetNamespace = "http://www.epsilon.com/webservices/")
        java.lang.String shcAssociateInd,
        @WebParam(name = "MessageVersion", targetNamespace = "http://www.epsilon.com/webservices/")
        java.lang.String messageVersion,
        @WebParam(name = "CurrentDate", targetNamespace = "http://www.epsilon.com/webservices/")
        java.lang.String currentDate,
        @WebParam(name = "CurrentTime", targetNamespace = "http://www.epsilon.com/webservices/")
        java.lang.String currentTime
    );

    @WebMethod(operationName = "CreatePartnerEnrollmentDetails", action = "http://www.epsilon.com/webservices/CreatePartnerEnrollmentDetails")
    @RequestWrapper(localName = "CreatePartnerEnrollmentDetails", targetNamespace = "http://www.epsilon.com/webservices/", className = "com.epsilon.webservices.CreatePartnerEnrollmentDetails")
    @ResponseWrapper(localName = "CreatePartnerEnrollmentDetailsResponse", targetNamespace = "http://www.epsilon.com/webservices/", className = "com.epsilon.webservices.CreatePartnerEnrollmentDetailsResponse")
    @WebResult(name = "CreatePartnerEnrollmentDetailsResult", targetNamespace = "http://www.epsilon.com/webservices/")
    public com.epsilon.webservices.CreatePartnerEnrollmentDetailsResponse.CreatePartnerEnrollmentDetailsResult createPartnerEnrollmentDetails(
        @WebParam(name = "MemberUniqueId", targetNamespace = "http://www.epsilon.com/webservices/")
        java.lang.String memberUniqueId,
        @WebParam(name = "MemberNumber", targetNamespace = "http://www.epsilon.com/webservices/")
        java.lang.String memberNumber,
        @WebParam(name = "RegistrationUniqueId", targetNamespace = "http://www.epsilon.com/webservices/")
        java.lang.String registrationUniqueId,
        @WebParam(name = "ServiceRegistrationNumber", targetNamespace = "http://www.epsilon.com/webservices/")
        java.lang.String serviceRegistrationNumber,
        @WebParam(name = "EnrollmentDate", targetNamespace = "http://www.epsilon.com/webservices/")
        java.lang.String enrollmentDate,
        @WebParam(name = "UnenrollmentDate", targetNamespace = "http://www.epsilon.com/webservices/")
        java.lang.String unenrollmentDate,
        @WebParam(name = "MobileNumber", targetNamespace = "http://www.epsilon.com/webservices/")
        java.lang.String mobileNumber,
        @WebParam(name = "RegistrationIndicator", targetNamespace = "http://www.epsilon.com/webservices/")
        java.lang.String registrationIndicator,
        @WebParam(name = "EnrollmentIndicator", targetNamespace = "http://www.epsilon.com/webservices/")
        java.lang.String enrollmentIndicator,
        @WebParam(name = "Source", targetNamespace = "http://www.epsilon.com/webservices/")
        java.lang.String source,
        @WebParam(name = "ServiceEnrollmentDate", targetNamespace = "http://www.epsilon.com/webservices/")
        java.lang.String serviceEnrollmentDate,
        @WebParam(name = "ServiceUnenrollmentDate", targetNamespace = "http://www.epsilon.com/webservices/")
        java.lang.String serviceUnenrollmentDate,
        @WebParam(name = "StoreNumber", targetNamespace = "http://www.epsilon.com/webservices/")
        java.lang.String storeNumber,
        @WebParam(name = "RequestorID", targetNamespace = "http://www.epsilon.com/webservices/")
        java.lang.String requestorID,
        @WebParam(name = "RegisterNumber", targetNamespace = "http://www.epsilon.com/webservices/")
        java.lang.String registerNumber,
        @WebParam(name = "TransactionNumber", targetNamespace = "http://www.epsilon.com/webservices/")
        java.lang.String transactionNumber,
        @WebParam(name = "AssociateID", targetNamespace = "http://www.epsilon.com/webservices/")
        java.lang.String associateID,
        @WebParam(name = "Date", targetNamespace = "http://www.epsilon.com/webservices/")
        java.lang.String date,
        @WebParam(name = "Time", targetNamespace = "http://www.epsilon.com/webservices/")
        java.lang.String time,
        @WebParam(name = "AliasName", targetNamespace = "http://www.epsilon.com/webservices/")
        java.lang.String aliasName,
        @WebParam(name = "MessageVersion", targetNamespace = "http://www.epsilon.com/webservices/")
        java.lang.String messageVersion
    );

    @WebMethod(operationName = "GetRewardBalance", action = "http://www.epsilon.com/webservices/GetRewardBalance")
    @RequestWrapper(localName = "GetRewardBalance", targetNamespace = "http://www.epsilon.com/webservices/", className = "com.epsilon.webservices.GetRewardBalance")
    @ResponseWrapper(localName = "GetRewardBalanceResponse", targetNamespace = "http://www.epsilon.com/webservices/", className = "com.epsilon.webservices.GetRewardBalanceResponse")
    @WebResult(name = "GetRewardBalanceResult", targetNamespace = "http://www.epsilon.com/webservices/")
    public com.epsilon.webservices.GetRewardBalanceResponse.GetRewardBalanceResult getRewardBalance(
        @WebParam(name = "RequestorID", targetNamespace = "http://www.epsilon.com/webservices/")
        java.lang.String requestorID,
        @WebParam(name = "StoreNumber", targetNamespace = "http://www.epsilon.com/webservices/")
        java.lang.String storeNumber,
        @WebParam(name = "CurrentDate", targetNamespace = "http://www.epsilon.com/webservices/")
        java.lang.String currentDate,
        @WebParam(name = "CurrentTime", targetNamespace = "http://www.epsilon.com/webservices/")
        java.lang.String currentTime,
        @WebParam(name = "AssociateID", targetNamespace = "http://www.epsilon.com/webservices/")
        java.lang.String associateID,
        @WebParam(name = "MemberNumber", targetNamespace = "http://www.epsilon.com/webservices/")
        java.lang.String memberNumber,
        @WebParam(name = "PointType", targetNamespace = "http://www.epsilon.com/webservices/")
        java.lang.String pointType,
        @WebParam(name = "MessageVersion", targetNamespace = "http://www.epsilon.com/webservices/")
        java.lang.String messageVersion
    );

    @WebMethod(operationName = "GetMemberLookup", action = "http://www.epsilon.com/webservices/GetMemberLookup")
    @RequestWrapper(localName = "GetMemberLookup", targetNamespace = "http://www.epsilon.com/webservices/", className = "com.epsilon.webservices.GetMemberLookup")
    @ResponseWrapper(localName = "GetMemberLookupResponse", targetNamespace = "http://www.epsilon.com/webservices/", className = "com.epsilon.webservices.GetMemberLookupResponse")
    @WebResult(name = "GetMemberLookupResult", targetNamespace = "http://www.epsilon.com/webservices/")
    public com.epsilon.webservices.GetMemberLookupResponse.GetMemberLookupResult getMemberLookup(
        @WebParam(name = "MessageVersion", targetNamespace = "http://www.epsilon.com/webservices/")
        java.lang.String messageVersion,
        @WebParam(name = "MemberNumber", targetNamespace = "http://www.epsilon.com/webservices/")
        java.lang.String memberNumber,
        @WebParam(name = "EmailAddress", targetNamespace = "http://www.epsilon.com/webservices/")
        java.lang.String emailAddress,
        @WebParam(name = "ID", targetNamespace = "http://www.epsilon.com/webservices/")
        java.lang.String id,
        @WebParam(name = "Type", targetNamespace = "http://www.epsilon.com/webservices/")
        java.lang.String type,
        @WebParam(name = "PhoneNumber", targetNamespace = "http://www.epsilon.com/webservices/")
        java.lang.String phoneNumber,
        @WebParam(name = "StoreNumber", targetNamespace = "http://www.epsilon.com/webservices/")
        java.lang.String storeNumber,
        @WebParam(name = "Terminal", targetNamespace = "http://www.epsilon.com/webservices/")
        java.lang.String terminal,
        @WebParam(name = "RequestorID", targetNamespace = "http://www.epsilon.com/webservices/")
        java.lang.String requestorID,
        @WebParam(name = "SearchType", targetNamespace = "http://www.epsilon.com/webservices/")
        java.lang.String searchType,
        @WebParam(name = "CurrentDate", targetNamespace = "http://www.epsilon.com/webservices/")
        java.lang.String currentDate,
        @WebParam(name = "CurrentTime", targetNamespace = "http://www.epsilon.com/webservices/")
        java.lang.String currentTime,
        @WebParam(name = "MaxRecords", targetNamespace = "http://www.epsilon.com/webservices/")
        java.lang.String maxRecords,
        @WebParam(name = "MaxPOSPrompt", targetNamespace = "http://www.epsilon.com/webservices/")
        java.lang.String maxPOSPrompt,
        @WebParam(name = "PromptGroups", targetNamespace = "http://www.epsilon.com/webservices/")
        com.epsilon.webservices.ArrayOfPromptGroup promptGroups,
        @WebParam(name = "FirstName", targetNamespace = "http://www.epsilon.com/webservices/")
        java.lang.String firstName,
        @WebParam(name = "LastName", targetNamespace = "http://www.epsilon.com/webservices/")
        java.lang.String lastName,
        @WebParam(name = "ZipCode", targetNamespace = "http://www.epsilon.com/webservices/")
        java.lang.String zipCode
    );

    @WebMethod(operationName = "GetMemberExtendedProfile", action = "http://www.epsilon.com/webservices/GetMemberExtendedProfile")
    @RequestWrapper(localName = "GetMemberExtendedProfile", targetNamespace = "http://www.epsilon.com/webservices/", className = "com.epsilon.webservices.GetMemberExtendedProfile")
    @ResponseWrapper(localName = "GetMemberExtendedProfileResponse", targetNamespace = "http://www.epsilon.com/webservices/", className = "com.epsilon.webservices.GetMemberExtendedProfileResponse")
    @WebResult(name = "GetMemberExtendedProfileResult", targetNamespace = "http://www.epsilon.com/webservices/")
    public com.epsilon.webservices.GetMemberExtendedProfileResponse.GetMemberExtendedProfileResult getMemberExtendedProfile(
        @WebParam(name = "MemberNumber", targetNamespace = "http://www.epsilon.com/webservices/")
        java.lang.String memberNumber,
        @WebParam(name = "MessageVersion", targetNamespace = "http://www.epsilon.com/webservices/")
        java.lang.String messageVersion
    );
}
