
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package com.epsilon.webservices;

import java.util.logging.Logger;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.1.11
 * 2017-04-14T18:02:39.589+05:30
 * Generated source version: 3.1.11
 * 
 */

@javax.jws.WebService(
                      serviceName = "ProfileSoapImplService",
                      portName = "ProfileSoapImplPort",
                      targetNamespace = "http://soap.service.profile.rewards.sears.com/",
                      wsdlLocation = "http://tellurideas-uat.intra.searshc.com/tellurideAS/Profile?wsdl",
                      endpointInterface = "com.epsilon.webservices.ProfileSoap")
                      
public class ProfileSoapImplPortImpl implements ProfileSoap {

    private static final Logger LOG = Logger.getLogger(ProfileSoapImplPortImpl.class.getName());

    /* (non-Javadoc)
     * @see com.epsilon.webservices.ProfileSoap#memberReplaceCard(java.lang.String originalMemberNumber, java.lang.String newMemberNumber, java.lang.String messageVersion)*
     */
    public com.epsilon.webservices.MemberReplaceCardResponse.MemberReplaceCardResult memberReplaceCard(java.lang.String originalMemberNumber, java.lang.String newMemberNumber, java.lang.String messageVersion) { 
        LOG.info("Executing operation memberReplaceCard");
        System.out.println(originalMemberNumber);
        System.out.println(newMemberNumber);
        System.out.println(messageVersion);
        try {
            com.epsilon.webservices.MemberReplaceCardResponse.MemberReplaceCardResult _return = new com.epsilon.webservices.MemberReplaceCardResponse.MemberReplaceCardResult();
            java.util.List<java.lang.Object> _returnContent = new java.util.ArrayList<java.lang.Object>();
            java.lang.Object _returnContentVal1 = null;
            _returnContent.add(_returnContentVal1);
            _return.getContent().addAll(_returnContent);
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.epsilon.webservices.ProfileSoap#updateMemberPrimaryProfile(java.lang.String messageVersion, java.lang.String memberNumber, java.lang.String requestorID, java.lang.String storeNumber, java.lang.String terminal, java.lang.String currentDate, java.lang.String currentTime, java.lang.String prefix, java.lang.String firstName, java.lang.String lastName, java.lang.String middleInitial, java.lang.String suffix, java.lang.String authFirstName, java.lang.String authLastName, java.lang.String clubDNPStatus, java.lang.String clubMembershipUpdatedBy, java.lang.String dateUpdated, java.lang.String dob, java.lang.String testAccount, java.lang.String accountStatus, java.lang.String statusChangeReasonCode, java.lang.String shcAssociateInd, java.lang.String wirelessPermissionFlag, java.lang.String languagePreference, java.lang.String address1, java.lang.String address2, java.lang.String city, java.lang.String state, java.lang.String zipCode, java.lang.String zipCodeExtension, java.lang.String countryCode, java.lang.String emailAddress, java.lang.String emailValidation, java.lang.String clubEmailOptStatus, java.lang.String tnCStatus, java.lang.String tnCVersion, java.lang.String charity, java.lang.String profileUpdate, com.epsilon.webservices.ArrayOfPOSPrompt posPrompt, com.epsilon.webservices.AdditionalAttributes additionalAttributes, com.epsilon.webservices.ArrayOfPhone phoneNumbers, com.epsilon.webservices.ArrayOfAffinity affinities, com.epsilon.webservices.ArrayOfAttr attributes)*
     */
    public com.epsilon.webservices.UpdateMemberPrimaryProfileResponse.UpdateMemberPrimaryProfileResult updateMemberPrimaryProfile(java.lang.String messageVersion, java.lang.String memberNumber, java.lang.String requestorID, java.lang.String storeNumber, java.lang.String terminal, java.lang.String currentDate, java.lang.String currentTime, java.lang.String prefix, java.lang.String firstName, java.lang.String lastName, java.lang.String middleInitial, java.lang.String suffix, java.lang.String authFirstName, java.lang.String authLastName, java.lang.String clubDNPStatus, java.lang.String clubMembershipUpdatedBy, java.lang.String dateUpdated, java.lang.String dob, java.lang.String testAccount, java.lang.String accountStatus, java.lang.String statusChangeReasonCode, java.lang.String shcAssociateInd, java.lang.String wirelessPermissionFlag, java.lang.String languagePreference, java.lang.String address1, java.lang.String address2, java.lang.String city, java.lang.String state, java.lang.String zipCode, java.lang.String zipCodeExtension, java.lang.String countryCode, java.lang.String emailAddress, java.lang.String emailValidation, java.lang.String clubEmailOptStatus, java.lang.String tnCStatus, java.lang.String tnCVersion, java.lang.String charity, java.lang.String profileUpdate, com.epsilon.webservices.ArrayOfPOSPrompt posPrompt, com.epsilon.webservices.AdditionalAttributes additionalAttributes, com.epsilon.webservices.ArrayOfPhone phoneNumbers, com.epsilon.webservices.ArrayOfAffinity affinities, com.epsilon.webservices.ArrayOfAttr attributes) { 
        LOG.info("Executing operation updateMemberPrimaryProfile");
        System.out.println(messageVersion);
        System.out.println(memberNumber);
        System.out.println(requestorID);
        System.out.println(storeNumber);
        System.out.println(terminal);
        System.out.println(currentDate);
        System.out.println(currentTime);
        System.out.println(prefix);
        System.out.println(firstName);
        System.out.println(lastName);
        System.out.println(middleInitial);
        System.out.println(suffix);
        System.out.println(authFirstName);
        System.out.println(authLastName);
        System.out.println(clubDNPStatus);
        System.out.println(clubMembershipUpdatedBy);
        System.out.println(dateUpdated);
        System.out.println(dob);
        System.out.println(testAccount);
        System.out.println(accountStatus);
        System.out.println(statusChangeReasonCode);
        System.out.println(shcAssociateInd);
        System.out.println(wirelessPermissionFlag);
        System.out.println(languagePreference);
        System.out.println(address1);
        System.out.println(address2);
        System.out.println(city);
        System.out.println(state);
        System.out.println(zipCode);
        System.out.println(zipCodeExtension);
        System.out.println(countryCode);
        System.out.println(emailAddress);
        System.out.println(emailValidation);
        System.out.println(clubEmailOptStatus);
        System.out.println(tnCStatus);
        System.out.println(tnCVersion);
        System.out.println(charity);
        System.out.println(profileUpdate);
        System.out.println(posPrompt);
        System.out.println(additionalAttributes);
        System.out.println(phoneNumbers);
        System.out.println(affinities);
        System.out.println(attributes);
        try {
            com.epsilon.webservices.UpdateMemberPrimaryProfileResponse.UpdateMemberPrimaryProfileResult _return = new com.epsilon.webservices.UpdateMemberPrimaryProfileResponse.UpdateMemberPrimaryProfileResult();
            java.util.List<java.lang.Object> _returnContent = new java.util.ArrayList<java.lang.Object>();
            java.lang.Object _returnContentVal1 = null;
            _returnContent.add(_returnContentVal1);
            _return.getContent().addAll(_returnContent);
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.epsilon.webservices.ProfileSoap#dateTimeOnServer(java.lang.Object parameters)*
     */
    public java.lang.Object dateTimeOnServer(java.lang.Object parameters) { 
        LOG.info("Executing operation dateTimeOnServer");
        System.out.println(parameters);
        try {
            java.lang.Object _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.epsilon.webservices.ProfileSoap#updateMemberPin(java.lang.String messageVersion, java.lang.String memberNumber, java.lang.String requestorID, java.lang.String currentDate, java.lang.String currentTime, java.lang.String pinNumber)*
     */
    public com.epsilon.webservices.UpdateMemberPinResponse.UpdateMemberPinResult updateMemberPin(java.lang.String messageVersion, java.lang.String memberNumber, java.lang.String requestorID, java.lang.String currentDate, java.lang.String currentTime, java.lang.String pinNumber) { 
        LOG.info("Executing operation updateMemberPin");
        System.out.println(messageVersion);
        System.out.println(memberNumber);
        System.out.println(requestorID);
        System.out.println(currentDate);
        System.out.println(currentTime);
        System.out.println(pinNumber);
        try {
            com.epsilon.webservices.UpdateMemberPinResponse.UpdateMemberPinResult _return = new com.epsilon.webservices.UpdateMemberPinResponse.UpdateMemberPinResult();
            java.util.List<java.lang.Object> _returnContent = new java.util.ArrayList<java.lang.Object>();
            java.lang.Object _returnContentVal1 = null;
            _returnContent.add(_returnContentVal1);
            _return.getContent().addAll(_returnContent);
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.epsilon.webservices.ProfileSoap#updateMemberEmail(java.lang.String messageVersion, java.lang.String memberNumber, java.lang.String requestorID, java.lang.String currentDate, java.lang.String currentTime, java.lang.String emailAddress, java.lang.String emailValidation, java.lang.String clubEmailOptStatus, java.lang.String clubMembershipUpdatedBy)*
     */
    public com.epsilon.webservices.UpdateMemberEmailResponse.UpdateMemberEmailResult updateMemberEmail(java.lang.String messageVersion, java.lang.String memberNumber, java.lang.String requestorID, java.lang.String currentDate, java.lang.String currentTime, java.lang.String emailAddress, java.lang.String emailValidation, java.lang.String clubEmailOptStatus, java.lang.String clubMembershipUpdatedBy) { 
        LOG.info("Executing operation updateMemberEmail");
        System.out.println(messageVersion);
        System.out.println(memberNumber);
        System.out.println(requestorID);
        System.out.println(currentDate);
        System.out.println(currentTime);
        System.out.println(emailAddress);
        System.out.println(emailValidation);
        System.out.println(clubEmailOptStatus);
        System.out.println(clubMembershipUpdatedBy);
        try {
            com.epsilon.webservices.UpdateMemberEmailResponse.UpdateMemberEmailResult _return = new com.epsilon.webservices.UpdateMemberEmailResponse.UpdateMemberEmailResult();
            java.util.List<java.lang.Object> _returnContent = new java.util.ArrayList<java.lang.Object>();
            java.lang.Object _returnContentVal1 = null;
            _returnContent.add(_returnContentVal1);
            _return.getContent().addAll(_returnContent);
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.epsilon.webservices.ProfileSoap#createMember(java.lang.String memberNumber, java.lang.String emailAddress, java.lang.String emailValidation, java.lang.String prefix, java.lang.String suffix, java.lang.String firstName, java.lang.String middleInitial, java.lang.String testAccount, java.lang.String lastName, java.lang.String address1, java.lang.String address2, java.lang.String city, java.lang.String state, java.lang.String zipCode, java.lang.String zipCodeExtension, java.lang.String countryCode, java.lang.String dob, java.lang.String currentDate, java.lang.String currentTime, java.lang.String clubMembershipCreatedBy, java.lang.String clubDNPStatus, java.lang.String shcAssociateInd, java.lang.String cardDesignType, java.lang.String wirelessPermissionFlag, java.lang.String clubEmailOptStatus, java.lang.String preferredLanguage, java.lang.String storeNumber, java.lang.String terminal, java.lang.String requestorID, java.lang.String messageVersion, java.lang.String enrollmentOfferCode, java.lang.String pinNumber, java.lang.String tnCStatus, java.lang.String tnCVersion, com.epsilon.webservices.ArrayOfPhone phoneNumbers, com.epsilon.webservices.ArrayOfAffinity affinities, com.epsilon.webservices.ArrayOfAttr attributes)*
     */
    public com.epsilon.webservices.CreateMemberResponse.CreateMemberResult createMember(java.lang.String memberNumber, java.lang.String emailAddress, java.lang.String emailValidation, java.lang.String prefix, java.lang.String suffix, java.lang.String firstName, java.lang.String middleInitial, java.lang.String testAccount, java.lang.String lastName, java.lang.String address1, java.lang.String address2, java.lang.String city, java.lang.String state, java.lang.String zipCode, java.lang.String zipCodeExtension, java.lang.String countryCode, java.lang.String dob, java.lang.String currentDate, java.lang.String currentTime, java.lang.String clubMembershipCreatedBy, java.lang.String clubDNPStatus, java.lang.String shcAssociateInd, java.lang.String cardDesignType, java.lang.String wirelessPermissionFlag, java.lang.String clubEmailOptStatus, java.lang.String preferredLanguage, java.lang.String storeNumber, java.lang.String terminal, java.lang.String requestorID, java.lang.String messageVersion, java.lang.String enrollmentOfferCode, java.lang.String pinNumber, java.lang.String tnCStatus, java.lang.String tnCVersion, com.epsilon.webservices.ArrayOfPhone phoneNumbers, com.epsilon.webservices.ArrayOfAffinity affinities, com.epsilon.webservices.ArrayOfAttr attributes) { 
        LOG.info("Executing operation createMember");
        System.out.println(memberNumber);
        System.out.println(emailAddress);
        System.out.println(emailValidation);
        System.out.println(prefix);
        System.out.println(suffix);
        System.out.println(firstName);
        System.out.println(middleInitial);
        System.out.println(testAccount);
        System.out.println(lastName);
        System.out.println(address1);
        System.out.println(address2);
        System.out.println(city);
        System.out.println(state);
        System.out.println(zipCode);
        System.out.println(zipCodeExtension);
        System.out.println(countryCode);
        System.out.println(dob);
        System.out.println(currentDate);
        System.out.println(currentTime);
        System.out.println(clubMembershipCreatedBy);
        System.out.println(clubDNPStatus);
        System.out.println(shcAssociateInd);
        System.out.println(cardDesignType);
        System.out.println(wirelessPermissionFlag);
        System.out.println(clubEmailOptStatus);
        System.out.println(preferredLanguage);
        System.out.println(storeNumber);
        System.out.println(terminal);
        System.out.println(requestorID);
        System.out.println(messageVersion);
        System.out.println(enrollmentOfferCode);
        System.out.println(pinNumber);
        System.out.println(tnCStatus);
        System.out.println(tnCVersion);
        System.out.println(phoneNumbers);
        System.out.println(affinities);
        System.out.println(attributes);
        try {
            com.epsilon.webservices.CreateMemberResponse.CreateMemberResult _return = new com.epsilon.webservices.CreateMemberResponse.CreateMemberResult();
            java.util.List<java.lang.Object> _returnContent = new java.util.ArrayList<java.lang.Object>();
            java.lang.Object _returnContentVal1 = null;
            _returnContent.add(_returnContentVal1);
            _return.getContent().addAll(_returnContent);
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.epsilon.webservices.ProfileSoap#updateEmailConfirmed(java.lang.String messageVersion, java.lang.String memberNumber, java.lang.String requestorID, java.lang.String currentDate, java.lang.String currentTime, java.lang.String emailAddress, java.lang.String emailConfirmed)*
     */
    public com.epsilon.webservices.UpdateEmailConfirmedResponse.UpdateEmailConfirmedResult updateEmailConfirmed(java.lang.String messageVersion, java.lang.String memberNumber, java.lang.String requestorID, java.lang.String currentDate, java.lang.String currentTime, java.lang.String emailAddress, java.lang.String emailConfirmed) { 
        LOG.info("Executing operation updateEmailConfirmed");
        System.out.println(messageVersion);
        System.out.println(memberNumber);
        System.out.println(requestorID);
        System.out.println(currentDate);
        System.out.println(currentTime);
        System.out.println(emailAddress);
        System.out.println(emailConfirmed);
        try {
            com.epsilon.webservices.UpdateEmailConfirmedResponse.UpdateEmailConfirmedResult _return = new com.epsilon.webservices.UpdateEmailConfirmedResponse.UpdateEmailConfirmedResult();
            java.util.List<java.lang.Object> _returnContent = new java.util.ArrayList<java.lang.Object>();
            java.lang.Object _returnContentVal1 = null;
            _returnContent.add(_returnContentVal1);
            _return.getContent().addAll(_returnContent);
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.epsilon.webservices.ProfileSoap#updateMemberAffinitySubscriptions(java.lang.String memberNumber, com.epsilon.webservices.ArrayOfAffinity affinities, java.lang.String messageVersion, java.lang.String requestorID, java.lang.String storeNumber, java.lang.String terminal, java.lang.String associateId, java.lang.String user)*
     */
    public com.epsilon.webservices.UpdateMemberAffinitySubscriptionsResponse.UpdateMemberAffinitySubscriptionsResult updateMemberAffinitySubscriptions(java.lang.String memberNumber, com.epsilon.webservices.ArrayOfAffinity affinities, java.lang.String messageVersion, java.lang.String requestorID, java.lang.String storeNumber, java.lang.String terminal, java.lang.String associateId, java.lang.String user) { 
        LOG.info("Executing operation updateMemberAffinitySubscriptions");
        System.out.println(memberNumber);
        System.out.println(affinities);
        System.out.println(messageVersion);
        System.out.println(requestorID);
        System.out.println(storeNumber);
        System.out.println(terminal);
        System.out.println(associateId);
        System.out.println(user);
        try {
            com.epsilon.webservices.UpdateMemberAffinitySubscriptionsResponse.UpdateMemberAffinitySubscriptionsResult _return = new com.epsilon.webservices.UpdateMemberAffinitySubscriptionsResponse.UpdateMemberAffinitySubscriptionsResult();
            java.util.List<java.lang.Object> _returnContent = new java.util.ArrayList<java.lang.Object>();
            java.lang.Object _returnContentVal1 = null;
            _returnContent.add(_returnContentVal1);
            _return.getContent().addAll(_returnContent);
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.epsilon.webservices.ProfileSoap#validatePin(java.lang.String memberNumber, java.lang.String requestorID, java.lang.String currentDate, java.lang.String currentTime, java.lang.String pinNumber, java.lang.String messageVersion)*
     */
    public com.epsilon.webservices.ValidatePinResponse.ValidatePinResult validatePin(java.lang.String memberNumber, java.lang.String requestorID, java.lang.String currentDate, java.lang.String currentTime, java.lang.String pinNumber, java.lang.String messageVersion) { 
        LOG.info("Executing operation validatePin");
        System.out.println(memberNumber);
        System.out.println(requestorID);
        System.out.println(currentDate);
        System.out.println(currentTime);
        System.out.println(pinNumber);
        System.out.println(messageVersion);
        try {
            com.epsilon.webservices.ValidatePinResponse.ValidatePinResult _return = new com.epsilon.webservices.ValidatePinResponse.ValidatePinResult();
            java.util.List<java.lang.Object> _returnContent = new java.util.ArrayList<java.lang.Object>();
            java.lang.Object _returnContentVal1 = null;
            _returnContent.add(_returnContentVal1);
            _return.getContent().addAll(_returnContent);
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.epsilon.webservices.ProfileSoap#getMemberPrimaryProfile(java.lang.String memberNumber, java.lang.String messageVersion)*
     */
    public com.epsilon.webservices.GetMemberPrimaryProfileResponse.GetMemberPrimaryProfileResult getMemberPrimaryProfile(java.lang.String memberNumber, java.lang.String messageVersion) { 
        LOG.info("Executing operation getMemberPrimaryProfile");
        System.out.println(memberNumber);
        System.out.println(messageVersion);
        try {
            com.epsilon.webservices.GetMemberPrimaryProfileResponse.GetMemberPrimaryProfileResult _return = new com.epsilon.webservices.GetMemberPrimaryProfileResponse.GetMemberPrimaryProfileResult();
            java.util.List<java.lang.Object> _returnContent = new java.util.ArrayList<java.lang.Object>();
            java.lang.Object _returnContentVal1 = null;
            _returnContent.add(_returnContentVal1);
            _return.getContent().addAll(_returnContent);
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.epsilon.webservices.ProfileSoap#updateMemberPrompts(com.epsilon.webservices.UpdateMemberPrompts parameters)*
     */
    public com.epsilon.webservices.UpdateMemberPromptsResponse updateMemberPrompts(UpdateMemberPrompts parameters) { 
        LOG.info("Executing operation updateMemberPrompts");
        System.out.println(parameters);
        try {
            com.epsilon.webservices.UpdateMemberPromptsResponse _return = new com.epsilon.webservices.UpdateMemberPromptsResponse();
            com.epsilon.webservices.UpdateMemberPromptsResponse.UpdateMemberPromptsResult _returnUpdateMemberPromptsResult = new com.epsilon.webservices.UpdateMemberPromptsResponse.UpdateMemberPromptsResult();
            java.util.List<java.lang.Object> _returnUpdateMemberPromptsResultContent = new java.util.ArrayList<java.lang.Object>();
            java.lang.Object _returnUpdateMemberPromptsResultContentVal1 = null;
            _returnUpdateMemberPromptsResultContent.add(_returnUpdateMemberPromptsResultContentVal1);
            _returnUpdateMemberPromptsResult.getContent().addAll(_returnUpdateMemberPromptsResultContent);
            _return.setUpdateMemberPromptsResult(_returnUpdateMemberPromptsResult);
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.epsilon.webservices.ProfileSoap#getPartnerEnrollmentDetails(java.lang.String memberNumber, java.lang.String source, java.lang.String requestorID, java.lang.String storeNumber, java.lang.String registerNumber, java.lang.String transactionNumber, java.lang.String associateID, java.lang.String date, java.lang.String time, java.lang.String aliasName, java.lang.String messageVersion)*
     */
    public com.epsilon.webservices.GetPartnerEnrollmentDetailsResponse.GetPartnerEnrollmentDetailsResult getPartnerEnrollmentDetails(java.lang.String memberNumber, java.lang.String source, java.lang.String requestorID, java.lang.String storeNumber, java.lang.String registerNumber, java.lang.String transactionNumber, java.lang.String associateID, java.lang.String date, java.lang.String time, java.lang.String aliasName, java.lang.String messageVersion) { 
        LOG.info("Executing operation getPartnerEnrollmentDetails");
        System.out.println(memberNumber);
        System.out.println(source);
        System.out.println(requestorID);
        System.out.println(storeNumber);
        System.out.println(registerNumber);
        System.out.println(transactionNumber);
        System.out.println(associateID);
        System.out.println(date);
        System.out.println(time);
        System.out.println(aliasName);
        System.out.println(messageVersion);
        try {
            com.epsilon.webservices.GetPartnerEnrollmentDetailsResponse.GetPartnerEnrollmentDetailsResult _return = new com.epsilon.webservices.GetPartnerEnrollmentDetailsResponse.GetPartnerEnrollmentDetailsResult();
            java.util.List<java.lang.Object> _returnContent = new java.util.ArrayList<java.lang.Object>();
            java.lang.Object _returnContentVal1 = null;
            _returnContent.add(_returnContentVal1);
            _return.getContent().addAll(_returnContent);
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.epsilon.webservices.ProfileSoap#getMemberPrompts(java.lang.String memberNumber, java.lang.String messageVersion, java.lang.String requestorID, com.epsilon.webservices.ArrayOfPromptGroup promptGroups, javax.xml.datatype.XMLGregorianCalendar currentDate, java.lang.String currentTime, java.lang.String storeNumber, java.lang.String terminal, java.lang.String includeAnswers)*
     */
    public com.epsilon.webservices.GetMemberPromptsResponse.GetMemberPromptsResult getMemberPrompts(java.lang.String memberNumber, java.lang.String messageVersion, java.lang.String requestorID, com.epsilon.webservices.ArrayOfPromptGroup promptGroups, javax.xml.datatype.XMLGregorianCalendar currentDate, java.lang.String currentTime, java.lang.String storeNumber, java.lang.String terminal, java.lang.String includeAnswers) { 
        LOG.info("Executing operation getMemberPrompts");
        System.out.println(memberNumber);
        System.out.println(messageVersion);
        System.out.println(requestorID);
        System.out.println(promptGroups);
        System.out.println(currentDate);
        System.out.println(currentTime);
        System.out.println(storeNumber);
        System.out.println(terminal);
        System.out.println(includeAnswers);
        try {
            com.epsilon.webservices.GetMemberPromptsResponse.GetMemberPromptsResult _return = new com.epsilon.webservices.GetMemberPromptsResponse.GetMemberPromptsResult();
            java.util.List<java.lang.Object> _returnContent = new java.util.ArrayList<java.lang.Object>();
            java.lang.Object _returnContentVal1 = null;
            _returnContent.add(_returnContentVal1);
            _return.getContent().addAll(_returnContent);
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.epsilon.webservices.ProfileSoap#updateMemberExtendedProfile(java.lang.String memberNumber, com.epsilon.webservices.ArrayOfExtendedProfilePreference extendedProfilePreferences)*
     */
    public com.epsilon.webservices.UpdateMemberExtendedProfileResponse.UpdateMemberExtendedProfileResult updateMemberExtendedProfile(java.lang.String memberNumber, com.epsilon.webservices.ArrayOfExtendedProfilePreference extendedProfilePreferences) { 
        LOG.info("Executing operation updateMemberExtendedProfile");
        System.out.println(memberNumber);
        System.out.println(extendedProfilePreferences);
        try {
            com.epsilon.webservices.UpdateMemberExtendedProfileResponse.UpdateMemberExtendedProfileResult _return = new com.epsilon.webservices.UpdateMemberExtendedProfileResponse.UpdateMemberExtendedProfileResult();
            java.util.List<java.lang.Object> _returnContent = new java.util.ArrayList<java.lang.Object>();
            java.lang.Object _returnContentVal1 = null;
            _returnContent.add(_returnContentVal1);
            _return.getContent().addAll(_returnContent);
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.epsilon.webservices.ProfileSoap#getMemberAffinitySubscriptions(java.lang.String memberNumber, java.lang.String messageVersion, java.lang.String requestorID, java.lang.String storeNumber, java.lang.String terminal, java.lang.String associateId, java.lang.String currentDate, java.lang.String currentTime)*
     */
    public com.epsilon.webservices.GetMemberAffinitySubscriptionsResponse.GetMemberAffinitySubscriptionsResult getMemberAffinitySubscriptions(java.lang.String memberNumber, java.lang.String messageVersion, java.lang.String requestorID, java.lang.String storeNumber, java.lang.String terminal, java.lang.String associateId, java.lang.String currentDate, java.lang.String currentTime) { 
        LOG.info("Executing operation getMemberAffinitySubscriptions");
        System.out.println(memberNumber);
        System.out.println(messageVersion);
        System.out.println(requestorID);
        System.out.println(storeNumber);
        System.out.println(terminal);
        System.out.println(associateId);
        System.out.println(currentDate);
        System.out.println(currentTime);
        try {
            com.epsilon.webservices.GetMemberAffinitySubscriptionsResponse.GetMemberAffinitySubscriptionsResult _return = new com.epsilon.webservices.GetMemberAffinitySubscriptionsResponse.GetMemberAffinitySubscriptionsResult();
            java.util.List<java.lang.Object> _returnContent = new java.util.ArrayList<java.lang.Object>();
            java.lang.Object _returnContentVal1 = null;
            _returnContent.add(_returnContentVal1);
            _return.getContent().addAll(_returnContent);
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.epsilon.webservices.ProfileSoap#getMemberAuditLookup(java.lang.String memberNumber, java.lang.String messageVersion, java.lang.String auditType, java.lang.String requestorID, java.lang.String startDateTime, java.lang.String endDateTime)*
     */
    public com.epsilon.webservices.GetMemberAuditLookupResponse.GetMemberAuditResult getMemberAuditLookup(java.lang.String memberNumber, java.lang.String messageVersion, java.lang.String auditType, java.lang.String requestorID, java.lang.String startDateTime, java.lang.String endDateTime) { 
        LOG.info("Executing operation getMemberAuditLookup");
        System.out.println(memberNumber);
        System.out.println(messageVersion);
        System.out.println(auditType);
        System.out.println(requestorID);
        System.out.println(startDateTime);
        System.out.println(endDateTime);
        try {
            com.epsilon.webservices.GetMemberAuditLookupResponse.GetMemberAuditResult _return = new com.epsilon.webservices.GetMemberAuditLookupResponse.GetMemberAuditResult();
            java.util.List<java.lang.Object> _returnContent = new java.util.ArrayList<java.lang.Object>();
            java.lang.Object _returnContentVal1 = null;
            _returnContent.add(_returnContentVal1);
            _return.getContent().addAll(_returnContent);
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.epsilon.webservices.ProfileSoap#getMemberLevel(java.lang.String memberNumber, java.lang.String messageVersion, java.lang.String requestorID)*
     */
    public com.epsilon.webservices.GetMemberLevelResponse.GetMemberLevelResult getMemberLevel(java.lang.String memberNumber, java.lang.String messageVersion, java.lang.String requestorID) { 
        LOG.info("Executing operation getMemberLevel");
        System.out.println(memberNumber);
        System.out.println(messageVersion);
        System.out.println(requestorID);
        try {
            com.epsilon.webservices.GetMemberLevelResponse.GetMemberLevelResult _return = new com.epsilon.webservices.GetMemberLevelResponse.GetMemberLevelResult();
            java.util.List<java.lang.Object> _returnContent = new java.util.ArrayList<java.lang.Object>();
            java.lang.Object _returnContentVal1 = null;
            _returnContent.add(_returnContentVal1);
            _return.getContent().addAll(_returnContent);
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.epsilon.webservices.ProfileSoap#getMemberTargetedOffers(com.epsilon.webservices.GetMemberTargetedOffers parameters)*
     */
    public java.lang.Object getMemberTargetedOffers(GetMemberTargetedOffers parameters) { 
        LOG.info("Executing operation getMemberTargetedOffers");
        System.out.println(parameters);
        try {
            java.lang.Object _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.epsilon.webservices.ProfileSoap#validateMember(java.lang.String memberNumber, java.lang.String firstName, java.lang.String lastName, java.lang.String messageVersion)*
     */
    public com.epsilon.webservices.ValidateMemberResponse.ValidateMemberResult validateMember(java.lang.String memberNumber, java.lang.String firstName, java.lang.String lastName, java.lang.String messageVersion) { 
        LOG.info("Executing operation validateMember");
        System.out.println(memberNumber);
        System.out.println(firstName);
        System.out.println(lastName);
        System.out.println(messageVersion);
        try {
            com.epsilon.webservices.ValidateMemberResponse.ValidateMemberResult _return = new com.epsilon.webservices.ValidateMemberResponse.ValidateMemberResult();
            java.util.List<java.lang.Object> _returnContent = new java.util.ArrayList<java.lang.Object>();
            java.lang.Object _returnContentVal1 = null;
            _returnContent.add(_returnContentVal1);
            _return.getContent().addAll(_returnContent);
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.epsilon.webservices.ProfileSoap#registerMember(java.lang.String memberNumber, java.lang.String emailAddress, java.lang.String emailValidation, java.lang.String zipCode, java.lang.String zipCodeExtension, java.lang.String shcAssociateInd, java.lang.String messageVersion, java.lang.String currentDate, java.lang.String currentTime)*
     */
    public com.epsilon.webservices.RegisterMemberResponse.RegisterMemberResult registerMember(java.lang.String memberNumber, java.lang.String emailAddress, java.lang.String emailValidation, java.lang.String zipCode, java.lang.String zipCodeExtension, java.lang.String shcAssociateInd, java.lang.String messageVersion, java.lang.String currentDate, java.lang.String currentTime) { 
        LOG.info("Executing operation registerMember");
        System.out.println(memberNumber);
        System.out.println(emailAddress);
        System.out.println(emailValidation);
        System.out.println(zipCode);
        System.out.println(zipCodeExtension);
        System.out.println(shcAssociateInd);
        System.out.println(messageVersion);
        System.out.println(currentDate);
        System.out.println(currentTime);
        try {
            com.epsilon.webservices.RegisterMemberResponse.RegisterMemberResult _return = new com.epsilon.webservices.RegisterMemberResponse.RegisterMemberResult();
            java.util.List<java.lang.Object> _returnContent = new java.util.ArrayList<java.lang.Object>();
            java.lang.Object _returnContentVal1 = null;
            _returnContent.add(_returnContentVal1);
            _return.getContent().addAll(_returnContent);
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.epsilon.webservices.ProfileSoap#createPartnerEnrollmentDetails(java.lang.String memberUniqueId, java.lang.String memberNumber, java.lang.String registrationUniqueId, java.lang.String serviceRegistrationNumber, java.lang.String enrollmentDate, java.lang.String unenrollmentDate, java.lang.String mobileNumber, java.lang.String registrationIndicator, java.lang.String enrollmentIndicator, java.lang.String source, java.lang.String serviceEnrollmentDate, java.lang.String serviceUnenrollmentDate, java.lang.String storeNumber, java.lang.String requestorID, java.lang.String registerNumber, java.lang.String transactionNumber, java.lang.String associateID, java.lang.String date, java.lang.String time, java.lang.String aliasName, java.lang.String messageVersion)*
     */
    public com.epsilon.webservices.CreatePartnerEnrollmentDetailsResponse.CreatePartnerEnrollmentDetailsResult createPartnerEnrollmentDetails(java.lang.String memberUniqueId, java.lang.String memberNumber, java.lang.String registrationUniqueId, java.lang.String serviceRegistrationNumber, java.lang.String enrollmentDate, java.lang.String unenrollmentDate, java.lang.String mobileNumber, java.lang.String registrationIndicator, java.lang.String enrollmentIndicator, java.lang.String source, java.lang.String serviceEnrollmentDate, java.lang.String serviceUnenrollmentDate, java.lang.String storeNumber, java.lang.String requestorID, java.lang.String registerNumber, java.lang.String transactionNumber, java.lang.String associateID, java.lang.String date, java.lang.String time, java.lang.String aliasName, java.lang.String messageVersion) { 
        LOG.info("Executing operation createPartnerEnrollmentDetails");
        System.out.println(memberUniqueId);
        System.out.println(memberNumber);
        System.out.println(registrationUniqueId);
        System.out.println(serviceRegistrationNumber);
        System.out.println(enrollmentDate);
        System.out.println(unenrollmentDate);
        System.out.println(mobileNumber);
        System.out.println(registrationIndicator);
        System.out.println(enrollmentIndicator);
        System.out.println(source);
        System.out.println(serviceEnrollmentDate);
        System.out.println(serviceUnenrollmentDate);
        System.out.println(storeNumber);
        System.out.println(requestorID);
        System.out.println(registerNumber);
        System.out.println(transactionNumber);
        System.out.println(associateID);
        System.out.println(date);
        System.out.println(time);
        System.out.println(aliasName);
        System.out.println(messageVersion);
        try {
            com.epsilon.webservices.CreatePartnerEnrollmentDetailsResponse.CreatePartnerEnrollmentDetailsResult _return = new com.epsilon.webservices.CreatePartnerEnrollmentDetailsResponse.CreatePartnerEnrollmentDetailsResult();
            java.util.List<java.lang.Object> _returnContent = new java.util.ArrayList<java.lang.Object>();
            java.lang.Object _returnContentVal1 = null;
            _returnContent.add(_returnContentVal1);
            _return.getContent().addAll(_returnContent);
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.epsilon.webservices.ProfileSoap#getRewardBalance(java.lang.String requestorID, java.lang.String storeNumber, java.lang.String currentDate, java.lang.String currentTime, java.lang.String associateID, java.lang.String memberNumber, java.lang.String pointType, java.lang.String messageVersion)*
     */
    public com.epsilon.webservices.GetRewardBalanceResponse.GetRewardBalanceResult getRewardBalance(java.lang.String requestorID, java.lang.String storeNumber, java.lang.String currentDate, java.lang.String currentTime, java.lang.String associateID, java.lang.String memberNumber, java.lang.String pointType, java.lang.String messageVersion) { 
        LOG.info("Executing operation getRewardBalance");
        System.out.println(requestorID);
        System.out.println(storeNumber);
        System.out.println(currentDate);
        System.out.println(currentTime);
        System.out.println(associateID);
        System.out.println(memberNumber);
        System.out.println(pointType);
        System.out.println(messageVersion);
        try {
            com.epsilon.webservices.GetRewardBalanceResponse.GetRewardBalanceResult _return = new com.epsilon.webservices.GetRewardBalanceResponse.GetRewardBalanceResult();
            java.util.List<java.lang.Object> _returnContent = new java.util.ArrayList<java.lang.Object>();
            java.lang.Object _returnContentVal1 = null;
            _returnContent.add(_returnContentVal1);
            _return.getContent().addAll(_returnContent);
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.epsilon.webservices.ProfileSoap#getMemberLookup(java.lang.String messageVersion, java.lang.String memberNumber, java.lang.String emailAddress, java.lang.String id, java.lang.String type, java.lang.String phoneNumber, java.lang.String storeNumber, java.lang.String terminal, java.lang.String requestorID, java.lang.String searchType, java.lang.String currentDate, java.lang.String currentTime, java.lang.String maxRecords, java.lang.String maxPOSPrompt, com.epsilon.webservices.ArrayOfPromptGroup promptGroups, java.lang.String firstName, java.lang.String lastName, java.lang.String zipCode)*
     */
    public com.epsilon.webservices.GetMemberLookupResponse.GetMemberLookupResult getMemberLookup(java.lang.String messageVersion, java.lang.String memberNumber, java.lang.String emailAddress, java.lang.String id, java.lang.String type, java.lang.String phoneNumber, java.lang.String storeNumber, java.lang.String terminal, java.lang.String requestorID, java.lang.String searchType, java.lang.String currentDate, java.lang.String currentTime, java.lang.String maxRecords, java.lang.String maxPOSPrompt, com.epsilon.webservices.ArrayOfPromptGroup promptGroups, java.lang.String firstName, java.lang.String lastName, java.lang.String zipCode) { 
        LOG.info("Executing operation getMemberLookup");
        System.out.println(messageVersion);
        System.out.println(memberNumber);
        System.out.println(emailAddress);
        System.out.println(id);
        System.out.println(type);
        System.out.println(phoneNumber);
        System.out.println(storeNumber);
        System.out.println(terminal);
        System.out.println(requestorID);
        System.out.println(searchType);
        System.out.println(currentDate);
        System.out.println(currentTime);
        System.out.println(maxRecords);
        System.out.println(maxPOSPrompt);
        System.out.println(promptGroups);
        System.out.println(firstName);
        System.out.println(lastName);
        System.out.println(zipCode);
        try {
            com.epsilon.webservices.GetMemberLookupResponse.GetMemberLookupResult _return = new com.epsilon.webservices.GetMemberLookupResponse.GetMemberLookupResult();
            java.util.List<java.lang.Object> _returnContent = new java.util.ArrayList<java.lang.Object>();
            java.lang.Object _returnContentVal1 = null;
            _returnContent.add(_returnContentVal1);
            _return.getContent().addAll(_returnContent);
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.epsilon.webservices.ProfileSoap#getMemberExtendedProfile(java.lang.String memberNumber, java.lang.String messageVersion)*
     */
    public com.epsilon.webservices.GetMemberExtendedProfileResponse.GetMemberExtendedProfileResult getMemberExtendedProfile(java.lang.String memberNumber, java.lang.String messageVersion) { 
        LOG.info("Executing operation getMemberExtendedProfile");
        System.out.println(memberNumber);
        System.out.println(messageVersion);
        try {
            com.epsilon.webservices.GetMemberExtendedProfileResponse.GetMemberExtendedProfileResult _return = new com.epsilon.webservices.GetMemberExtendedProfileResponse.GetMemberExtendedProfileResult();
            java.util.List<java.lang.Object> _returnContent = new java.util.ArrayList<java.lang.Object>();
            java.lang.Object _returnContentVal1 = null;
            _returnContent.add(_returnContentVal1);
            _return.getContent().addAll(_returnContent);
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

}
